title: Short course on Mathematical Epidemiology (Arba Minch 2023)
logo: /assets/img/vibrio-cholerae.jpeg
description: Material used for teaching the course, including slides and R code.
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-1943806-8
plugins:
  - jekyll-sitemap
