%\SweaveUTF8
\documentclass[aspectratio=43]{beamer}

\input{slides_setup_nonLightBoard_whiteBG.tex}

\title{Models incorporating a spatial component}
\subtitle{Potchefstroom -- Course 02}
\author{Julien Arino}
\date{21 February 2024}


\begin{document}
\SweaveOpts{concordance=TRUE}
\SweaveOpts{prefix.string = FIGS/lecture-04}

% The title page
\begin{frame}[noframenumbering,plain]
  \begin{tikzpicture}[remember picture,overlay]
    \node[above right,inner sep=0pt,opacity=0.2] at (current page.south west)
    {
      \includegraphics[height=\paperheight,width=\paperwidth]{FIGS/Gemini-generated-viruses-bacteria-Dali-style-1.jpeg}
    };
\end{tikzpicture}
  \setbeamercolor{title}{fg=subsub_header_section}
  \setbeamercolor{author}{fg=subsub_header_section} 
  \setbeamerfont{title}{size=\Large,series=\bfseries}
  \setbeamerfont{author}{size=\Large,series=\bfseries}
  \setbeamerfont{date}{series=\bfseries}
  %\setbeamerfont{date}{size=\small,series=\mdseries}
	\titlepage
\end{frame}
\addtocounter{page}{-1}


\frame{\frametitle{Diseases have been known to be mobile for a while}
\framesubtitle{The plague of Athens of 430 BCE}
\begin{minipage}{0.7\textwidth}
It first began, it is said, in the parts of Ethiopia above Egypt, and
thence descended into Egypt and Libya and into most of the [Persian] King's
country. Suddenly falling upon Athens, it first attacked the
population in Piraeus 
%-- which was the occasion of their saying that the Peloponnesians had poisoned the reservoirs, there being as yet no wells there--
[..]
and afterwards appeared in the upper city, when the
deaths became much more frequent. 
\begin{flushright}
Thucydides (c. 460 BCE - c. 395 BCE)\\
History of the Peloponnesian War
\end{flushright}
\end{minipage}\quad
\begin{minipage}{0.25\textwidth}
\begin{center}
\includegraphics[width=0.9\textwidth]{FIGS/Thucydides-bust-noBG}
\end{center}
\end{minipage}
}


% The outline page
{
\setbeamercolor{background canvas}{bg=outline_colour}
\begin{frame}{Outline}
    \tableofcontents[hideallsubsections]
\end{frame}
\addtocounter{page}{-1}
}

%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
\section{Spatio-temporal spread of diseases}

\begin{frame}{Pathogen spread has evolved with mobility}
Pathogens use trade routes 
\vfill 
In ancient times, trade routes were ``simple''
\end{frame}

\maxFrameImage{FIGS/trade_routes_1478AD}
\maxFrameImage{FIGS/population-moyen-age-grande-peste-carte}
\maxFrameImage{FIGS/RossOnWye_plagueCross}
\maxFrameImage{FIGS/RossOnWye_plagueCross_zoom}


\begin{frame}{Pathogen spread has evolved with mobility}
Pathogens use trade routes 
\vfill 
With the acceleration and globalization of mobility, things are changing
\end{frame}

\maxFrameImage{FIGS/MapOfFranceWithHenriIV}
\maxFrameImage{FIGS/LiverpoolToWinnipeg}
\maxFrameImage{FIGS/travelTimesFromWinnipeg}
\maxFrameImage{FIGS/duration_Paris_Bordeaux}
\maxFrameImage{FIGS/traveltimes_france_tgv}
\maxFrameImage{FIGS/TravelTimesFromMX}

\begin{frame}{Scale of modern mobility difficult to apprehend}
\begin{block}{Working definition}
\textbf{Mobility} is the collection of processes through which individuals change their current location
\end{block}
\vfill
Takes many different forms \vfill Evolves constantly \vfill  Numbers are
.. colossal
\end{frame}

\maxFrameImage{FIGS/passengers_transported_worldwide}

\begin{frame}{Why mobility is important in the context of health}

\begin{block}{}
All migrants/travellers carry with them their ``health history''
\end{block}
\begin{itemize}
\item latent and/or active infections (TB, H1N1, polio)
\item immunizations (schedules vary by country)
\item health/nutrition practices (KJv)
\item treatment methods (antivirals)
\end{itemize}
\begin{block}{}
Pathogens ignore borders and politics
\end{block}     
\begin{itemize}
\item e.g., antiviral treatment policies for Canada and USA
\end{itemize}
\end{frame}
	

%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
\section{Metapopulation models}
%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
\subsection{Why use metapopulation models?}

\frame {\frametitle{Why use metapopulations for disease models?}
\begin{itemize}
\item Appropriate for the description of spatial spread of some diseases
\vfill
\item Ease of simulation
\vfill
\item Aggregation of data by governments is most often done at the jurisdictional level, very easy to reconcile with locations in metapopulations
\end{itemize}
}

\begin{frame}{A few pointers}
	\begin{itemize}
		\item JA \& PvdD. \href{https://julien-arino.github.io/assets/pdf/papers/2006_ArinoPvdD-FIC48.pdf}{Disease spread in metapopulations}. \emph{Fields Institute Communications} \textbf{48}:1-13 (2006)
		\item JA. \href{https://julien-arino.github.io/assets/pdf/papers/2009_Arino-metapopulations.pdf}{Diseases in metapopulations}. In \emph{Modeling and Dynamics of Infectious Diseases}, World Scientific (2009)
		\item JA. \href{https://doi.org/10.1016/j.idm.2017.05.001}{Spatio-temporal spread of infectious pathogens of humans}. \emph{Infectious Disease Modelling} \textbf{2}(2):218-228 (2017)
	\end{itemize}
\end{frame}


%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
\subsection[Explicit movement]{Metapopulations with explicit movement}

\frame{\frametitle{Metapopulations with explicit movement}
	Split continuous space into $N$ discrete geographical locations (\emph{ptatches})
	\vfill
	Each location contains \textbf{compartments} (homogeneous groups of individuals). E.g., preys, predators, etc. 
	\vfill
	Here, we consider a single compartment, the \emph{species of interest}, with no further compartmentalisation
	\vfill
	Individuals \emph{may} move between locations; $m_{qp}\geq 0$ rate of movement of individuals from location $p=1,\ldots,N$ to location $q=1,\ldots,N$
	\vfill
}

\frame{\frametitle{Explicit movement (focus on $P_1$)}
	\begin{center}		
	\begin{tikzpicture}[auto, %node distance = 2cm, auto,
	cloud/.style={minimum width={width("N-1")+2pt},
		draw, ellipse,fill=red!20}]
	\node [cloud] (P1) {$P_1$};
	\node [cloud, above right=of P1] (P2) {$P_2$};
	\node [cloud, right=of P1] (P3) {$P_3$};
	\node [cloud, below right=of P1] (P4) {$P_4$};
	\node [cloud, below=of P1] (P5) {$P_5$};
	\node [cloud, below left=of P1] (P6) {$P_6$};
	\node [cloud, above left=of P1] (Pk) {$P_k$};
	%% Outflows
	\path [line, very thick, blue] (P1) to [bend left = 20] node [midway, left] (TextNode) {$m_{21}$} (P2);
	\path [line, very thick, blue] (P1) to [bend left = 20] node [midway, below] (TextNode) {$m_{31}$} (P3);
	\path [line, very thick, blue] (P1) to [bend left = 20] node [pos=0.9, right] (TextNode) {$m_{51}$} (P5);
	\path [line, very thick, blue] (P1) to [bend left = 20] node [midway, right] (TextNode) {$m_{61}$} (P6);
	\path [line, very thick, blue, densely dashed] (P1) to [bend left = 20] node [midway, left] (TextNode) {$m_{k1}$} (Pk);
	%% Inflows
	\path [line, very thick, red] (P2) to [bend left = 20] node [midway, right] (TextNode) {$m_{12}$} (P1);
	\path [line, very thick, red] (P4) to [bend left = 20] node [right] (TextNode) {$m_{14}$} (P1);
	\path [line, very thick, red] (P6) to [bend left = 20] node [left] (TextNode) {$m_{16}$} (P1);
	\path [line, very thick, red, densely dashed] (Pk) to [bend left = 20] node [right, pos=0.1] (TextNode) {$m_{1k}$} (P1);
	\end{tikzpicture}
	\end{center}
	\[
	P_1' = {\red \sum_{\substack{j=1\\j\neq 1}}^{N}m_{1j}P_j}
	{\blue -P_1\sum_{\substack{j=1\\j\neq 1}}^{N}m_{j1}}
	\]
	or
	\[
	P_1' = \sum_{j=1}^{N} m_{1j}P_j
	\textrm{ assuming }
	m_{11}=-\sum_{\substack{j=1\\j\neq 1}}^{N} m_{j1}
	\]
}



%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
\subsection{The graph setting}


\begin{frame}\frametitle{Graph setting}
Suppose
\begin{itemize} 
\item $|\P|$ locations, vertices in a (directed) graph $\G$
\item Each location contains a certain number of compartments belonging to a common set $\C$ of compartments
\item Arcs of $\G$ represent the possibility for a given compartment to move between two locations; any two locations are connected by a maximum of $|\C|$ edges
\end{itemize}
\vfill
Graph is a digraph: movement is not always symmetric
\end{frame}


\begin{frame}
$\G=(\P,\A)$ is multi-digraph, where 
\begin{itemize}
	\item $\P$ is the set of vertices (locations)
	\item $\A$ is the set of arcs, i.e., an ordered multiset of pairs of elements of $\P$
\end{itemize}
\vfill
Any two vertices $X,Y\in\P$ are connected by at most $|\C|$ arcs from $X$ to $Y$ and at most $|\C|$ arcs from $Y$ to $X$
\vfill
Because there are $|\C|$ compartments and movements are compartment-specific, we also define, for all $c\in\C$, $\P_c$ and $\A_c$ as well as the compartment-specific digraphs $\G^c=(\P_c,\A_c)$
\end{frame}



\frame{\frametitle{Connection matrix}
For a given compartment $c\in\C$, a \emph{connection matrix} can be associated to the digraph $\G_c$
\vfill
This is the \textbf{adjacency matrix} of $\G_c$, but we emphasize the reason why we use $\G_c$ by using the term \emph{connection}
\vfill
Choosing an ordering of elements of $\P$, the $(i,j)$ entry of the $|\P|\times|\P|$-matrix $\N_c=\N_c(\G_c)$ is one if $R^c(P_i,P_j)$ and zero otherwise, i.e., if $P_i$ has no direct access to $P_j$
\vfill
For convenience, the ordering of the locations is generally assumed the same for all compartments
}


\frame{\frametitle{Srong connectedness and irreducibility}
\begin{definition}[Reducible/irreducible matrix]
	\label{def:reducible_irreducible_matrix}
	A matrix $A$ is \textbf{reducible} if there exists a permutation matrix $P$ such that $P^TAP$ is block upper triangular. A matrix that is not reducible is \textbf{irreducible}
\end{definition}
\vfill
Matrix $A\in\IF^{n\times n}$ is irreducible if for all $i,j=1,\ldots,n$, there exists $k$ such that $a_{ij}^k>0$, where $a_{ij}^k$ is the $(i,j)$-entry in $A^k$
\vfill
\begin{theorem}
	Strong connectedness $\Leftrightarrow$ \textbf{irreducibility} of the connection matrix $\mathcal{C}_c$
\end{theorem}
}


%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
\subsection{Generic model}

\frame{
Dynamics of the system:
\begin{itemize}
\item dynamics in each location resulting from the interactions of the various compartments, 
\item operator describing the movements of individuals between the locations.
\end{itemize}
}

\begin{frame}{A very simple example to facilitate ingestion}
	Suppose an SIS model over a set $\P$ of locations. If need be, choose an order on elements of $\P$ and index locations as $1,\ldots,|\P|$
	\vfill
	Let $S_p$ and $I_p$ be number of susceptible and infectious individuals in location $p\in\P$, respectively
	\vfill 
	Then, in location $p\in\P$, dynamics governed by
	\begin{subequations}
		\label{sys:sample_SIS}
		\begin{align}
			S_p' &= b_p - \beta_pS_pI_p +\gamma_pI_p -d_pS_p +\sum_{q\in\P}m_{Spq}S_q\\
			I_p' &= \beta_pS_pI_p -\gamma_pI_p -d_pI_p+\sum_{q\in\P}m_{Ipq}I_q
		\end{align}
	\end{subequations}
	\vfill
	(Don't worry about why this is a metapopulation model this far)
\end{frame}

\frame{\frametitle{Notation}
\begin{itemize}
	\item $N_{cp}(t)$ number of individuals of compartment $c$ in location $p$ at time $t$
	\vfill
	(Here and elsewhere: omit dependence on $t$ unless it causes confusion)
	\vfill
	\item $N_c=\left(N_{c1},\ldots,N_{c|\P|}\right)^T$ distribution of individuals of compartment $c\in\C$ among the different locations 
	\newline
	[E.g., for \eqref{sys:sample_SIS}, $N_S=(S_1,\ldots,S_{|\P|})^T$]
	\vfill
	\item $N^p=\left(N_1^p,\ldots,N_{|\P|}^p\right)^T$ composition of the population in location $p\in\P$
	\newline
	[E.g., for \eqref{sys:sample_SIS}, $N^p=(S_p,I_p)^T$]
\end{itemize}
}

\frame{\frametitle{General form of the system}
Interaction function $f$ and movement operator $M$ can be time-dependent (not shown)
\begin{itemize}
\item Equation by equation; for all $c\in\C$ and $p\in\P$
\begin{equation}\label{sys:metapop_Nsp}
\frac{d}{dt}N_{cp}=f_{cp}(N^p)+M_{cp}(N_s)
\end{equation}
with $f_{cp}:\mathbb{R}^{|\P|}\to\mathbb{R}$ and $M_{cp}:\mathbb{R}^{|\C|}\to\mathbb{R}$
\item Compartment by compartment; for all $c\in\C$
\begin{equation}\label{sys:metapop_Ns}
\frac{d}{dt}N_c =f^p(N^p)+M_c(N_c)
\end{equation}
with $f^p:\mathbb{R}^{|\P|}\to\mathbb{R}^{|\C|}$ and $M_s^p:\mathbb{R}^{|\C|}\to\mathbb{R}^{|\C|}$
\item Location by location; for all $p=1,\ldots,|\P|$
\begin{equation}\label{sys:metapop_Np}
\frac{d}{dt}N^p =f^p(N^p)+M^p(N^p)
\end{equation}
with $f^p:\mathbb{R}^{|\P|}\to\mathbb{R}^{|\C|}$ and $M_s^p:\mathbb{R}^{|\C|}\to\mathbb{R}^{|\C|}$
\end{itemize}
}


\frame{\frametitle{Metapopulation models with linear movement}
Use a linear autonomous movement operator
\vfill
Then, for a given compartment $c\in\C$ and in a given location $p\in\P$
\[
	N_{cp}'=f_{cp}(N^p)
	+\sum\dind{q\in\P}{q\neq p}m_{cpq}N_{cq} 
	-\left(\sum\dind{q\in\P}{q\neq p}m_{cqp}\right)N_{cp}
\]
where $m_{cpq}$ rate of movement of individuals in compartment $c\in\C$ from location $q\in\P$ to location $p\in\P$
}

\begin{frame}{A more compact notation}
	To make 
	\[
		N_{cp}'=f_{cp}(N^p)
		+\sum\dind{q\in\P}{q\neq p}m_{cpq}N_{cq} 
		-\left(\sum\dind{q\in\P}{q\neq p}m_{cqp}\right)N_{cp}
	\]
	more compact, denote the rate of leaving location $p$ as
	\begin{equation}
		m_{cpp} = -\sum\dind{q\in\P}{q\neq p}m_{cqp}
	\end{equation}
	Then
	\begin{equation}\label{eq:general_metapop_linear_migration}
		N_s'=f_{cp}(N^p)+\sum_{q\in\P}m_{cpq}N_{cq}
	\end{equation}
\end{frame}

\begin{frame}{Vector form of the system}
For compartment $c\in\C$,
\begin{equation}\label{eq:general_metapop}
N_c'=f(N)+\mathcal{M}_cN_c
\end{equation}
with
\begin{equation}\label{eq:movement_matrix}
\mathcal{M}_c =
\begin{pmatrix}
-\sum\limits_{k\in\P}m_{ck1} & m_{c12} & \cdots & m_{c1|\P|} \\
& & & \\
m_{c|\P|1} & m_{c|\P|2} & \cdots & -\sum\limits_{k\in\P}m_{ck|\P|}
\end{pmatrix}
\end{equation}
\end{frame}


%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%
\subsection{The movement matrix}

\begin{frame}{Definitions and notation for matrices}
\begin{itemize}
	\item $M\in\mathbb{R}^{n\times n}$ a square matrix with entries denoted $m_{ij}$
	\vfill
	\item $M\geq\mathbf{0}$ if $m_{ij}\geq 0$ for all $i,j$ (could be the zero matrix); $M>\mathbf{0}$ if $M\geq\mathbf{0}$ and $\exists i,j$ with $m_{ij}>0$; $M\gg\mathbf{0}$ if $m_{ij}>0$ $\forall i,j=1,\ldots,n$. Same notation for vectors
	\vfill
	\item $\sigma(M)=\{\lambda\in\mathbf{C}; M\lambda=\lambda\mathbf{v}, \mathbf{v}\neq\mathbf{0}\}$ \textbf{spectrum} of $M$
	\vfill
	\item $\rho(M)=\max_{\lambda\in\sigma(M)}\{|\lambda|\}$ \textbf{spectral radius}
	\vfill
	\item $s(M)=\max_{\lambda\in\sigma(M)}\{\Re(\lambda)\}$ \textbf{spectral abscissa} (or \textbf{stability modulus})
	\vfill
	\item $M$ is an \textbf{M-matrix} if it is a \textbf{Z-matrix} ($m_{ij}\leq 0$ for $i\neq j$) and $M = s\mathbb{I}-A$, with $A\geq 0$ and $s\geq \rho(A)$
\end{itemize}
\end{frame}

\begin{frame}{The movement matrix}
	The matrix
	\begin{equation}\tag{\ref{eq:movement_matrix}}
		\mathcal{M}_c =
		\begin{pmatrix}
		-\sum\limits_{k\in\P}m_{ck1} & m_{c12} & \cdots & m_{c1|\P|} \\
		& & & \\
		m_{c|\P|1} & m_{c|\P|2} & \cdots & -\sum\limits_{k\in\P}m_{ck|\P|}
		\end{pmatrix}
	\end{equation}
	is the \textbf{movement matrix}
	\vfill
	It plays an extremely important role in the analysis of metapopulation systems, so we'll spend some time discussing its properties
	\vfill
$\mathcal{M}_c$ describes
\begin{itemize} 
\item existence of connections
\item when they exist, their ``intensity''
\end{itemize}
\end{frame}

\begin{frame}{Properties of the movement matrix $\M$}
	First, remark $-\M_c$ is a Lagrangian matrix (cf. Michael's course)
	\vfill
	\begin{lemma}\label{lemma:behaviour_Mc}
		\begin{enumerate}
			\item $0\in\sigma(\M)$ corresponding to left e.v. $\11^T$ \hfill[$\sigma$ spectrum]
			\item $-\M$ is a singular M-matrix
			\item $0=s(\M)\in\sigma(\M)$ \hfill[$s$ spectral abscissa]
			\item If $\M$ irreducible, then $s(\M)$ has multiplicity 1
		\end{enumerate}
	\end{lemma}
	\vfill
	For complete proof of Lemma~\ref{lemma:behaviour_Mc} and Proposition~\ref{prop:behaviour_Mc} (next page), see \href{http://dx.doi.org/10.1007/s11538-019-00593-1}{Arino, Bajeux \& Kirkland, BMB 2019}
\end{frame}

\begin{frame}
	\begin{proposition}[$D$ a diagonal matrix]
		\label{prop:behaviour_Mc}
		\begin{enumerate}
			\item $s(\M+d\II)=d$, $\forall d\in\IR$
			\item $s(\M+D)\in\sigma(\M+D)$ associated to $\bv>\b0$. If $\M$ irreducible, $s(\M+D)$ has  multiplicity 1 and is associated to $\bv\gg \b0$
			\item If $\diag (D)\gg \b0$, then $D-\M$ invertible M-matrix and $(D-\M)^{-1}> \b0$
			\item $\M$ irreducible and $\diag(D)>\b0$ $\Longrightarrow$ $D-\M$ nonsingular irreducible M-matrix and $(D-\M)^{-1}\gg \b0$		
		\end{enumerate}
	\end{proposition}
\end{frame}


%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%
\subsection{Behaviour of the mobility component}
\frame{\frametitle{Behaviour of the mobility component -- No demography}
Assume no within-location dynamics, just movement. Then \eqref{eq:general_metapop} takes the form
\begin{equation}\label{eq:mobility_compartment}
	N_c' = \mathcal{M}_cN_c
\end{equation}
\vfill
\begin{theorem}\label{th:GAS_metapop1}
For a given compartment $c\in\C$, suppose that the movement matrix $\M_c$ is irreducible. Then for any $N_c(0)>0$, \eqref{eq:mobility_compartment} satisfies
\[
\lim_{t\to\infty}N_c(t)=N_c^\star\gg 0
\]
\end{theorem}
\vfill
Note that $N_c^\star$ depends on $\nbOne^TN_c(0)$
}


\begin{frame}{Reduction to total population per location -- Demography}
Let 
\[
	T_p = \sum_{c\in\C}N_{cp}
\]
be the total population in location $p$
\vfill
It is often posssible to obtain, in each location $p\in\P$, an equation for the evolution of the total population that takes the form
\begin{equation}\label{eq:dT_total_population}
	T_p' = 
	D_p(T_p)+\sum_{c\in\C}\sum_{q\in\P}m_{cpq}N_{cq}
\end{equation}
where $D_p(T_p)$ describes the demography in location $p$
\end{frame}

\begin{frame}{Nature of the demography}
	Most common types of demographic functions
	\begin{itemize}
		\item $D_p(T_p)=b_p-d_pT_p$ (asymptotically constant population)
		\item $D_p(T_p)=b_pT_p-d_pT_p$ 
		\item $D_p(T_p)=d_pT_p-d_pT_p=0$ (constant population)
		\item $D_p(T_p)=r_pT_p(1-T_p/K_p)$ (logistic demography)
	\end{itemize}
	\vfill
	In what follows, assume 
	\begin{equation}\label{eq:demography_function}
		D_p(T_p)=b_p-d_pT_p
	\end{equation}
\end{frame}

\begin{frame}{Vector / matrix form of the equation}
Assuming demography is of the form \eqref{eq:demography_function}, write \eqref{eq:dT_total_population} in vector form
\begin{equation}\label{sys:dN_general} 
	\mathbf{T}'=\mathbf{b}-\bd\bT+\sum_{c\in\C}\mathcal{M}_c\bN_{c}	
\end{equation}
where 
\begin{itemize}
	\item $\mathbf{b}=(b_1,\ldots,b_{|\mathcal{P}|})^T\in\IR^{|\P|}$
	\item $\mathbf{T}=(T_1,\ldots,T_{|\mathcal{P}|})^T\in\IR^{|\P|}$
	\item $\mathbf{N}=(N_{c1},\ldots,N_{c{|\mathcal{P}|}})^T\in\IR^{|\P|}$
	\item $\bd=\mathsf{diag}\left(d_1,\ldots,d_{|\mathcal{P}|}\right)\in\IR^{|\mathcal{P}|\times|\mathcal{P}|}$
	\item $\mathcal{M}_c\in\IR^{|\mathcal{P}|\times|\mathcal{P}|}$
\end{itemize}

\end{frame}

\frame{\frametitle{Movement similar for all compartments}
\begin{definition}[Movement similar for all compartments]
\label{def:mvt_similar_for_all_compartments}
Movement is \textbf{similar for all compartments} if, in the multi-digraph $\mathcal{G}$, existence of a $c\in\C$ such that $R^c(X,Y)$ implies that $R^c(X,Y)$ for all $c\in\C$
\end{definition}
}


\begin{frame}{The nice case}
Suppose movement rates \textbf{equal for all compartments}, i.e.,
$$
\M_c\equiv\M
$$
\vfill
(stronger than Definition~\ref{def:mvt_similar_for_all_compartments}, which only requires zero/nonzero patterns in all $\M_c$, $c\in\C$, to be the same)
\vfill
Then
\begin{align}
\bT' &= \bb-\bd\bT+\M\sum_{c\in\C}\bN_{c} \nonumber \\
&= \bb-\bd\bT+\M\bT \label{sys:pSLIRS_toy_dN}
\end{align}
\end{frame}


\begin{frame}{Equilibria}
$$
\begin{aligned}
\bT'=\b0 &\Leftrightarrow \mathbf{b}-\bd\mathbf{T}+\mathcal{M}\mathbf{T}=\mathbf{0} \\
&\Leftrightarrow (\bd-\mathcal{M})\mathbf{T}=\mathbf{b} \\
&\Leftrightarrow \mathbf{T}^\star=(\bd-\mathcal{M})^{-1}\mathbf{b}
\end{aligned}
$$
given, of course, that $\bd-\mathcal{M}$ (or, equivalently, $\mathcal{M}-\bd$) is invertible.. 
\vfill
Is it?
\end{frame}

\begin{frame}{Nonsingularity of $\mathcal{M}-\bd$}
Using the spectrum shift of Theorem~\ref{prop:behaviour_Mc}{(1)}
\[
s\left(\mathcal{M}-\min_{p\in\mathcal{P}}d_p\right)=-\min_{p\in\mathcal{P}}d_p
\]
This gives a constraint: for total population to behave well (in general, we want this), we \emph{must assume all death rates are positive}
\vfill
Assume they are (in other words, assume $\bd$ nonsingular). Then $\mathcal{M}-\bd$ is nonsingular and $\bT^\star=(\bd-\mathcal{M})^{-1}\mathbf{b}$ unique
\end{frame}


\begin{frame}{Behaviour of the total population}
\framesubtitle{Equal irreducible movement case}
$\mathbf{T}^\star=(\bd-\mathcal{M})^{-1}\mathbf{b}$ attracts solutions of
$$
\mathbf{T}'=\mathbf{b}-\bd\mathbf{T}+\mathcal{M}\mathbf{T}=:f(\mathbf{T})
$$
\vfill
Indeed, we have
$$
Df=\mathcal{M}-\bd
$$
\vfill
Since we now assume that $\bd$ is nonsingular, we have by Theorem~\ref{prop:behaviour_Mc}{(1)} that $s(\mathcal{M}-\min_{p\in\mathcal{P}}d_p)=-\min_{p\in\mathcal{P}}d_p<0$
\vfill
$\mathcal{M}$ irreducible $\rightarrow$ $\mathbf{T}^\star\gg 0$ (provided $\mathbf{b}>\mathbf{0}$, of course)
\end{frame}


\begin{frame}{Behaviour of total population}
\framesubtitle{Equal reducible movement case}
\begin{theorem}
Assume $\mathcal{M}$ reducible. Let $a$ be the number of minimal absorbing sets in the corresponding connection graph $\mathcal{G}(\mathcal{M})$. Then
\begin{enumerate}
	\item The spectral abscissa $s(\mathcal{M})=0$ has multiplicity $a$
	\item Associated to $s(\mathcal{M})$ is a nonnegative eigenvector $\mathbf{v}$ s.t.
	\begin{itemize}
		\item $v_i>0$ if $i$ is a vertex in a minimal absorbing set
		\item $v_i=0$ if $i$ is a transient vertex
	\end{itemize}
\end{enumerate}
\end{theorem}

\vfill
From Foster and Jacquez, \href{https://doi.org/10.1016/0025-5564(75)90096-6}{Multiple zeros for eigenvalues and the multiplicity of traps of a linear compartmental system}, \emph{Mathematical Biosciences} (1975)
\end{frame}


\begin{frame}{The not-so-nice case}
Recall that
$$
\bT'=\mathbf{b}-\bd\bT+\sum_{c\in\C}\mathcal{M}_c\bN_{c}
$$

Suppose movement rates \textbf{similar for all compartments}, i.e., the zero/nonzero patterns in all matrices are the same but not the entries

Let
$$
\underline{\mathcal{M}}=\left[\min_{X\in\{S,L,I,R\}}m_{Xpq}\right]_{pq,p\neq q}\qquad 
\underline{\mathcal{M}}=\left[\max_{X\in\{S,L,I,R\}}m_{Xpq}\right]_{pq,p=q}
$$
and
$$
\overline{\mathcal{M}}=\left[\max_{X\in\{S,L,I,R\}}m_{Xpq}\right]_{pq,p\neq q}\qquad
\overline{\mathcal{M}}=\left[\min_{X\in\{S,L,I,R\}}m_{Xpq}\right]_{pq,p=q}
$$
\end{frame}


\begin{frame}{Cool, no? No!}
Then we have
$$
\mathbf{b}-\bd\mathbf{T}+\underline{\mathcal{M}}\mathbf{T}\leq\mathbf{T}'\leq\mathbf{b}-\bd\mathbf{T}+\overline{\mathcal{M}}\mathbf{T}
$$
\vfill
Me, roughly every 6 months: \emph{Oooh, coooool, a linear differential inclusion!}
\vfill
Me, roughly 10 minutes after that previous statement: \emph{Quel con!} 
\vfill
Indeed $\underline{\mathcal{M}}$ and $\overline{\mathcal{M}}$ are \textbf{are not} movement matrices  (in particular, their column sums are not all zero)
\vfill
So no luck there.. 
\vfill
However, we can still do stuff, but more on a case-by-case basis
\end{frame}






%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
\subsection{The models considered}


\frame{\frametitle{The toy SLIRS model in patches}
\begin{center}
	\begin{tikzpicture}[scale=1, every node/.style={transform shape},
		auto, %node distance = 2cm, auto,
		box/.style={minimum width={width("N-1")+2pt},
			draw, rectangle,fill=gray!20}]
		%% States
		\node [box] at (0,2) (S) {$S$};
		\node [box] at (2,2) (L) {$L$};
		\node [box] at (4,2) (I) {$I$};
		\node [box] at (6,2) (R) {$R$};
		%% Flows
		\path [line, thick] (-1.5,2) to node [midway, above] (TextNode) {$B(N)$} (S);
		\path [line, thick] (S) to node [midway, above, sloped] (TextNode) {$\Phi$} (L);
		\path [line, thick] (L) to node [midway, above] (TextNode) {$\varepsilon L$} (I);
		\path [line, thick] (I) to node [sloped, midway, above] (TextNode) {$\gamma I$} (R);
		\draw [>=latex,->, thick, rounded corners] (R) -- +(0,0.75) -- ++(-6,0.75) node[midway, above] {$\nu R$} -- (S);
		\path [line, thick] (S) to node [midway, right] (TextNode) {$dS$} ++(0,-1);
		\path [line, thick] (L) to node [midway, right] (TextNode) {$dL$} ++(0,-1);
		\path [line, thick] (I) to node [midway, right] (TextNode) {$(d+\delta)I$} ++(0,-1);
		\path [line, thick] (R) to node [midway, right] (TextNode) {$dR$} ++(0,-1);
	\end{tikzpicture}
\end{center}
\begin{subequations}\label{sys:SLIRS}
\begin{align}
S' &= \B(N)+\nu R-\Phi-dS \\
L' &= \Phi-(\varepsilon+d)L\\
I' &= \varepsilon L-(\gamma+d+\delta)I\\
R' &= \gamma I-(\nu+d)R
\end{align}
\end{subequations}
$\Phi$ force of infection. Depends on $S,I$, possibly $N$. In general
\[
\Phi=\beta(N)\phi(S,I)
\] 

Mass action, $\Phi=\beta SI$, proportional incidence, $\Phi=\beta SI/N$
}



\frame{\frametitle{$|\mathcal{P}|$-SLIRS model}
\begin{subequations}
	\label{sys:pSLIRS}
	\begin{align}
		S_{p}' &=\mathcal{B}_p\left(N_p\right)+\nu_pR_p-\Phi_p-d_pS_p 
		\color{red}{+\textstyle{\sum_{q\in\mathcal{P}}} m_{Spq}S_{q}} 
		\label{sys:pSLIRS_dS} \\
		L_{p}' &=\Phi_p-\left( \varepsilon_{p}+d_{p}\right)L_{p}
		\color{red}{+\textstyle{\sum_{q\in\mathcal{P}}} m_{Lpq}L_{q}} 
		\label{sys:pSLIRS_dL} \\
		I_{p}' &=\varepsilon_pL_p-(\gamma_p+d_p)I_p
		\color{red}{+\textstyle{\sum_{q\in\mathcal{P}}} m_{Ipq}I_{q}} 
		\label{sys:pSLIRS_dI} \\
		R_{p}' &=\gamma _{p}I_{p}-\left(\nu_{p}+d_{p}\right)R_{p}
		\color{red}{+\textstyle{\sum_{q\in\mathcal{P}}} m_{Rpq}R_{q}} 
		\label{sys:pSLIRS_dR} 
	\end{align}
	with incidence 
	\begin{equation}
		\Phi_p=\beta_p\frac{S_pI_p}{N_p^{q_p}},\qquad q_p\in\{0,1\}
		\label{sys:pSLIRS_incidence} 
	\end{equation}
\end{subequations}	
}

\begin{frame}
\frametitle{$|\S|\;|\P|$-SLIRS (multiple species)}
$p\in\P$ and $s\in\mathcal{S}$ (a set of species)
\vfill
\begin{subequations}
	\label{sys:spSLIRS}
	\begin{align}
		S_{sp}' &= \mathcal{B}_{sp}(N_{sp})+\nu_{sp}R_{sp}-\Phi_{sp}-d_{sp}S_{sp}
		\color{red}{+\textstyle{\sum_{q\in\mathcal{P}}} m_{Sspq}S_{sq}} 
		\label{sys:spSLIRS_dS} \\
		L_{sp}' &= \Phi_{sp}-(\varepsilon_{sp}+d_{sp})L_{sp}
		\color{red}{+\textstyle{\sum_{q\in\mathcal{P}}}m_{Lspq}L_{sq}}
		\label{sys:spSLIRS_dL} \\
		I_{sp}' &= \varepsilon_{sp}L_{sp}-(\gamma_{sp}+d_{sp})I_{sp}
		\color{red}{+\textstyle{\sum_{q\in\mathcal{P}}} m_{Ispq}I_{sq}}
		\label{sys:spSLIRS_dI} \\
		R_{sp} &= \gamma _{sp}I_{sp}-(\nu_{sp}+d_{sp})R_{sp}
		\color{red}{+\textstyle{\sum_{q\in\mathcal{P}}} m_{Rspq}R_{sq}} 
		\label{sys:spSLIRS_dR} 
	\end{align}
	with incidence
	\begin{equation}
	\Phi_{sp}=\sum_{k\in\mathcal{S}}\beta_{skp}\frac{S_{sp}I_{kp}}{N_p^{q_p}},\qquad q_p\in\{0,1\}
	\label{sys:spSLIRS_incidence} 
	\end{equation}
\end{subequations}
\vfill
{\tiny
\begin{itemize}
\setlength{\itemsep}{-5pt}
\item JA, Davis, Hartley, Jordan, Miller \& PvdD. \href{https://julien-arino.github.io/assets/pdf/papers/2005_ArinoDavisHartleyJordanMillerPvdD-MMB22.pdf}{A multi-species epidemic model with spatial dynamics}. \emph{Mathematical Medicine and Biology} \textbf{22}(2):129-142 (2005)\newline 
\item JA, Jordan \& PvdD. \href{https://julien-arino.github.io/assets/pdf/papers/2007_ArinoJordanPvdD-MBS206.pdf}{Quarantine in a multi-species epidemic model with spatial dynamics}. \emph{Mathematical Biosciences} \textbf{206}(1):46-60 (2007)
\end{itemize}}
\end{frame}

\frame{
\frametitle{$|\P|^2$-SLIRS (residents-travellers)}
\begin{subequations}
	\label{sys:ppSLIRS}
	\begin{align}
		S_{pq}' =& 
		\mathcal{B}_{pq}\left(N_p^r\right)+\nu_{pq} R_{pq}-\Phi_{pq}-d_{pq}S_{pq} \color{red}{+\textstyle{\sum_{k\in\mathcal{P}}} m_{Spqk}S_{pk}} 
		\label{sys:ppSLIRS_dS} \\
		L_{pq}' =& \Phi_{pq}
		-(\varepsilon_{pq}+d_{pq})L_{pq}
		\color{red}{+\textstyle{\sum_{k\in\mathcal{P}}} m_{Lpqk}L_{pk}} 
		\label{sys:ppSLIRS_dL} \\
		I_{pq}' =& \varepsilon_{pq} L_{pq}
		-(\gamma_{pq}+d_{pq})I_{pq}
		\color{red}{+\textstyle{\sum_{k\in\mathcal{P}}} m_{Ipqk}I_{pk}} 
		\label{sys:ppSLIRS_dI} \\
		R_{pq}' =& \gamma_{pq} I_{pq}
		-(\nu_{pq}+d_{pq})R_{pq}
		\color{red}{+\textstyle{\sum_{k\in\mathcal{P}}} m_{Rpqk}R_{pk}}
		\label{sys:ppSLIRS_dR} 
	\end{align}
	with incidence
	\begin{equation}
		\Phi_{pq}=\sum_{k\in\mathcal{P}}\beta_{pqk}\frac{S_{pq}I_{kq}}{N_p^{q_q}},\qquad q_q=\{0,1\}
		\label{sys:ppSLIRS_incidence} 
	\end{equation}
\end{subequations}

\vfill
{\tiny
\begin{itemize}
%\setlength{\itemsep}{-5pt}
\item Sattenspiel \& Dietz. \href{https://doi.org/10.1016/0025-5564(94)00068-B}{A structured epidemic model incorporating geographic mobility among regions} (1995)
\item JA \& PvdD. \href{https://julien-arino.github.io/assets/pdf/papers/2003_ArinoPvdD-MPS10_correct.pdf}{A multi-city epidemic model}. \emph{Mathematical Population Studies} \textbf{10}(3):175-193 (2003)
\item JA \& PvdD. \href{https://julien-arino.github.io/assets/pdf/papers/2003_ArinoPvdD-LNCIS294.pdf}{The basic reproduction number in a multi-city compartmental epidemic model}. In \emph{Positive Systems} (2003)
\end{itemize}}
}


\frame{\frametitle{Steps for an analysis}
\textbf{Basic steps}
\begin{enumerate}
\item Well-posedness of the system
\item Existence of disease free equilibria (DFE)
\item Computation of a reproduction number $\R_0$, study local asymptotic stability of DFE
\item If DFE unique, prove global asymptotic stability when $\R_0<1$
\end{enumerate}
\textbf{Additional steps}
\begin{enumerate}\setcounter{enumi}{4}
\item Existence of \emph{mixed} equilibria, with some locations at DFE and others with disease
\item Computation of some bounds on $\R_0$
\item EEP and its LAS \& GAS properties
\end{enumerate}
$\ldots$
}

\begin{frame}{Analysis -- Toy system}
For simplicity, consider $|\mathcal{P}|$-SLIRS with $\mathcal{B}_p(N_p)=\mathcal{B}_p$
\begin{subequations}
	\label{sys:pSLIRS_toy}
	\begin{align}
		S_{p}' &=\mathcal{B}_p-\Phi_p-d_pS_p+\nu_pR_p
		+\textstyle{\sum_{q\in\mathcal{P}}} m_{Spq}S_{q} 
		\label{sys:pSLIRS_toy_dS} \\
		L_{p}' &=\Phi_p-\left( \varepsilon_{p}+d_{p}\right)L_{p}
		+\textstyle{\sum_{q\in\mathcal{P}}} m_{Lpq}L_{q} 
		\label{sys:pSLIRS_toy_dL} \\
		I_{p}' &=\varepsilon_pL_p-(\gamma_p+d_p)I_p
		+\textstyle{\sum_{q\in\mathcal{P}}} m_{Ipq}I_{q} 
		\label{sys:pSLIRS_toy_dI} \\
		R_{p}' &=\gamma _{p}I_{p}-\left(\nu_{p}+d_{p}\right)R_{p}
		+\textstyle{\sum_{q\in\mathcal{P}}} m_{Rpq}R_{q}
		\label{sys:pSLIRS_toy_dR} 
	\end{align}
	with incidence
	\begin{equation}
		\Phi_p=\beta_p\frac{S_pI_p}{N_p^{q_p}},\qquad q_p\in\{0,1\}
		\label{sys:pSLIRS_toy_incidence} 
	\end{equation}			
\end{subequations}
\vfill
System of $4|\mathcal{P}|$ equations
\end{frame}

\begin{frame}{Don't panic: size is not that bad..}
System of $4|\mathcal{P}|$ equations !!!
\vfill
However, a lot of structure: 
\begin{itemize}
	\item $|\mathcal{P}|$ \emph{copies} of individual units, each comprising 4 equations
	\item Dynamics of individual units well understood
	\item Coupling is linear
\end{itemize}
\vfill
$\implies$ Good case of large-scale system
\vfill
(matrix analysis is your friend)

\end{frame}


% %%%%%%%%%%%%%%%%%%%
% %%%%%%%%%%%%%%%%%%%
% %%%%%%%%%%%%%%%%%%%
% %%%%%%%%%%%%%%%%%%%
% %%%%%%%%%%%%%%%%%%%
% %%%%%%%%%%%%%%%%%%%
% \subsection{Well-posedness}

\frame{\frametitle{Existence and uniqueness}
\begin{itemize}
\item
Existence and uniqueness of solutions classic, assured by good choice of birth and force of infection functions
\vfill
\item
In the cases treated later, the birth function is either constant or a linear combination of state variables
\vfill
\item May exist problems at the origin, if the force of infection is not defined there
\vfill
\item
Assumption form now on: existence and uniqueness
\end{itemize}
}

\begin{frame}{Other basic stuff}
	Skipped until I homogeneise notation
	\vfill
	Not complicated but sometimes tedious
	\vfill
	Easy if it has been proved for the constituting units
\end{frame}


% \frame{\frametitle{Nonnegativity of solutions}
% Sufficient to show that each of the faces of the positive orthant (cone) cannot be crossed, that is, that the vector field points inward on these faces. 

% Take \eqref{sys:pSEIRS}. Assume that initially all variables are nonnegative. 

% Setting $S_i=0$ in \eqref{sys:pSEIRS_Si} gives
% \[
% \frac{d}{dt}S_i = \B_i(N_i)+\nu_iR_i+\sum_{j=1}^{|\P|}m_{ij}^S S_j\geq 0,
% \]
% implying that $S_i=0$ cannot be crossed from positive to negative $S_i$. Similarly, setting $E_i=0$ in \eqref{sys:pSEIRS_Ei} gives
% \[
% \frac{d}{dt}E_i = \Phi_i +\sum_{j=1}^{|\P|}m_{ij}^E E_j\geq 0,
% \]
% and $E_i=0$ cannot be crossed. The same argument shows that neither $I_i$ nor $R_i$ can be crossed. Hence solutions remain nonnegative for nonnegative initial conditions.
% }

% \frame{\frametitle{Positivity of solutions}
% Assume that initial conditions are such that $S_\bullet(0)>0$ and $E_\bullet(0),I_\bullet(0),R_\bullet(0)\geq 0$, with $\sum_{\bullet}E_\bullet(0)+I_\bullet(0)>0$ (so that there are exposed and/or infectives at initial time). This implies that $S_\bullet>0$ for all times.

% \begin{theorem}\label{th:Spositive}
% Generically, if a given movement rate $m_\bullet>0$, the linked $S_\bullet>0$.
% \end{theorem}
% }


% # Behaviour of the total population

% Consider behaviour of $N_p=S_p+L_p+I_p+R_p$. We have
% $$
% \begin{aligned}
% N_p' &=\mathcal{B}_p\cancel{-\Phi_p}-d_pS_p\cancel{+\nu_pR_p}
% +\textstyle{\sum_{q\in\mathcal{P}}} m_{Spq}S_{q} \\
% &\quad \cancel{+\Phi_p}-\left(\cancel{\varepsilon_{p}}
% +d_{p}\right)L_{p}
% +\textstyle{\sum_{q\in\mathcal{P}}} m_{Lpq}L_{q} \\
% &\quad \cancel{+\varepsilon_pL_p}-(\cancel{\gamma_p}+d_p)I_p
% +\textstyle{\sum_{q\in\mathcal{P}}} m_{Ipq}I_{q} \\
% &\quad \cancel{+\gamma _{p}I_{p}}
% -\left(\cancel{\nu_{p}}+d_{p}\right)R_{p}
% +\textstyle{\sum_{q\in\mathcal{P}}} m_{Rpq}R_{q}
% \end{aligned}
% $$


% \frame{\frametitle{Boundedness of solutions -- Identical movement rates for all epidemiological states}
% Consider system \eqref{sys:pSEIRS}. Assume $\delta_i=0$ and $M^{S}=M^{E}=M^{I}=M^{R}=:M=[m_{ij}]$. 
% Total population $N_i$ in location $i$:
% \begin{equation}\label{eq:N_pSEIRS}
% \frac{d}{dt}N_i=\B_i(N_i)-d_iN_i-\delta_i I_i+\sum_{j=1}^{|\P|}m_{ij}N_j -\sum_{j=1}^{|\P|}m_{ji}N_i.
% \end{equation}
% Total population in all locations $\nbOne^TN=N_{1}+N_{2}+\ldots +N_{|\P|}$:
% \begin{equation}
% \dfrac{d}{dt}\nbOne^TN=\dsum\limits_{i=1}^{|\P|}(\B_{i}\left( N_{i}\right)-d_{i}N_{i} 
% -\delta_{i}I_{i}).  \label{eq:dNdt}
% \end{equation}
% If $\B_i(N_i)$ has ``good" properties, $\nbOne^TN(t)$ is bounded.
% }

% \frame{
% \begin{theorem}\label{th:behaviorN_nSEIRS}
% Suppose that in system \eqref{sys:pSEIRS}, movement is identical for all epidemiological states, that the disease is not lethal ($\delta_i=0$), and that in each location, birth compensates natural death, that is, $\B_i(N_i)=d_iN_i$. Then for every location $i=1,\ldots,|\P|$, there holds
% \[
% \lim_{t\to\infty}N_i(t)=N_i^*>0.
% \]
% \end{theorem}
% }

% \frame{\frametitle{Proof}
% Under theorem assumptions, system is linear and decouples from the epidemic variables. For $i=1,\ldots,|\P|$,
% \[
% \dfrac{d}{dt}N_{i}=\dsum\limits_{j=1}^{|\P|}m_{ij}N_{j}-\dsum\limits_{j=1}^{|\P|}m_{ji}^{{}}N_{i}  
% \]
% or
% \[
% \frac{d}{dt}
% \begin{pmatrix}
% N_1 \\
% N_2 \\
% \vdots \\
% N_{|\P|}
% \end{pmatrix}=
% \begin{pmatrix}
% -\sum_{j=1}^{|\P|}m_{j1} & m_{12} & m_{13} & \cdots & m_{1|\P|} \\
% m_{21} & -\sum_{j=1}^{|\P|}m_{j1} & m_{23} & \cdots & m_{2|\P|} \\
% \vdots &\vdots &\vdots& & \vdots \\
% m_{|\P|1} & m_{|\P|2} & m_{|\P|3} & \cdots 
% & -\sum_{j=1}^{|\P|}m_{j|\P|}
% \end{pmatrix}
% \begin{pmatrix}
% N_1 \\
% N_2 \\
% \vdots \\
% N_{|\P|}
% \end{pmatrix}.
% \]
% The result then follows from Theorem~\ref{th:GAS_metapop1}.
% }

% \frame{
% \begin{theorem}\label{th:behaviorN_spSEIRS}
% Suppose that, in system \eqref{sys:spSEIRS}, movement is identical for all epidemiological states, that the disease is not lethal ($\delta_{sp}=0$), and that in each location, birth compensates natural death, that is, $\B_{sp}(N_{sp})=d_{sp}N_{sp}$. Then the movement model is given, for all $s=1,\ldots,|\C|$ and all $p=1,\ldots,|\P|$, by
% \begin{equation}\label{eq:Nsp_spSEIRS}
% \frac{d}{dt}N_{sp}=\sum_{q=1}^{|\P|}m_{spq}N_{sq}-\sum_{q=1}^{|\P|}m_{sqp}N_{sp},
% \end{equation}
% and there holds
% \[
% \lim_{t\to\infty}N_{sp}(t)=N_{sp}^*>0.
% \]
% \end{theorem}
% }

% \frame{
% \begin{theorem}\label{th:behaviorN_ppSEIRS}
% Suppose that, in system \eqref{sys:ppSEIRS}, movement is identical for all epidemiological states, that the disease is not lethal ($\delta_{sp}=0$), and that in each location, birth compensates natural death, that is, 
% \[
% \B_{ij}(N_i^r)=\left\{
% \begin{array}{ll}
% d_{ij}\sum_{k=1}^{|\P|}N_{ik} & \textrm{if } i=j, \\
% 0 & \textrm{if } i\neq j.
% \end{array}
% \right.
% \] 
% Then for every location $i,j=1,\ldots,|\P|$, there holds
% \[
% \lim_{t\to\infty}N_{ij}(t)=N_{ij}^*>0.
% \]
% \end{theorem}
% }

% \frame{
% In the case of system \eqref{sys:ppSEIRS}, boundedness can be obtained with more general birth functions.
% The variation of the number $N_i^r$ of residents in location $i$ is
% given by
% \begin{eqnarray}
% \frac{d}{dt}N^r_i&=& \frac{d}{dt}\sum_{j=1}^{|\P|} N_{ij}
% = \frac{d}{dt}N_{ii}+ \sum\dind{j=1}{j\neq i}^{|\P|}
% \frac{d}{dt}N_{ij} \nonumber\\
% &=& \B_{ii}(N_i^r)+\sum_{k=1}^{|\P|} m_{iik}N_{ik}
% -(d+\sum_{k=1}^n m_{iki})N_{ii} \nonumber \\
% &&+\sum\dind{j=1}{j\neq i}^{|\P|}\left[ \sum_{k=1}^{|\P|} m_{ijk}N_{ik}
% -(d_i+\sum_{k=1}^{|\P|} m_{ikj})N_{ij}
% \right] \nonumber\\
% &=& \B_{ii}(N_i^r) +\sum_{j=1}^{|\P|}\left[ \sum_{k=1}^{|\P|}
% m_{ijk}N_{ik} -(d_i+\sum_{k=1}^{|\P|} m_{ikj})N_{ij} \right]
%  \nonumber \\
%  &=& \B_{ii}(N_i^r)-d_iN_i^r \nonumber
% \end{eqnarray}
% }

% \frame{
% Therefore the resident population of each location either decreases or
% increases, depending on the value of
% \[
% \B_{ii}(N_i^r)-d_iN_i^r=A_i+(b_i-d_i)N^r_{i}.
% \]
% To ensure that the population remains bounded, we thus make the
% following hypotheses on the birth function. We suppose that for each
% location $i$ one of the following two conditions holds:
% \begin{enumerate}
% \item[\textbf{ H1}] $A_i>0$, $d_i>b_i$.
% \item[\textbf{ H2}] $A_i=0$, $d_i=b_i$.
% \end{enumerate}
% If \textbf{ H1} holds, then the
% population in location $i$ is bounded above by
% $\max\{A_i/(d_i-b_i),N^r_i(0)\}$. 

% If \textbf{ H2} holds, then the
% resident population of location $i$ is constant with $N^r_i=N^r_i(0)$,
% and if this is true for all locations, then the total population in
% the system is constant.
% }

% \frame{
% \frametitle{Different (but similar) movement rates in different epidemiological states}
% Consider system \eqref{sys:spSEIRS}.

% Total population $N_{sp}$ in location $p$ for species $s$:
% \begin{equation}\label{eq:dNdt_spSEIRS_statusdep}
% \frac{d}{dt}N_{sp}=\B_{sp}(N_{sp})-d_{sp}N_{sp}-\delta_{sp}I_{sp}+\sum_{X\in\{S,E,I,R\}}\left(\sum_{q=1}^{|\P|}m_{spq}^XX_{sq}-\sum_{q=1}^{|\P|}m_{sqp}^XX_{sp}\right)
% \end{equation}
% Cannot be evaluated independently of the dynamics of \eqref{sys:spSEIRS}.

% Let
% \[
% \underline{m}_{spq}=\min_{X\in\{S,E,I,R\}}\{m_{spq}^X\},\qquad
% \overline{m}_{spq}=\max_{X\in\{S,E,I,R\}}\{m_{spq}^X\}.
% \]
% }

% \frame{
% Equation \eqref{eq:dNdt_spSEIRS_statusdep} can then be bounded above
% \[
% \frac{d}{dt}N_{sp} \leq \B_{sp}(N_{sp})-d_{sp}N_{sp}+\sum_{q=1}^{|\P|}\overline{m}_{spq}N_{sq}-\sum_{q=1}^{|\P|}\underline{m}_{sqp}N_{sp}.
% \]
% If birth and death compensate, as before, then the total population is bounded.
% }

%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
\subsection{Existence of a DFE}

\frame{\frametitle{Disease free equilibrium}
The model is at equilibrium if the time derivatives are zero
\vfill
\begin{definition}[Metapopulation DFE]
In the case of system \eqref{sys:pSLIRS_toy}, location $p\in\P$ is at a disease-free equilibrium (DFE) if $L_{p}=I_{p}=0$, and the $|\P|$-location model is at a \textbf{metapopulation DFE} if $L_{p}=I_{p}=0$ for all $p\in\P$
\end{definition}
\vfill
Here, we want to find the DFE for the $|\P|$-location model. Later, the existence of mixed equilibria, with some locations at the DFE and others at an endemic equilibrium, is considered
\vfill
(For \eqref{sys:spSLIRS}, replace $L_p$ with $L_{sp}$ and $I_p$ with $I_{sp}$, for \eqref{sys:ppSLIRS}, replace $L_p$ by $L_{pp}$ and $I_p$ by $I_{pp}$. To simplify notation, we could write $L_{\bullet}$ and $I_{\bullet}$)
}

\begin{frame}{}
Assume \eqref{sys:pSLIRS_toy} at metapopulation DFE. Then $\Phi_p=0$ and 
\begin{align*}
0 &=\mathcal{B}_p-d_pS_p+\nu_pR_p
+\textstyle{\sum_{q\in\mathcal{P}}} m_{Spq}S_{q} \\
0 &=-\left(\nu_{p}+d_{p}\right)R_{p}
+\textstyle{\sum_{q\in\mathcal{P}}} m_{Rpq}R_{q}
\end{align*}
Want to solve for $S_p,R_p$. Here, it is best (crucial in fact) to remember some linear algebra. Write system in vector form:
\begin{align*}
\mathbf{0} &=\mathbf{b}-\bd\mathbf{S}+\mathbf{\nu}\bR+\mathcal{M}^S\mathbf{S} \\
\mathbf{0} &=-\left(\mathbf{\nu}+\bd\right)\bR+\mathcal{M}^R\bR
\end{align*}
where $\mathbf{S},\bR,\mathbf{b}\in\mathbb{R}^{|\mathcal{P}|}$, $\bd,\mathbf{\nu},\mathcal{M}^S,\mathcal{M}^R$ $|\mathcal{P}|\times|\mathcal{P}|$-matrices ($\bd,\mathbf{\nu}$ diagonal)
\end{frame}

\begin{frame}{$\bR$ at DFE}
Recall second equation:
$$
\mathbf{0} =-\left(\mathbf{\nu}+\bd\right)\bR+\mathcal{M}^R\bR \Leftrightarrow (\mathcal{M}^R-\mathbf{\nu}-\bd)\bR=\mathbf{0}
$$
\vfill
So unique solution $\bR=\mathbf{0}$ if $\mathcal{M}^R-\mathbf{\nu}-\bd$ invertible
Is it?
\vfill
We have been here before! 
\vfill
From spectrum shift, $s(\mathcal{M}^R-\mathbf{\nu}-\bd)=-\min_{p\in\mathcal{P}}(\nu_p+d_p)<0$
\vfill
So, given $\mathbf{L}=\mathbf{I}=\mathbf{0}$, $\bR=\mathbf{0}$ is the unique equilibrium and
$$
\lim_{t\to\infty}\bR(t)=\mathbf{0}
$$
\vfill
$\implies$ DFE has $\mathbf{L}=\mathbf{I}=\bR=\mathbf{0}$
\end{frame}


\begin{frame}{$\mathbf{S}$ at the DFE}
DFE has $\mathbf{L}=\mathbf{I}=\bR=\mathbf{0}$ and $\mathbf{b}-\bd\mathbf{S}+\mathcal{M}^S\mathbf{S}=\mathbf{0}$, i.e.,
$$
\mathbf{S}=(\bd-\mathcal{M}^S)^{-1}\mathbf{b}
$$
\vfill
Recall: $-\mathcal{M}^S$ singular M-matrix. From previous reasoning, $\bd-\mathcal{M}^S$ has \textbf{instability modulus} shifted \emph{right} by $\min_{p\in\mathcal{P}}d_p$. So:
\begin{itemize}
\item $\bd-\mathcal{M}^S$ invertible
\item $\bd-\mathcal{M}^S$ nonsingular M-matrix
\end{itemize}
\vfill
Second point $\implies (\bd-\mathcal{M}^S)^{-1}>\mathbf{0}\implies (\bd-\mathcal{M}^S)^{-1}\mathbf{b}> \mathbf{0}$  (would have $\gg\mathbf{0}$ if $\mathcal{M}^S$ irreducible)
\vfill
So DFE makes sense with
$$
(\mathbf{S},\mathbf{L},\mathbf{I},\bR)=\left((\bd-\mathcal{M}^S)^{-1}\mathbf{b},\mathbf{0},\mathbf{0},\mathbf{0}\right)
$$
\end{frame}

%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
\subsection{Computation of a reproduction number}

\frame{
\begin{itemize}
\item
Linear stability of the disease free equilibrium can be investigated by using the next generation matrix
\vfill
\item
In general, $\R_0$ depends on the demographic, disease and mobility parameters
\end{itemize}
}

\begin{frame}{Computing the basic reproduction number $\R_0$}
Use next generation method with $\Xi=\{L_1,\ldots,L_{|\mathcal{P}|},I_1,\ldots,I_{|\mathcal{P}|}\}$, $\Xi'=\mathcal{F}-\mathcal{V}$
$$
\mathcal{F}=\left(\Phi_1,\ldots,\Phi_{|\mathcal{P}|},0,\ldots,0\right)^T
$$
$$
\mathcal{V}=
\begin{pmatrix}
\left( \varepsilon_{1}+d_{1}\right)L_{1}
-\sum\limits_{q\in\mathcal{P}} m_{L1q}L_{q} \\
\vdots \\
\left( \varepsilon_{|\mathcal{P}|}+d_{|\mathcal{P}|}\right)L_{|\mathcal{P}|}
-\sum\limits_{q\in\mathcal{P}} m_{L|\mathcal{P}|q}L_{q} \\
-\varepsilon_1L_1+(\gamma_1+d_1)I_1
-\sum\limits_{q\in\mathcal{P}} m_{I1q}I_{q} \\
\vdots \\
-\varepsilon_{|\mathcal{P}|}L_{|\mathcal{P}|}
+(\gamma_{|\mathcal{P}|}+d_{|\mathcal{P}|})I_{|\mathcal{P}|}
-\sum\limits_{q\in\mathcal{P}} m_{I|\mathcal{P}|q}I_{q}
\end{pmatrix}
$$
\end{frame}


\begin{frame}
Differentiate w.r.t. $\Xi$:
$$
D\mathcal{F}
=
\begin{pmatrix}
\dfrac{\partial\Phi_1}{\partial L_1} & \cdots &
\dfrac{\partial\Phi_1}{\partial L_{|\mathcal{P}|}} & 
\dfrac{\partial\Phi_1}{\partial I_1} & \cdots &
\dfrac{\partial\Phi_1}{\partial I_{|\mathcal{P}|}} \\
\vdots & & \vdots & \vdots & & \vdots \\
\dfrac{\partial\Phi_{|\mathcal{P}|}}{\partial L_1} & \cdots &
\dfrac{\partial\Phi_{|\mathcal{P}|}}{\partial L_{|\mathcal{P}|}} & 
\dfrac{\partial\Phi_{|\mathcal{P}|}}{\partial I_1} & \cdots &
\dfrac{\partial\Phi_{|\mathcal{P}|}}{\partial I_{|\mathcal{P}|}} \\
0 & \cdots & 0 & 0 & \cdots & 0 \\
\vdots & & \vdots & \vdots & & \vdots \\
0 & \cdots & 0 & 0 & \cdots & 0
\end{pmatrix}
$$
\end{frame}

\begin{frame}
Note that
$$
\frac{\partial\Phi_p}{\partial L_k}=\frac{\partial\Phi_p}{\partial I_k}=0
$$
whenever $k\neq p$, so
$$
D\mathcal{F}
=
\begin{pmatrix}
\mathsf{diag}\left(
\frac{\partial\Phi_1}{\partial L_1},\ldots,\frac{\partial\Phi_{|\mathcal{P}|}}{\partial L_{|\mathcal{P}|}}\right) &
\mathsf{diag}\left(
\frac{\partial\Phi_1}{\partial I_1},\ldots,\frac{\partial\Phi_{|\mathcal{P}|}}{\partial I_{|\mathcal{P}|}}\right) \\
\mathbf{0} & \mathbf{0} 
\end{pmatrix}
$$
\end{frame}

\begin{frame}{Evaluate $D\mathcal{F}$ at DFE}
	\begin{minipage}[t]{0.45\textwidth}
		If $\Phi_p=\beta_pS_pI_p$, then
		\begin{itemize}
			\item $\dfrac{\partial\Phi_p}{\partial L_p}=0$
			\item $\dfrac{\partial\Phi_p}{\partial I_p}=\beta_pS_p$
		\end{itemize}
	\end{minipage}
	\begin{minipage}[t]{0.45\textwidth}
		If $\Phi_p=\beta_p\dfrac{S_pI_p}{N_p}$, then
		\begin{itemize}
			\item $\dfrac{\partial\Phi_p}{\partial L_p}=\beta_p\dfrac{S_pI_p}{N_p^2}=0$ at DFE
			\item $\dfrac{\partial\Phi_p}{\partial I_p}=\beta_p\dfrac{S_p}{N_p}$ at DFE
		\end{itemize}
	\end{minipage}
	\vfill
In both cases, $\partial/\partial L$ block is zero so
$$
F=D\mathcal{F}(DFE)=
\begin{pmatrix}
\mathbf{0} & \mathsf{diag}\left(
\frac{\partial\Phi_1}{\partial I_1},\ldots,\frac{\partial\Phi_{|\mathcal{P}|}}{\partial I_{|\mathcal{P}|}}\right) \\
\mathbf{0} & \mathbf{0}
\end{pmatrix}
$$
\end{frame}

\begin{frame}{Compute $D\mathcal{V}$ and evaluate at DFE}
$$
V=
\begin{pmatrix}
\mathsf{diag}_p(\varepsilon_p+d_p)-\mathcal{M}^L & \mathbf{0} \\
-\mathsf{diag}_p(\varepsilon_p) & \mathsf{diag}_p(\gamma_p+d_p)-\mathcal{M}^I
\end{pmatrix}
$$
where $\mathsf{diag}_p(z_p):=\mathsf{diag}(z_1,\ldots,z_{|\mathcal{P}|})$
\vfill
Inverse of $V$ easy ($2\times 2$ block lower triangular):
$$
V^{-1}
=
\begin{pmatrix}
\left(\mathsf{diag}_p(\varepsilon_p+d_p)-\mathcal{M}^L\right)^{-1} & \mathbf{0} \\
\tilde V_{21}^{-1} & \left(\mathsf{diag}_p(\gamma_p+d_p)-\mathcal{M}^I\right)^{-1}
\end{pmatrix}
$$
where
\begin{multline*}
	\tilde V_{21}^{-1}=
	\left(\mathsf{diag}_p(\varepsilon_p+d_p)-\mathcal{M}^L\right)^{-1}\\ 
	\mathsf{diag}_p(\varepsilon_p)
	\left(\mathsf{diag}_p(\gamma_p+d_p)-\mathcal{M}^I\right)^{-1}		
\end{multline*}
\end{frame}

\begin{frame}{$\R_0$ as $\rho(FV^{-1})$}
Next generation matrix
$$
FV^{-1}=
\begin{pmatrix}
\mathbf{0} & F_{12} \\
\mathbf{0} & \mathbf{0}
\end{pmatrix}
\begin{pmatrix}
\tilde V_{11}^{-1} & \mathbf{0} \\
\tilde V_{21}^{-1} & \tilde V_{22}^{-1}
\end{pmatrix}
=
\begin{pmatrix}
F_{12}\tilde V_{21}^{-1} & F_{12}\tilde V_{22}^{-1} \\
\mathbf{0} & \mathbf{0}
\end{pmatrix}
$$
where $\tilde V_{ij}^{-1}$ is block $ij$ in $V^{-1}$. So
$$
\R_0=\rho\left(F_{12}\tilde{V}_{21}^{-1}\right)
$$
i.e.,
\begin{multline*}
	\R_0=\rho\Biggl(
		\mathsf{diag}\left(
		\frac{\partial\Phi_1}{\partial I_1},\ldots,\frac{\partial\Phi_{|\mathcal{P}|}}{\partial I_{|\mathcal{P}|}}\right)
		\left(\mathsf{diag}_p(\varepsilon_p+d_p)-\mathcal{M}^L\right)^{-1} \\ 
		\mathsf{diag}_p(\varepsilon_p)
		\left(\mathsf{diag}_p(\gamma_p+d_p)-\mathcal{M}^I\right)^{-1}
		\Biggr)			
\end{multline*}
\end{frame}

\begin{frame}{Local asymptotic stability of the DFE}
\begin{theorem}\label{th:LAS_DFE_pSLIRS_toy}
	Define $\R_0$ for the $|\mathcal{P}|$-SLIRS as 
	\begin{multline*}
		\R_0=\rho\Biggl(
			\mathsf{diag}\left(
			\frac{\partial\Phi_1}{\partial I_1},\ldots,\frac{\partial\Phi_{|\mathcal{P}|}}{\partial I_{|\mathcal{P}|}}\right)
			\left(\mathsf{diag}_p(\varepsilon_p+d_p)-\mathcal{M}^L\right)^{-1}  \\
			\mathsf{diag}_p(\varepsilon_p)
			\left(\mathsf{diag}_p(\gamma_p+d_p)-\mathcal{M}^I\right)^{-1}
			\Biggr)				
	\end{multline*}
	Then the DFE
	$$
	(\mathbf{S},\mathbf{L},\mathbf{I},\mathbf{R})=\left((\mathbf{d}-\mathcal{M}^S)^{-1}\mathbf{b},\mathbf{0},\mathbf{0},\mathbf{0}\right)
	$$
	is locally asymptotically stable if $\R_0<1$ and unstable if $\R_0>1$		
\end{theorem}
\vfill
{\setstretch{0.5}\tiny
From PvdD \& Watmough, \href{https://doi.org/10.1016/S0025-5564(02)00108-6}{Reproduction numbers and sub-threshold endemic equilibria for compartmental models of disease transmission}, \emph{Bulletin of Mathematical Biology} \textbf{180}(1-2): 29-48 (2002)}
\end{frame}

\begin{frame}{Some remarks about $\R_0$}
	The expression for $\R_0$ in Theorem~\ref{th:LAS_DFE_pSLIRS_toy} is exact
	\vfill
	However, unless you consider a very small set of locations, you will not get a closed form expression
	\vfill
	Indeed, by Theorem~\ref{prop:behaviour_Mc}{(3)} and more importantly (often $\M$ is irreducible), Theorem~\ref{prop:behaviour_Mc}{(4)}, the two inverses in $\R_0$ are likely crowded ($\gg 0$ in the irreducible case)
	\vfill
	However, numerically, this works easy unless conditioning is bad
\end{frame}


\begin{frame}{Do not in $\R_0$ put all your .. interpretation?}
\framesubtitle{An urban centre and satellite cities}
Winnipeg as urban centre and 3 smaller satellite cities: Portage la Prairie, Selkirk and Steinbach
\begin{itemize}
	\item population density low to very low outside of Winnipeg
	\item MB road network well studied by MB Infrastructure Traffic Engineering Branch
\end{itemize}
\vfill
JA \& S Portet. \href{https://julien-arino.github.io/assets/pdf/papers/2015_ArinoPortet-JMB71.pdf}{Epidemiological implications of mobility between a large urban centre and smaller satellite cities}. \emph{Journal of Mathematical Biology} \textbf{71}(5):1243-1265 (2015)
\end{frame}

\maxFrameImage{FIGS/MB_highways}

\begin{frame}{Known and estimated quantities}
\begin{center}
	\begin{tabular}{c|c|c|c|c}
		City & Pop. (2014) & Pop. (now) & Dist. & Avg. trips/day \\
		\hline
		Winnipeg (W) & 663,617 & 749,607 & - & - \\
		Portage la Prairie (1) & 12,996 & 13,270 & 88 & 4,115 \\
		Selkirk (2) & 9,834 & 10,504 & 34 & 7,983 \\
		Steinbach (3) & 13,524 & 17,806 & 66 & 7,505
	\end{tabular}
\end{center}
\end{frame}	

\maxFrameImage{FIGS/SIR_flow_diagram_UrbanCentre_Satellite}

\begin{frame}{Estimating movement rates}
	Assume $m_{yx}$ movement rate from city $x$ to city $y$. *Ceteris paribus*, $N_x'=-m_{yx}N_x$, so $N_x(t)=N_x(0)e^{-m_{yx}t}$. Therefore, after one day, $N_x(1)=N_x(0)e^{-m_{yx}}$, i.e.,
	$$
	m_{yx}=-\ln\left(\frac{N_x(1)}{N_x(0)}\right)
	$$
	Now, $N_x(1)=N_x(0)-T_{yx}$, where $T_{yx}$ number of individuals going from $x$ to $y$ / day. So
	$$
	m_{yx}=-\ln\left(1-\frac{T_{yx}}{N_x(0)}\right)
	$$
	Computed for all pairs $(W,i)$ and $(i,W)$ of cities
\end{frame}
	
\begin{frame}{Sensitivity of $\mathcal{R}_0$ to variations of $\mathcal{R}_0^x\in[0.5,3]$}
\begin{center}
	\includegraphics[width=\textwidth]{FIGS/sensitivity_4cities}
\end{center}
\emph{with disease}: $\mathcal{R}_0^x=1.5$; \emph{without disease}: $\mathcal{R}_0^x=0.5$. Each box and corresponding whiskers are 10,000 simulations
\end{frame}

\begin{frame}{Lower connectivity can drive $\mathcal{R}_0$}
	PLP and Steinbach have comparable populations but with parameters used, only PLP can cause the general $\mathcal{R}_0$ to take values larger than 1 when $\mathcal{R}_0^W<1$
	\vfill
	This is due to the movement rate: if $\mathcal{M}=0$, then
	$$
	\mathcal{R}_0=\max\{\mathcal{R}_0^W,\mathcal{R}_0^1,\mathcal{R}_0^2,\mathcal{R}_0^3\},
	$$
	since $FV^{-1}$ is then block diagonal
	\vfill
	Movement rates to and from PLP are lower $\rightarrow$ situation closer to uncoupled case and $\mathcal{R}_0^1$ has more impact on the general $\mathcal{R}_0$
\end{frame}

\begin{frame}{$\mathcal{R}_0$ does not tell the whole story!}
\begin{center}
	\includegraphics[width=0.49\textwidth]{FIGS/invasion_WPG_from_satellites_R01_m_caseR0W05_R0}
	\includegraphics[width=0.49\textwidth]{FIGS/invasion_WPG_from_satellites_R01_m_caseR0W05_attackRate}
\end{center}
\vfill
Plots as functions of $\mathcal{R}_0^1$ in PLP and the reduction of movement between Winnipeg and PLP. Left: general $\mathcal{R}_0$. Right: Attack rate in Winnipeg
\end{frame}

% \frame{\frametitle{General SEIRS}
% System \eqref{sys:pSEIRS} with a generic force of infection.

% Order the infected variables as $E_{1},\ldots ,E_{|\P|},I_{1},\ldots,I_{|\P|}$. 

% Form the vectors
% \[
% \mathcal{F}=
% \begin{pmatrix}
% \Phi_1\\
% \vdots\\
% \Phi_{|\P|}\\
% 0\\
% \vdots\\
% 0
% \end{pmatrix},
% \] 
% representing new infections into the infected classes $E_{1},\ldots ,E_{|\P|},I_{1},\ldots,I_{|\P|}$,
% } 

% \frame{
% \[
% \mathcal{V}=-
% \begin{pmatrix}
% -(\varepsilon_1+d_1)E_1+\sum_{j=1}^{|\P|}m_{1j}^EE_j-\sum_{j=1}^{|\P|}m_{j1}^EE_1 \\
% \vdots\\
% -(\varepsilon_{|\P|}+d_{|\P|})E_{|\P|}+\sum_{j=1}^{|\P|}m_{{|\P|}j}^EE_j-\sum_{j=1}^{|\P|}m_{j{|\P|}}^EE_{|\P|}\\
% \varepsilon_1E_1-(\gamma_1+d_1+\delta_1)I_1+\sum_{j=1}^{|\P|}m_{1j}^II_j-\sum_{j=1}^{|\P|}m_{j1}^II_1\\
% \vdots\\
% \varepsilon_{|\P|}E_{|\P|}-(\gamma_{|\P|}+d_{|\P|}+\delta_{|\P|})I_{|\P|}+\sum_{j=1}^{|\P|}m_{{|\P|}j}^II_j-\sum_{j=1}^{|\P|}m_{j{|\P|}}^II_{|\P|}
% \end{pmatrix},
% \]
% representing other flows within and out off the infected classes $E_{1},\ldots ,E_{|\P|},I_{1},\ldots,I_{|\P|}$ (note that $\mathcal{V}$ has a minus sign).
% }

% \frame{
% \begin{itemize}
% \item
% Matrix of new infections $F$ and matrix of transfer between
% compartments $V$ are Jacobian matrices obtained by differentiating $\mathcal{F}$ and $\mathcal{V}$ with respect to the infected variables, evaluated at the disease free equilibrium (DFE).
% \end{itemize}
% Note that
% \[
% \frac{\partial\Phi_i}{\partial E_i}=\phi_i(S_i,I_i)\frac{\partial\beta_i}{\partial E_i}(N_i),
% \]
% and since $\phi=0$ at the DFE, it follows that $\partial\Phi_i/\partial E_i=0$ at the DFE.
% }

% \frame{
% Therefore, $F$ and $V$ are given in partitioned form by
% \begin{equation}\label{eq:FV_R0_pSEIRS}
% F=
% \begin{bmatrix}
% 0 & F_{12} \\ 
% 0 & 0%
% \end{bmatrix}%
% \text{ and }V=%
% \begin{bmatrix}
% V_{11} & 0 \\ 
% -V_{21} & V_{22}%
% \end{bmatrix}
% \end{equation}
% with
% \[
% F_{12}=\diag\left(\left.\frac{\partial \Phi_i}{\partial I_i}\right|_{DFE}\right),
% \]
% and
% \[
% V_{11}=-M_{{}}^{E}+\diag(\varepsilon
% _{i}+d_{i}+\dsum\limits_{j=1}^{|\P|}m_{ji}^{E})\quad 
% V_{21}=\diag\left( \varepsilon _{i}\right)
% \]
% \[
% V_{22}=-M_{{}}^{I}+\diag(\gamma
% _{i}+d_{i}+\delta_i+\dsum\limits_{j=1}^{|\P|}m_{ji}^{I}).
% \]
% }

% \frame{
% Matrices $V_{11}$ and $V_{22}$ are $|\P|\times|\P|$ irreducible 
% M-matrices and thus have positive inverses. 

% The next generation matrix%
% \begin{equation*}
% FV^{-1}=%
% \begin{bmatrix}
% F_{12}V_{22}^{-1}V_{21}V_{11}^{-1} & F_{12}V_{22}^{-1} \\ 
% 0 & 0%
% \end{bmatrix}%
% \end{equation*}%
% has spectral radius, denoted by $\rho $, given by $\rho \left(
% FV^{-1}\right) =\rho \left( F_{12}V_{22}^{-1}V_{21}V_{11}^{-1}\right)$. 
% }

% \frame{
% Jacobian matrix of the infected compartments at the
% DFE, $F-V$, has all eigenvalues with negative real parts
% if and only if $\rho \left( FV^{-1}\right) <1$. 

% This is summarized in the following theorem.
% \begin{theorem}\label{th:R0_pSEIRS}
% Define the \textit{basic reproduction number} $\R_0$ for system \eqref{sys:pSEIRS} with force of infection \eqref{eq:Phi_nSEIRSgeneral_generic} by
% \begin{equation}\label{eq:R0_pSEIRS}
% \R_0=\rho\left(FV^{-1}\right)=\rho \left( F_{12}V_{22}^{-1}V_{21}V_{11}^{-1}\right),
% \end{equation}
% with matrices $F$ and $V$ defined by \eqref{eq:FV_R0_pSEIRS}.
% Then the DFE is locally asymptotically stable if $\R_0<1$, and unstable if $\R_0>1$.
% \end{theorem} 
% }

% \frame{\frametitle{Case of proportional incidence}
% With a force of infection using standard (proportional) incidence, $\Phi=\beta_i S_iI_i/N_i$,
% \[
% \left.\frac{\partial\Phi_i}{\partial I_i}\right|_{DFE}=\beta_i\frac{S_i^*}{N_i^*}=\beta_i,
% \]
% so 
% \begin{itemize}
% \item $V$ unchanged
% \item $F_{12}=\diag(\beta_1,\ldots,\beta_{|\P|})$ provided that $\B_i(N_i)$ is such that $S_i^*=N_i^*$ (as is the case for example if $\B_i(N_i)=d_iN_i$). 
% \end{itemize}
% $\Rightarrow$ $\R_0$ does not depend on the movement parameters, only on the within-location parameters.
% }


% \frame{\frametitle{SEIRS with multiple species}
% Suppose $\B_{sp}$ are such that for all $s=1,\ldots,|\C|$ and $p=1,\ldots,|\P|$, $\lim_{t\to\infty}N_{sp}(t)=N_{sp}^*>0$.
 
% Method for multiple species is essentially the same as for a single species.

% To determine the matrices $F$ and $V$, order the state variables by
% species, then by location, \emph{i.e.}, 
% \begin{displaymath}
% E_{11},E_{21},\ldots,E_{|\C|1},E_{12},\ldots,E_{|\C||\P|},
% I_{11},I_{21},\ldots,I_{|\C|1},I_{12},\ldots,I_{|\C||\P|}.
% \end{displaymath}
% }

% \frame{
% The vector $\mathcal{F}$ then takes the form
% \[
% \mathcal{F}=
% \begin{pmatrix}
% \Phi_{11}\\
% \Phi_{21}\\
% \vdots\\
% \Phi_{|\C|1}\\
% \Phi_{21}\\
% \vdots\\
% \Phi_{|\C||\P|}\\
% 0\\
% \vdots\\
% 0
% \end{pmatrix},
% \]
% with the lower block of zeros consisting of $|\C||\P|$ zeros corresponding to the $I$ variables. 
% }

% \frame{
% At the DFE, $\partial\Phi_{sp}/\partial E_{ij}=0$, for all $s,i=1,\ldots,|\C|$ and all $p,j=1,\ldots,|\P|$. 

% Also, $\partial\Phi_{sp}/\partial I_{ij}=0$ for $s,i=1,\ldots,|\C|$ and all $p,j=1,\ldots,|\P|$, whenever $p\neq i$ (there are no contacts outside of the location).

% Then the nonnegative matrix $F$ takes the form
% \begin{displaymath}
% F=\begin{pmatrix}
% 0 & G \\
% 0 & 0 
% \end{pmatrix}
% =
% \begin{pmatrix}
% \hbox{\LARGE $0$} & \bigoplus\limits_{k=1}^{|\P|} G_k \\
% \hbox{\LARGE $0$} & \hbox{\LARGE $0$} 
% \end{pmatrix},
% \end{displaymath}
% with $G_k$ an $|\C|\times |\C|$-matrix with $(i,j)$ entry equal to
% \[
% [G_k]_{ij}=\left.\frac{\partial\Phi_{ik}}{\partial I_{jk}}\right|_{DFE}.
% \] 
% }

% \frame{
% The matrix $V$ is the block matrix
% \begin{displaymath}
% V=\begin{pmatrix}
% A & 0 \\
% -C & B
% \end{pmatrix}
% =\begin{pmatrix}
% \begin{matrix}
% A_{11} & \cdots & A_{1|\P|} \\
% \vdots & \ddots & \vdots \\
% A_{|\P|1} & \cdots & A_{|\P||\P|}
% \end{matrix}
% & \hbox{\LARGE $0$} \\
% -\bigoplus\limits_{k=1}^{|\P|}C_k &
% \begin{matrix}
% B_{11} & \cdots & B_{1|\P|} \\
% \vdots & \ddots & \vdots \\
% B_{|\P|1} & \cdots & B_{|\P||\P|}
% \end{matrix}
% \end{pmatrix}
% \end{displaymath}
% }


% \frame{
% Matrix $A$ is the block matrix $A=A_{jk}$, with each $A_{jk}$ block an
% $|\C|\times|\C|$ diagonal matrix. 
% The $(i,i)$ entry of $A_{kk}$ is equal to
% $d_{ik}+\varepsilon_{ik}+\sum_{l=1}^{|\P|} m_{ilk}$, whereas for $j\neq k$
% the $(i,i)$ entry of $A_{jk}$ is $-m_{ijk}$. 
% Matrix $B$ is the same as $A$ but with $\varepsilon_{ik}$ replaced by
% $\gamma_{ik}$. 
% Finally, $C_k$ is an $s\times s$
% diagonal matrix with $(i,i)$ entry equal to $\varepsilon_{ik}$.

% Matrices $G$, $A$, $B$ and $C$ are $|\C||\P|\times |\C||\P|$-matrices. 
% Matrices $A$ and $B$ are nonsingular $M$-matrices since they have the
% Z-sign pattern and are diagonally dominant by columns. Thus $A^{-1}$ and $B^{-1}$ are
% nonnegative. 
% }

% \frame{
% Due to the particular structure of $F$ and $V$, the computation of
% $\rho(FV^{-1})$ is greatly simplified. 
% Indeed, the inverse $V^{-1}$ of $V$ keeps its block triangular
% structure 
% \begin{displaymath}
% V^{-1}=\begin{pmatrix}
% A^{-1} & 0 \\
% B^{-1}CA^{-1} & B^{-1}
% \end{pmatrix},
% \end{displaymath}
% and it follows that
% \begin{displaymath}
% FV^{-1}=
% \begin{pmatrix}
% 0 & G\\
% 0 & 0 
% \end{pmatrix}
% \begin{pmatrix}
% A^{-1} & 0 \\
% B^{-1}CA^{-1} & B^{-1}
% \end{pmatrix}
% =
% \begin{pmatrix}
% GB^{-1}CA^{-1} & GB^{-1} \\
% 0 & 0
% \end{pmatrix}.
% \end{displaymath}
% Thus
% \begin{displaymath}
% \R_0=\rho(GB^{-1}CA^{-1})
% \end{displaymath}
% }

% \frame{
% Since $GB^{-1}CA^{-1}$ is a nonnegative matrix,
% its spectral radius is attained at the largest real eigenvalue.
% If $\R_0<1$, then the DFE is locally stable, whereas
% if $\R_0>1$, then the DFE is unstable. The following result has been proved.
% \begin{theorem}\label{th:R0_spSEIRS_LAS}
% For system \eqref{sys:spSEIRS} with $|\C|$ species and $\bar n$ locations,
% \begin{equation}\label{eq:R0_spSEIRS}
% \R_0=\rho(GB^{-1}CA^{-1})
% \end{equation}
% If $\R_0<1$, then the DFE is locally asymptotically stable, if $\R_0>1$
% then the DFE is unstable.
% \end{theorem}
% }

% \frame{\frametitle{Case of proportional incidence}
% In the case of a force of infection with proportional incidence, the $(i,j)$ entry of $G_k$ takes the form $\beta_{ijk}\hat S_{ik}/N^*_{jk}$.
% }



% \frame{\frametitle{SEIRS with residency location}
% Order the infected variables (exposed and infectives) as 
% \[
% E_{11},\ldots,E_{1|\P|}, E_{21},\ldots E_{2|\P|},\ldots
% E_{|\P||\P|},I_{11},\ldots,I_{1|\P|}, I_{21},\ldots I_{2|\P|},\ldots,
% I_{|\P||\P|}.
% \]

% Since $\Phi_{ij}$ describes the infection of susceptible residents of location $i$ who are currently in location $j$, there holds that $\partial \Phi_{pq}/\partial I_{ij}=0$ if $q\neq j$, for all $i,j,p,q=1,\ldots,|\P|$, since contacts only involve individuals that are in the same location.
% }

% \frame{
% This gives the block matrix $F$,
% \[
% F=\begin{pmatrix}
% 0 & G \\
% 0 & 0
% \end{pmatrix}
% \]
% where $G$ is an $|\P|^2\times|\P|^2$ matrix having $|\P|^2$ blocks, with each
% block $G_{ij}$ an $|\P|\times|\P|$
% diagonal matrix of the form $G_{ij}=\diag(g_{ijq})$, where 
% $g_{ijq}=\beta_{ijq} \hat N_{iq} /\hat N^p_{q}$, for
% $q=1,\ldots,|\P|$.
% \[
% G_{ij}=\diag
% \left(
% \left.\frac{\partial\Phi_{i1}}{\partial I_{j1}}\right|_{DFE},\left.\frac{\partial\Phi_{i2}}{\partial I_{j2}}\right|_{DFE},\ldots,\left.\frac{\partial\Phi_{i|\P|}}{\partial I_{j|\P|}}\right|_{DFE}
% \right).
% \]
% }

% \frame{
% Also, $V$ is a lower triangular block matrix,
% \[
% V=\begin{pmatrix}
% A & 0 \\
% C & B
% \end{pmatrix}
% =
% \begin{pmatrix}
% \bigoplus\limits_{p=1}^{|\P|}A_p & \hbox{\LARGE $0$} \\
% -\bigoplus\limits_{p=1}^{|\P|}C_p & \bigoplus\limits_{p=1}^{|\P|}B_p 
% \end{pmatrix}
% \] 
% where each block $A$, $B$ and $C$ is $|\P|^2\times|\P|^2$.
% }


% \frame{
% For $p=1,\ldots|\P|$, $A_p$ is an $|\P|\times|\P|$ matrix with
% \[
% A_p=
% \tiny
% \left[
% \begin{array}{ccccc}
% \varepsilon_{p1}+d_{p1}+\sum_{k=1}^{|\P|}m_{pk1}^E & -m_{p12}^E & -m_{p13}^E & \cdots & -m_{p1|\P|}^E \\
% -m_{p21}^E & \varepsilon_{p2}+d_{p2}+\sum_{k=1}^{|\P|}m_{pk2}^E & -m_{p23}^E & \cdots & -m_{p2|\P|}^E \\
% & & & \\
% -m_{p|\P|1}^E & -m_{p|\P|2}^E & -m_{p|\P|3}^E & \cdots & \varepsilon_{p|\P|}+d_{p|\P|}+\sum_{k=1}^{|\P|}m_{pk|\P|}^E
% \end{array}
% \right],
% \]
% }

% \frame{
% $B_p$ is an $|\P|\times|\P|$-matrix with
% \[
% B_p=\tiny
% \left[
% \begin{array}{ccccc}
% \gamma_{p1}+d_{p1}+\sum_{k=1}^{|\P|}m_{pk1}^I & -m_{p12}^I & -m_{p13}^I & \cdots & -m_{p1|\P|}^I \\
% -m_{p21}^I & \gamma_{p2}+d_{p2}+\sum_{k=1}^{|\P|}m_{pk2}^I & -m_{p23}^I & \cdots & -m_{p2|\P|}^I \\
% & & & \\
% -m_{p|\P|1}^I & -m_{p|\P|2}^I & -m_{p|\P|3}^I & \cdots & \gamma_{p|\P|}+d_{p|\P|}+\sum_{k=1}^{|\P|}m_{pk|\P|}^I
% \end{array}
% \right],
% \]
% and $C_p$ is an $|\P|\times|\P|$ diagonal matrix with $C_p=\diag(\varepsilon_{p1},\ldots,\varepsilon_{p|\P|})$.
% }

% \frame{
% Since $A_k$ and $B_k$ have the Z-sign pattern and have all positive
% column sums, $A_k$ and $B_k$ are nonsingular M-matrices. Note that
% \[
% \left(\bigoplus\limits_{p=1}^{|\P|}\left(B_p\right)^{-1}\right)
% \left(\bigoplus\limits_{p=1}^{|\P|}\left(C_p\right)\right)
% \left(\bigoplus\limits_{p=1}^{|\P|}\left(A_p\right)^{-1}\right)
% =\bigoplus\limits_{p=1}^{|\P|}\left(A_pC_p^{-1}B_p\right)^{-1}.
% \]
% }

% \frame{
% Therefore, the inverse of $V$ is the nonnegative matrix
% \begin{equation}\label{eq:invV_ppSEIRS}
% V^{-1}=
% \begin{pmatrix}
% \bigoplus\limits_{p=1}^{|\P|}\left(A_p\right)^{-1} & \hbox{\LARGE $0$} \\
% \bigoplus\limits_{p=1}^{|\P|}\left(A_pC_p^{-1}B_p\right)^{-1}
% & \bigoplus\limits_{p=1}^{|\P|}\left(B_p\right)^{-1}
% \end{pmatrix}.
% \end{equation}
% }

% \frame{
% Since $V^{-1}$ is lower triangular by blocks, $FV^{-1}$ can be given
% by blocks.
% The basic reproduction number
% for system (\ref{sys:ppSEIRS}) is 
% \begin{equation}
% \R_0=\rho
% \left\{
% G \left(
% \bigoplus\limits_{p=1}^{|\P|}
% (A_p)C_p^{-1}(B_p)\right)^{-1}
% \right\}
% \label{eq:R0}
% \end{equation} 
% where $\rho\{\cdot\}$ is the spectral radius, and the following result
% holds.
% \begin{theorem}
% Let $\R_0$ be defined as in (\ref{eq:R0}). If $\R_0<1$, then the
% DFE of (\ref{sys:ppSEIRS}) is locally asymptotically stable. 
% If $\R_0>1$, then the DFE of (\ref{sys:ppSEIRS}) is unstable.
% \label{th:R0}
% \end{theorem}
% }

%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
\subsection{Global stability of the DFE when $\R_0<1$}

\frame{\frametitle{The toy $|\P|$-SLIRS}
LAS results for $\R_0<1$ can sometimes be strengthened to GAS. One class of models where this works often is when the population is either constant or asymptotically constant and incidence is \emph{standard}
\vfill
\begin{theorem}\label{th:pSLIRS_GAS}
Let $\R_0$ be defined as in Theorem~\ref{th:LAS_DFE_pSLIRS_toy} and use proportional incidence $\Phi_p=\beta_pS_pI_p/N_p$. If $\R_0<1$, then the DFE of system \eqref{sys:pSLIRS_toy} is globally asymptotically stable
\end{theorem}
}



\frame{\frametitle{$|\S|\;|\P|$-SLIRS with multiple species}
In the case in which movement is equal for all compartments and there is no disease death, a comparison theorem argument can be used as in Theorem~\ref{th:pSLIRS_GAS} to show that if $\R_0<1$, then the
DFE of the $|\S|\;|\P|$-SLIRS \eqref{sys:spSLIRS} is globally asymptotically stable. 
\vfill
\begin{theorem}\label{th:R0_spSEIRS_GAS}
For system \eqref{sys:spSLIRS} with $|\S|$ species and $|\P|$ locations, with movement equal for all compartments, define $\R_0$ appropriately and use proportional incidence. 
If $\R_0<1$, then the DFE is globally asymptotically stable
\end{theorem}
}



%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%
\subsection{Metapopulation-specific problems}

\begin{frame}{Metapopulation-specific problems -- Two main types}
\begin{itemize}
	\item \textbf{Inheritance problems --} Which of the properties of the constituting units are inherited by the metapopulation?
	\vfill
	\item \textbf{Metapopulation-specific behaviours --} Are there dynamic behaviours observed in a metapopulation not observed in the constituting units?
\end{itemize}
\end{frame}


\begin{frame}{Inherited dynamical properties (a.k.a. I am lazy)}
	Given
	\begin{subequations}
		\begin{align}
			s_{kp}' &= f_{kp}(S_p,I_p) \label{sys:generic_intra_ds} \\
			i_{\ell p}' &= g_{\ell p}(S_p,I_p) \label{sys:generic_intra_di}
		\end{align}				
	\end{subequations}
	with known properties, what is known of
	\begin{subequations}
		\begin{align}
			s_{kp}' &= f_{kp}(S_p,I_p)+\textstyle{\sum_{q\in\mathcal{P}}} m_{kpq}s_{kq} 
			\label{sys:generic_inter_ds} \\
			i_{\ell p}' &= g_{\ell p}(S_p,I_p)+\textstyle{\sum_{q\in\mathcal{P}}} m_{\ell pq}i_{\ell q}
			\label{sys:generic_inter_di}
		\end{align}				
	\end{subequations}
	\begin{itemize}
		\item Existence and uniqueness $\checkmark$
		\item Invariance of $\mathbb{R}_+^\bullet$ under the flow $\checkmark$
		\item Boundedness $\checkmark$
		\item Location of individual $\mathcal{R}_{0i}$ and general $\mathcal{R}_0$ ?
		\item GAS ?		
	\end{itemize}
	- 
\end{frame}

\begin{frame}{An inheritance problem -- Backward bifurcations}
	\begin{itemize}
		\item Suppose a model that, isolated in a single patch, undergoes so-called backward bifurcations
		\item This means the model admits subthreshold endemic equilibria
		\item What happens when you couple many such consistuting units?
	\end{itemize}
	\vfill
	\emph{YES}, coupling together backward bifurcating units can lead to a system-level backward bifurcation
	\vfill
	JA, Ducrot \& Zongo. \href{https://julien-arino.github.io/assets/pdf/papers/2012_ArinoDucrotZongo-JMB64.pdf}{A metapopulation model for malaria with transmission-blocking partial immunity in hosts}. \emph{Journal of Mathematical Biology} \textbf{64}(3):423-448 (2012) 		
\end{frame}

\begin{frame}{Metapopulation-induced behaviours ?}
	``Converse'' problem to inheritance problem. Given
	\begin{align}
	s_{kp}' &= f_{kp}(S_p,I_p)  \tag{9a} \\
	i_{\ell p}' &= g_{\ell p}(S_p,I_p) \tag{9b}
	\end{align}
	with known properties, does
	\begin{align}
	s_{kp}' &= f_{kp}(S_p,I_p)+\textstyle{\sum_{q\in\mathcal{P}}} m_{kpq}s_{kq}  \tag{10a} \\
	i_{\ell p}' &= g_{\ell p}(S_p,I_p)+\textstyle{\sum_{q\in\mathcal{P}}} m_{\ell pq}i_{\ell q}  \tag{10b}
	\end{align}
	exhibit some behaviours not observed in the uncoupled system?
	
	E.g.: units have $\{\mathcal{R}_0<1\implies$ DFE GAS, $\mathcal{R}_0>1\implies$ 1 GAS EEP$\}$ behaviour, metapopulation has periodic solutions
		
\end{frame}

\begin{frame}{Mixed equilibria}
	Can there be situations where some locations are at the DFE and others at an EEP?
	\vfill
	This is the problem of \textbf{mixed equilibria}
	\vfill
	This is a metapopulation-specific problem, not one of inheritance of dynamical properties!
\end{frame}

\begin{frame}{Types of equilibria}
	\begin{definition}[Location level EP]
		Location $p\in\mathcal{P}$ at equilibrium is \textbf{empty} if $X_p^\star=0$, at the \textbf{disease-free equilibrium} if $X_p^\star=(s_{k_1p}^\star,\ldots,s_{k_up}^\star,0,\ldots,0)$, where $k_1,\ldots,k_u$ are some indices with $1\leq u\leq|\mathcal{U}|$ and $s_{k_1p}^\star,\ldots,s_{k_up}^\star$ are positive, and at an \textbf{endemic equilibrium} if $X_p\gg 0$
	\end{definition}
	\vfill
	\begin{definition}[Metapopulation level EP]
		A \textbf{population-free equilibrium} has all locations empty. A \textbf{metapopulation disease-free equilibrium} has all locations at the disease-free equilibrium for the same compartments. A \textbf{metapopulation endemic equilibrium} has all locations at an endemic equilibrium
	\end{definition}
\end{frame}

\begin{frame}{Mixed equilibria}
	\begin{definition}
		A \textbf{mixed equilibrium} is an equilibrium such that
		\begin{itemize}
			\item all locations are at a disease-free equilibrium but the system is not at a metapopulation disease-free equilibrium
			\item or, there are at least two locations that have different types of location-level equilibrium (empty, disease-free or endemic)
		\end{itemize}
	\end{definition}
	E.g., 
	$$
	((S_1,I_1,R_1),(S_2,I_2,R_2))=((+,0,0),(+,+,+))
	$$
	is mixed and so is
	$$
	((S_1,I_1,R_1),(S_2,I_2,R_2))=((+,0,0),(+,0,+))
	$$
\end{frame}


\begin{frame}
	\begin{theorem}
		Suppose that movement is similar for all compartments (MSAC) and that the system is at equilibrium
		\begin{itemize}
			\item If patch $p\in\mathcal{P}$ is empty, then all patches in $\mathcal{A}(p)$ are empty 
			\item If patch $p\in\mathcal{P}$ is at a disease free equilibrium, then the subsystem consisting of all patches in $\{p,\mathcal{A}(p)\}$ is at a metapopulation disease free equilibrium 
			\item If patch $p\in\mathcal{P}$ is at an endemic equilibrium, then all patches in $\mathcal{D}(p)$ are also at an endemic equilibrium
			\item If $\mathcal{G}^c$ is strongly connected for some compartment $c\in\mathcal{C}$, then there does not exist mixed equilibria
		\end{itemize}
	\end{theorem}
	Note that MSAC $\implies$ $\mathcal{A}^c=\mathcal{A}$ and $\mathcal{D}^c=\mathcal{D}$ for all $c\in\mathcal{C}$
\end{frame}




% \frame{\frametitle{Similar movement}
% What is important here is not that movement be status-independent, but that different states have the same connection graph (irrespective of the movement rates).
% \begin{definition}\label{def:similar_movement}
% Movement in system \eqref{sys:pSEIRS} is similar for all states if, for all $i,j=1,\ldots,|\P|$, there holds that either
% \[
% m_{ij}^Sm_{ij}^Em_{ij}^Im_{ij}^R>0
% \]
% or
% \[
% m_{ij}^S=m_{ij}^E=m_{ij}^I=m_{ij}^R=0.
% \]
% Movement in system \eqref{sys:spSEIRS} is similar for all states if, for all $i,j=1,\ldots,|\P|$ and a given species $c\in\C$, there holds that either
% \[
% m_{sij}^Sm_{sij}^Em_{sij}^Im_{sij}^R>0
% \]
% or
% \[
% m_{sij}^S=m_{sij}^E=m_{sij}^I=m_{sij}^R=0.
% \]
% If this is true for all states and all species, then movement in \eqref{sys:spSEIRS} is similar for all states and all species.
% Movement in system \eqref{sys:ppSEIRS} is similar for all states if, for all $i,j,k=1,\ldots,|\P|$, there holds that either
% \[
% m_{ijk}^Sm_{ijk}^Em_{ijk}^Im_{ijk}^R>0
% \]
% or
% \[
% m_{ijk}^S=m_{ijk}^E=m_{ijk}^I=m_{ijk}^R=0.
% \]
% \end{definition}
% }


% \frame{\frametitle{Movement similar for all states -- Model with normal movement}
% System with multiple species \eqref{sys:spSEIRS}. Specialization to the case of a single species is trivial.

% \begin{theorem}\label{th:DFE_propagates_spSEIRS}
% Suppose that \eqref{sys:spSEIRS} with movement similar for all states is at an equilibrium. 

% If a given location $p$ is at a DFE, then all locations that have an access to location $p$ for a given species $s$ are also at a DFE.
% \end{theorem}
% }

% \frame{\frametitle{Proof}
% Fix the species index at $s$. For simplicity suppose that $p=1$, i.e., there is no disease in location 1. Thus $E_{s1}=I_{s1}=0$. Then for $p=1$, \eqref{sys:spSEIRS_Isp} is
% \[
% 0=\frac{d}{dt}I_{s1}=\sum_{r=2}^{|\P|}m_{s1r}I_{sr}.
% \]
% For a given location $r$, define
% \[
% \mathcal{P}_{\to r}=\{q:m_{srq}>0\},
% \]
% the subset of locations with a direct access to location $r$, and
% \[
% \mathcal{P}_{\not\to r}=\{q\neq r: m_{srq}=0\},
% \]
% the subset of locations with no direct access to location $r$. 
% }

% \frame{
% Then, since $I_{sr}\geq 0$ and
% \[
% \sum_{r=2}^{|\P|}m_{s1r}I_{sr}=\sum_{r\in\mathcal{P}_{\to 1}}m_{s1r}I_{sr}+
% \sum_{r\in\mathcal{P}_{\not\to 1}}m_{s1r}I_{sr}=0,
% \]
% it follows that $I_{sr}=0$ for $r\in\mathcal{P}_{\to 1}$. Similarly, setting $p=1$ in \eqref{sys:spSEIRS_Esp} and using $\mathcal{P}_{\to 1}$, it follows that $E_{sr}=0$ for $r\in\mathcal{P}_{\to 1}$. Thus, all locations $r$ with a direct access to location 1 have no disease, i.e., are such that $E_{sr}=I_{sr}=0$.


% Now consider a location $r$ in $\mathcal{P}_{\to 1}$. Using the same argument as previously, it follows that $E_{sw}=I_{sw}=0$ for all $w\in\mathcal{P}_{\to r}$. locations that are in $\mathcal{P}_{\to r}\setminus\mathcal{P}_{\to 1}$ have a length 2 access to location 1. By induction, all locations in $\overline{\mathcal{P}}_{\to 1}$ are at the DFE if location 1 is at the DFE.
% }

% \frame{
% \begin{itemize}
% \item
% This result is independent of the nature of the birth function $\B_{sp}$. 
% \item Conclusions have not been derived on the nature of $R_p$ for those locations that are at the DFE, nor has it been shown that $S_p\to N_p^*$. 
% \item In fact, with a little additional work, it can be shown that $\lim_{t\to\infty}R_k(t)=0$ for $k\in\overline{\mathcal{P}}_{\to p}$. In this case, $S_p\to N_p^*$, with the precise value of $N_p^*$ undetermined until a birth function has been chosen.
% \end{itemize}
% }

% \frame{
% \begin{theorem}\label{th:EEP_propagates_spSEIRS}
% Suppose that \eqref{sys:spSEIRS} with movement similar for all states is at an equilibrium. 

% If a given location $p$ is at an endemic equilibrium, then all locations that can be accessed from location $p$ for a given species $s$ are also at an endemic equilibrium.
% \end{theorem}
% }

% \frame{\frametitle{Proof}
% Fix the species index $s$. For simplicity suppose that $p=1$, i.e., $E_{s1}+I_{s1}>0$. From \eqref{sys:spSEIRS_Esp} and \eqref{sys:spSEIRS_Isp} with $q\neq 1$,
% \begin{align*}
% 0=\frac{d}{dt}(E_{sq}+I_{sq}) &= \Phi_{sq}-d_{sq}(E_{sq}+I_{sq})-\gamma_{sq}I_{sq} \\
% &\quad +\sum_{r=1}^{|\P|}m_{sqr}(E_{sr}+I_{sr})-\sum_{r=1}^{|\P|}m_{srq}(E_{sq}+I_{sq}).
% \end{align*}
% Assume that $E_{sq}+I_{sq}=0$ and $m_{sq1}>0$, i.e., location 1 has access to location $q$. Then the above equation reduces to 
% \[
% 0=\sum_{r=1}^{|\P|}m_{sqr}(E_{sr}+I_{sr}),
% \]
% and implies that $E_{s1}+I_{s1}=0$, giving a contradiction. Thus the disease in location $q$ is at an endemic equilibrium. The remainder of the proof follows as in the proof of Theorem~\ref{th:DFE_propagates_spSEIRS}.
% }

% %%%%%%%%%%%%%%%
% \frame{\frametitle{Movement similar for all states -- Model with residency location}
% \begin{theorem}\label{th:DFE_propagates_ppSEIRS}
% Suppose that system \eqref{sys:ppSEIRS} with movement similar for all states is at an equilibrium, and that a given location $p$ is at the DFE. 

% Then all locations that can be accessed from location $p$, and all locations that have an access to location $p$, are at the DFE.
% \end{theorem}
% }

% \frame{\frametitle{Proof}
% Suppose, without loss of generality, that location $1$ is at the DFE, i.e., $I_{k1}=E_{k1}=0$ for all $k=1,\ldots,|\P|$. 

% Then consider \eqref{sys:ppSEIRS_Eij} and \eqref{sys:ppSEIRS_Iij} with $i=1$. Since $I_{11}=0$, it follows that $\Phi_{11}=0$ and thus
% \begin{align*}
% \frac{d}{dt}E_{11} &= \sum_{k=1}^{|\P|} m_{11k}^E E_{1k} \\
% \frac{d}{dt}I_{11} &= \sum_{k=1}^{|\P|} m_{11k}^I I_{1k}. 
% \end{align*}
% Recall that variables remain nonnegative. 

% Since the system is at equilibrium, $E_{1k}=0$ for all locations $k$ such that E individuals from location $k$ have direct access to location 1, and $I_{1k}=0$ for all locations $k$ such that I individuals from location $k$ have direct access to location 1. 
% }

% \frame{
% These sets of locations are denoted $\mathcal{P}_{\to 1}^E$ and $\mathcal{P}_{\to 1}^I$, respectively. Since movement is similar for all states, $\mathcal{P}_{\to 1}^E=\mathcal{P}_{\to 1}^I=:\mathcal{P}_{\to 1}$. 

% In summary, if location 1 is at the DFE, then there holds that for all locations $j$ in $\mathcal{P}_{\to 1}$, $E_{1j}=I_{1j}=0$, i.e., there is no disease in visitors from location 1 visiting locations that have direct access to location 1. 
% }

% \frame{
% Consider now \eqref{sys:ppSEIRS_Eij} for one of these locations, i.e., for $j\in\mathcal{P}_{\to 1}$. There holds, for visitors to $j$ from location 1,
% \[
% \frac{d}{dt}E_{1j} = \Phi_{1j}.
% \]
% Since the system is at an equilibrium, $\Phi_{1j}=0$, that is 
% \[
% 0=\Phi_{1j}=\sum_{k=1}^{|\P|}\phi_{1k}(S_{1j},I_{kj}).
% \]
% It was shown (Theorem~\ref{th:Spositive}) that $S_{ij}>0$ for all positive times, provided that $m_{ijk}>0$. Since the $S_{ij}$ are positive, there holds that for all $j\in\mathcal{P}_{\to 1}$ such that $m_{1jk}>0$,
% $I_{kj}=0$. Using the same type of argument that was used to show that $R=0$ in the proof of Theorem~\ref{th:R0_spSEIRS_GAS}, it follows that for these locations, there also holds that $E_{kj}=0$.

% To summarize, if location 1 is at the DFE, then locations $j\in\mathcal{P}_{\to 1}$ are also at the DFE. By induction, all locations that are in $\overline{\mathcal{P}}_{\to 1}$ are at the DFE.
% }




%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%
\subsection{Computational considerations}

\begin{frame}
	\begin{itemize}
		\item JA. \href{https://doi.org/10.1016/j.idm.2017.05.001}{Spatio-temporal spread of infectious pathogens of humans}. \emph{Infectious Disease Modelling} \textbf{2}(2):218-228 (2017)
		\item JA. \href{https://doi.org/10.1016/j.idm.2019.12.008}{Mathematical epidemiology in a data-rich world}. \emph{Infectious Disease Modelling} \textbf{5}:161-188 (2020)
		\item github repo \href{https://github.com/julien-arino/modelling-with-data}{modelling-with-data}
	\end{itemize}
\end{frame}

\begin{frame}{Not very difficult}
As for the mathematical analysis: if you do things carefully and think about things a bit, numerics are not hard. Well: not harder than numerics in low-D
\vfill
Exploit vector structure
\end{frame}

\begin{frame}[fragile]{Set up parameters}
\begin{lstlisting}
pop = c(34.017, 1348.932, 1224.614, 173.593, 93.261) * 1e+06
countries = c("Canada", "China", "India", "Pakistan", "Philippines")
T = matrix(data = 
        c(0, 1268, 900, 489, 200, 
        1274, 0, 678, 859, 150, 
        985, 703, 0, 148, 58, 
        515, 893, 144, 0, 9, 
        209, 174, 90, 2, 0), 
      nrow = 5, ncol = 5, byrow = TRUE)	
\end{lstlisting}
\end{frame}

\begin{frame}[fragile]{Work out movement matrix}
\begin{lstlisting}
p = list()
# Use the approximation explained in Arino & Portet (JMB 2015)
p$M = mat.or.vec(nr = dim(T)[1], nc = dim(T)[2])
for (from in 1:5) {
  for (to in 1:5) {
    p$M[to, from] = -log(1 - T[from, to]/pop[from])
  }
  p$M[from, from] = 0
}
p$M = p$M - diag(colSums(p$M))
\end{lstlisting}	
\end{frame}

\begin{frame}[fragile]
\begin{lstlisting}
p$P = dim(p$M)[1]
p$eta = rep(0.3, p$P)
p$epsilon = rep((1/1.5), p$P)
p$pi = rep(0.7, p$P)
p$gammaI = rep((1/5), p$P)
p$gammaA = rep((1/3), p$P)
# The desired values for R_0
R_0 = rep(1.5, p$P)
\end{lstlisting}	
\end{frame}

\begin{frame}[fragile]{Write down indices of the different state variable types}
	Save index of state variable types in state variables vector (we have to use a vector and thus, for instance, the name ``S'' needs to be defined)
\begin{lstlisting}
p$idx_S = 1:p$P
p$idx_L = (p$P+1):(2*p$P)
p$idx_I = (2*p$P+1):(3*p$P)
p$idx_A = (3*p$P+1):(4*p$P)
p$idx_R = (4*p$P+1):(5*p$P)
\end{lstlisting}	
\end{frame}

\begin{frame}[fragile]{Set up IC and time}
\begin{lstlisting}
# Set initial conditions. For example, we start with 2
# infectious individuals in Canada.
L0 = mat.or.vec(p$P, 1)
I0 = mat.or.vec(p$P, 1)
A0 = mat.or.vec(p$P, 1)
R0 = mat.or.vec(p$P, 1)
I0[1] = 2
S0 = pop - (L0 + I0 + A0 + R0)
# Vector of initial conditions to be passed to ODE solver.
IC = c(S = S0, L = L0, I = I0, A = A0, R = R0)
# Time span of the simulation (5 years here)
tspan = seq(from = 0, to = 5 * 365.25, by = 0.1)
\end{lstlisting}	
\end{frame}


\begin{frame}[fragile]{Set up $\beta$ to avoid blow up}
	Let us take $\R_0=1.5$ for patches in isolation. Solve $\R_0$ for $\beta$ 
	$$
	\beta=\frac{\R_0}{S(0)}
	\left(
	\frac{1-\pi_p}{\gamma_{Ip}}
	+\frac{\pi_p\eta_p}{\gamma_{Ap}}
	\right)^{-1}
	$$ 
\begin{lstlisting}
for (i in 1:p$P) {
  p$beta[i] = 
    R_0[i] / S0[i] * 1/((1 - p$pi[i])/p$gammaI[i] + p$pi[i] * p$eta[i]/p$gammaA[i])
}
\end{lstlisting}	
\end{frame}

\begin{frame}[fragile]{Define the vector field}
\begin{lstlisting}[language=Renhanced]
SLIAR_metapop_rhs <- function(t, x, p) {
  with(as.list(p), {
    S = x[idx_S]
    L = x[idx_L]
    I = x[idx_I]
    A = x[idx_A]
    R = x[idx_R]
    N = S + L + I + A + R
    Phi = beta * S * (I + eta * A) / N
    dS = - Phi + MS \%*\% S
    dL = Phi - epsilon * L + p$ML \%*\% L
    dI = (1 - pi) * epsilon * L - gammaI * I + MI \%*\% I
    dA = pi * epsilon * L - gammaA * A + MA \%*\% A
    dR = gammaI * I + gammaA * A + MR \%*\% R
    dx = list(c(dS, dL, dI, dA, dR))
    return(dx)
  })
}	
\end{lstlisting}
\end{frame}
	

\begin{frame}[fragile]{And now call the solver}
\begin{lstlisting}
# Call the ODE solver
sol <- ode(y = IC, 
      times = tspan, 
      func = SLIAR_metapop_rhs, 
      parms = p,
      method = "ode45")
\end{lstlisting}	
\end{frame}
	
\begin{frame}[fragile]{One little trick (case with demography)}
	Suppose demographic EP is $\mathbf{N}^\star=(\bd-\mathcal{M})^{-1}\mathbf{b}$

	Want to maintain $\mathbf{N}(t)=\mathbf{N}^\star$ for all $t$ to ignore convergence to demographic EP. Think in terms of $\mathbf{b}$:
	
	$$
	\mathbf{N}'=0\iff \mathbf{b}-\bd\mathbf{N}+\mathcal{M}\mathbf{N}=0 \iff \mathbf{b} = (\bd-\mathcal{M})\mathbf{N}
	$$
	
	So take $\mathbf{b}=(\bd-\mathcal{M})\mathbf{N}^\star$
	
	Then
	$$
	\mathbf{N}' = (\bd-\mathcal{M})\mathbf{N}^\star
	-\bd\mathbf{N}+\mathcal{M}\mathbf{N}
	$$
	and thus if $\mathbf{N}(0)=\mathbf{N}^\star$, then $\mathbf{N}'(0)=0$ and thus $\mathbf{N}'=0$ for all $t\geq 0$, i.e., $\mathbf{N}(t)=\mathbf{N}^\star$ for all $t\geq 0$
\end{frame}

\begin{frame}{Word of warning about that trick, though..}
$$
\mathbf{b}=(\bd-\mathcal{M})\mathbf{N}^\star
$$
	
$\bd-\M$ has nonnegative (typically positive) diagonal entries and nonpositive off-diagonal entries
	
Easy to think of situations where the diagonal will be dominated by the off-diagonal, so $\bb$ could have negative entries
	
$\implies$ use this for numerics, not for the mathematical analysis
\end{frame}


%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%
\section{Spatial propagation on a ``road''}

\maxFrameImage{FIGS/LopezCoutinhoBurratiniMassad-1999.png}

\begin{frame}\frametitle{Spatial spread of an epidemic on a ``road''}
\begin{itemize}
\item SIS and SIR models
\vfill
\item Consider a road of length $L$
\vfill
\item $S(x,t)$, $I(x,t)$ and (when relevant) $R(x,t)$ are the densities of individuals in the different compartments at location $x\in[0,L]$ at time $t$
\vfill
\item For simplicity, denote 
\[
\frac{\partial}{\partial t}X(x,t) = X_t(x,t) 
\]
\end{itemize}
\end{frame}

\begin{frame}\frametitle{The SIR model on the road}
\begin{subequations}\label{sys:SIRS_spatial}
\begin{align}
S_t(x,t) &= -\beta(x,t)S(x,t)-dS(x,t)+dN(x)+\lambda_1I(x,t) 
\label{sys:SIRS_spatial_S} \\
I_t(x,t) &= \lambda(x,t)S(x,t)-dI(x,t)-(\gamma_1+\gamma_2)I(x,t)
\label{sys:SIRS_spatial_I} \\
R_t(x,t) &= \gamma_2I(x,t)-dR(x,t)
\end{align}
where the force of infection is
\begin{equation}\label{sys:SIRS_spatial_lambda}
\lambda(x,t)=\frac 1N \int_0^L\beta(x,x')I(x,x')dx'
\end{equation}
and the total population along the road is
\begin{equation}
N=\int_0^LN(x')dx'
\end{equation}
\end{subequations}
\end{frame}


\begin{frame}
Take the SIS model as an example ($\gamma_2=0,\gamma_1=\gamma$). Solve \eqref{sys:SIRS_spatial_I} in terms of $\lambda$:
\begin{equation}\label{sys:SIS_spatial_compute_I}
\begin{aligned}
I(x,t) &= \exp\left(-\int_0^t\lambda(x,s)-(d+\gamma)tds\right) \\
& \times \int_0^t \lambda(x,t')N(x)
e^{\int_0^{t'}\lambda(x,s)+(d+\gamma)t' ds}dt' \\
&+I(x,0)\exp\left(-\int_0^t \lambda(x,s)-(d+\gamma)tds\right)
\end{aligned}
\end{equation}
\end{frame}

\begin{frame}
Substitute \eqref{sys:SIS_spatial_compute_I} into \eqref{sys:SIRS_spatial_lambda}
\[
\begin{aligned}
\lambda(x,t) &=
\int_0^L \beta(x,x')n(x')
\int_0^t \lambda(x',t')
e^{-\int_{t'}^t \lambda(x',s)-(d+\gamma)(t-t')ds}dt'dx' \\
&+\int_0^L \beta(x,x')i(x',0)
e^{-\int_0^t \lambda(x',s)-(d+\gamma)t ds}dx'
\end{aligned}
\]
where $n(x)=N(x)/N$ and $i(x,t)=I(x,t)/N$. Without demography ($d=0$):
\[
\begin{aligned}
\lambda(x,t) &=
\int_0^L \beta(x,x')n(x')
\int_0^t \lambda(x',t')
e^{-\int_{t'}^t \lambda(x',s)-\gamma(t-t')ds}dt'dx' \\
&\quad +\int_0^L \beta(x,x')i(x',0)
e^{-\int_0^t \lambda(x',s)-\gamma t ds}dx'
\end{aligned}
\]
\end{frame}


\begin{frame}
Thus the problem is in the form
\[
\bB\lambda(x,t)=\lambda(x,t)
\]
\vfill
In both cases, $\bB$ is a Hammerstein-type operator in $x$
\vfill
\begin{itemize}
\item SIR case: $\bB$ is a nonlinear Volterra operator in $t$ \imply existence and uniqueness of solutions
\vfill
\item SIS case: $\bB$ is not a nonlinear Volterra operator in $t$. However, it resembles one and the authors establish existence and uniqueness of solutions
\end{itemize}
\end{frame}


\begin{frame}
In both cases, there is a travelling wave front then convergence to a steady state
\vfill
In the SIS case
\[
\lambda(x)=\lim_{t\to\infty}\bB\lambda(x,t)
=\bB_\infty\lambda(x)=
\int_0^L\beta(x,x')n(x')
\frac{\lambda(x',\infty)}{\lambda(x',\infty)+\gamma}
\]
which does not depend on $t$
\vfill 
They then discuss conditions s.t. this limit $\neq 0$, by looking for values of $z$ s.t. $\bB_\infty\lambda(x)=z\lambda(x)$ has a positive solution
\vfill
Show there exists a threshold $z_{\text{threshold}}=\R_0$ s.t. $\lambda(x)\equiv 0$ if $\R_0<1$ and a positive solution if $\R_0>1$
\end{frame}


%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%
\section{A diffusion-type spatial spread model}

\maxFrameImage{FIGS/MurraySeward-1992.png}

\begin{frame}{Spatial spread of rabies with immunity}
\begin{subequations}
\label{sys:rabies}
\begin{align}
\frac{\partial S}{\partial t} &= 
(a-b)\left(1-\frac NK\right)S+a^\star R-\beta SI \label{sys:rabies_S} \\
\frac{\partial L}{\partial t} &= 
\beta SI-\sigma L-\left(b+(a-b)\frac NK\right)L \label{sys:rabies_L} \\
\frac{\partial I}{\partial t} &= 
\sigma L-\alpha I-\gamma I-\left(b+(a-b)\frac NK\right)I 
+ D_I\frac{\partial^2 I}{\partial x^2} \label{sys:rabies_I} \\
\frac{\partial R}{\partial t} &= 
\gamma I+(a-a^\star)R+\left(b+(a-b)\frac NK\right)R \label{sys:rabies_R}
\end{align}
\end{subequations}
where $N=S+L+I+R$
\end{frame}

\end{document}
