%\SweaveUTF8
\documentclass[aspectratio=43]{beamer}

\input{slides_setup_nonLightBoard_whiteBG.tex}

\title{Introduction to mathematical epidemiology}
\subtitle{Potchefstroom -- Course 01 -- Part 01}
\author{Julien Arino}
\date{20 February 2024}

\begin{document}
\SweaveOpts{concordance=TRUE}
\SweaveOpts{prefix.string = FIGS/lecture-01}

<<set-options,echo=FALSE>>=
# Are we plotting for a dark background
plot_blackBG = FALSE
# Source the useful functions file
source("../CODE/useful_functions.R")
@


% The title page
\begin{frame}[noframenumbering,plain]
  \begin{tikzpicture}[remember picture,overlay]
    \node[above right,inner sep=0pt,opacity=0.2] at (current page.south west)
    {
        \includegraphics[height=\paperheight,width=\paperwidth]{FIGS/Gemini-generated-viruses-bacteria-Bacon-style-1.jpeg}
    };
\end{tikzpicture}
  \setbeamercolor{title}{fg=subsub_header_section}
  \setbeamercolor{author}{fg=subsub_header_section} 
  \setbeamerfont{title}{size=\Large,series=\bfseries}
  \setbeamerfont{author}{size=\Large,series=\bfseries}
  \setbeamerfont{date}{series=\bfseries}
  %\setbeamerfont{date}{size=\small,series=\mdseries}
	\titlepage
\end{frame}
\addtocounter{page}{-1}

% % The title page
% \begin{frame}[noframenumbering,plain]
%   \titlepage
% \end{frame}
% \addtocounter{page}{-1}

% The outline page
{
\setbeamercolor{background canvas}{bg=outline_colour}
\begin{frame}{Outline}
    \tableofcontents[hideallsubsections]
\end{frame}
\addtocounter{page}{-1}
}

%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
\section{Epidemiology}

%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
\subsection{Definition}
\begin{frame}{Definition}

\begin{itemize}
    \item[\href{https://en.wikipedia.org/wiki/Epidemiology}{Wiki}] 
    \defword{Epidemiology} is the study and analysis of the distribution (who, when, and where), patterns and determinants of health and disease conditions in defined populations
    \item[\href{https://www.bmj.com/about-bmj/resources-readers/publications/epidemiology-uninitiated/1-what-epidemiology}{BMJ}]
    \defword{Epidemiology} is the study of how often diseases occur in different groups of people and why. Epidemiological information is used to plan and evaluate strategies to prevent illness and as a guide to the management of patients in whom disease has already developed 
\end{itemize}
\vfill
Etymology: \emph{the study of what is upon the people}, derived from the Greek \emph{epi} (\emph{upon}, \emph{among}), \emph{demos} (\emph{people}, \emph{district}) and \emph{logos} (\emph{study}, \emph{word}, \emph{discourse})
\end{frame}


%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
\subsection{Who, when and where}


\begin{frame}{Who, when and where}
Recall part of the definition on Wikipedia
\begin{quote}
\defword{Epidemiology} is the study and analysis of the distribution (who, when, and where)  
\end{quote}
\end{frame}


\begin{frame}{A terminologically heavy domain}
A few pointers for modellers:
\vfill
- Moghadas and Laskowski. \href{https://nccid.ca/wp-content/uploads/sites/2/2015/03/ReviewTermsFluWEB.pdf}{Review of terms used in modelling influenza infection}. NCCID 2014
\vfill
- Milwid et al. \href{https://doi.org/10.3389/fpubh.2016.00213}{Toward standardizing a lexicon of infectious disease modeling terms}. Frontiers in Public Health 2016
\end{frame}


\begin{frame}{Who}
- \defword{Epidemiology} typically used when dealing with humans, but sometimes also generically when an easy description is sought; e.g., plant disease epidemiology
\vfill
- \defword{Epizootic}: denoting or relating to a disease that is temporarily prevalent and widespread in an animal population
\vfill
- \defword{Panzootic} is like a pandemic for animals
\vfill
- \defword{One Health}: considers health of humans, animals and their environment (including plants)
\end{frame}


\begin{frame}
    \centering
    \includegraphics[height=\textheight]{FIGS/gr1_lrg.jpg}
% "https://doi.org/10.1016/S0140-6736(20)31027-8"
\end{frame}


\begin{frame}{Incidence \& Prevalence (when?)}
\defword{Incidence}: number of new cases in a population generated within a certain time period
\vfill
\defword{Prevalence}: number of cases of a disease at a single time point in a population
\vfill
$\implies$ $I(t)$ in an epidemiological model is \textbf{prevalence}, not \textbf{incidence}
\end{frame}

\begin{frame}{Exposition versus Exposed}
- Some bright bulb (not sure who) in days of yore: let's call \textbf{exposed} someone who has contracted the disease but is not yet showing symptoms ($\implies$ SEIR model)
\vfill
- "Real" epidemiologist: let's trace people who were exposed to the virus, i.e., people having come into contact with the virus (whether they have contracted the disease or not)
\vfill
- Interestingly, I have embarked on a quixotic quest to make people use $L$ instead of $E$, only to be told by real epidemiologists that they don't care \code{:)}
\end{frame}


\begin{frame}{The different stages of propagation}
        \includegraphics[width=\textwidth]{FIGS/Difference_between_outbreak,_endemic,_epidemic_and_pandemic-en.png}
\end{frame}
        


\begin{frame}{Epidemic curves}
- Used to record the occurrence of new cases as a function of time
\vfill
- When not too many cases, usually "individualised" (bar plots)
\vfill
- When number of cases is large, continuous curve
\end{frame}


\begin{frame}
    \includegraphics[width=\textwidth]{FIGS/41591_2020_1092_Fig1_HTML.png}
    %"https://doi.org/10.1038/s41591-020-1092-0"
\end{frame}


\begin{frame}
    \includegraphics[width=\textwidth]{FIGS/371_27_f1.jpeg}
    % "https://doi.org/10.1126/science.abf8832"
\end{frame}


\begin{frame}{Some terminology for ``where''}
\bbullet \defword{Epidemic}: diseases that are \emph{visited upon} a population
\vfill
\bbullet \defword{Pandemic}: (will revisit this later in the course) epidemic that has spread across a large region, e.g., multiple continents or worldwide
\vfill
\bbullet \defword{Endemic}: diseases that \emph{reside within} a population
\vfill
\bbullet We don't say ``panendemic''
\end{frame}


\begin{frame}{Where? \href{https://en.wikipedia.org/wiki/1854_Broad_Street_cholera_outbreak}{1854 cholera outbreak}}
    \begin{minipage}{0.5\textwidth}
    \includegraphics[width=\textwidth]{FIGS/Snow-cholera-map.jpg}
    \end{minipage}
    \begin{minipage}{0.45\textwidth}
        Cholera outbreak near Broad Street, London (UK)
        \vfill
        Studied by \href{https://en.wikipedia.org/wiki/John_Snow}{John Snow}

        \begin{quotation}
            I found that nearly all the deaths had taken place within a short distance of the [Broad Street] pump    
        \end{quotation}
            \end{minipage}
\end{frame}


\begin{frame}{\href{https://www.ncbi.nlm.nih.gov/books/NBK143061/}{WHO pandemic (influenza) phases}}
% <style>
%     .heatMap {
%         overflow:scroll;
%     }
%     .heatMap th {
%         background: grey;
%     }
%     .heatMap tr:nth-child(1) { background: green;}
%     .heatMap tr:nth-child(2) { background: green;}
%     .heatMap tr:nth-child(3) { background: yellow;}
%     .heatMap tr:nth-child(4) { background: yellow;}
%     .heatMap tr:nth-child(5) { background: orange;}
%     .heatMap tr:nth-child(6) { background: red;}
% </style>

% <div class="heatMap">

\begin{tabular}{ccp{6cm}}
Period & Phase & Description \\
\hline
\rowcolor{lgreen} Interpandemic & 1 & No animal influenza virus circulating among animals has been reported to cause infection in humans \\
\rowcolor{lgreen} & 2 & Animal influenza virus circulating in domesticated or wild animals known to have caused infection in humans and therefore considered a specific potential pandemic threat
\end{tabular}
\end{frame}

\begin{frame}{\href{https://www.ncbi.nlm.nih.gov/books/NBK143061/}{WHO pandemic (influenza) phases}}
\begin{tabular}{ccp{6cm}}
Period & Phase & Description \\
\hline 
\rowcolor{yellow} Pandemic alert & 3 & Animal or human-animal influenza reassortant virus has caused sporadic cases or small clusters of disease in people, but has not resulted in H2H transmission sufficient to sustain community-level outbreaks \\
\rowcolor{yellow} & 4 & Human-to-human transmission of an animal or human-animal influenza reassortant virus able to sustain community-level outbreaks has been verified 
\end{tabular}
\end{frame}

\begin{frame}{\href{https://www.ncbi.nlm.nih.gov/books/NBK143061/}{WHO pandemic (influenza) phases}}
\begin{tabular}{ccp{6cm}}
    Period & Phase & Description \\
    \hline 
\rowcolor{orange} Pandemic alert & 5 & Same identified virus has caused sustained community-level outbreaks in at least 2 countries in 1 WHO region \\
\rowcolor{lred} Pandemic & 6 & In addition to criteria in Phase 5, same virus has caused sustained community-level outbreaks in at least 1 other country in another WHO region
\end{tabular}
\end{frame}

\begin{frame}
    \includegraphics[width=\textwidth]{FIGS/1280px-World_Health_Organisation_regional_offices.png}
\end{frame}



%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
\subsection{Fighting against infections}

\begin{frame}{Fighting against infections}
\begin{quote}
    Epidemiological information is used to plan and evaluate \defword{strategies to prevent illness} and as a guide to the \defword{management of patients} in whom disease has already developed  
\end{quote}
\vfill
\bbullet Preventing illness
\begin{itemize}
    \item Prophylactic measures
    \item Vaccination
\end{itemize}
\vfill
\bbullet Managing illness
\begin{itemize}
    \item Prevention of further spread (e.g., in hospital) 
    \item Treatment
\end{itemize}
\end{frame}


\begin{frame}{Immunisation}
\bbullet Smallpox first disease for which it was known 
\vfill
\bbullet Mentioned in a 1549 Chinese book
\vfill
\bbullet China: powdered smallpox scabs blown up noses of the healthy; variolation-induced mortality not negligible (0.5-2\%) but lower than normal (20\%)
\vfill
\bbullet 1798:  Edward Jenner introduces safer inoculation with cowpox (vaccination)
\vfill
\bbullet 1880s: Pasteur extends vaccination to chicken cholera and anthrax in animals and human rabies
\vfill
At the time, \defword{herd immunity} was not understood so this was for personal protection
\end{frame}


\begin{frame}
<div style = "position: relative; top: -55%; padding-bottom:60px; font-size:40px">
Measles cases in the USA
</div>
\includegraphics[width=\textwidth]{FIGS/measles_US_1944_2019.png}
\end{frame}


%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
\section{Mathematical Epidemiology}

\begin{frame}{The domain is quite old ..}
.. but has only become a thing in recent years!
\end{frame}

\maxFrameImage{FIGS/math-epi-papers-to-1970.png}
\maxFrameImage{FIGS/math-epi-papers-since-1970.png}

%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
\subsection{The early years}
\begin{frame}{Daniel Bernoulli (1760)}
\begin{minipage}{0.5\textwidth}
    \includegraphics[width=\textwidth]{FIGS/Bernoulli-1760-first_page.jpg}
\end{minipage}
\begin{minipage}{0.47\textwidth}
\bbullet \href{https://gallica.bnf.fr/ark:/12148/bpt6k3558n/f220.item}{BNF scan} or \href{https://julien-arino.github.io/assets/pdf/Bernoulli-1760.pdf}{pdf}
\vskip1cm
\bbullet Probably the first epidemic model
\vskip1cm
\bbullet About petite vérole (smallpox) inoculation    
\end{minipage}
\end{frame}


\begin{frame}{Ross (early 1900)}
\begin{minipage}{0.5\textwidth}
    \includegraphics[width=\textwidth]{FIGS/RonaldRoss_WellcomeCollection.jpg}
\end{minipage}
\begin{minipage}{0.47\textwidth}
\bbullet On 20 August 1897, observed malaria parasites in the gut of a mosquito fed several days earlier on a malaria positive human
\vskip1cm
\bbullet Nobel Prize for Medicine 1902
\vskip1cm
\bbullet Started considering malaria eradication using mathematical models; for some history, read \href{https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3320609/pdf/ppat.1002588.pdf}{this 2012 paper}
\end{minipage}
\end{frame}


\begin{frame}{Kermack and McKendrick (1927+)}
\bbullet We spend a lot more time on this later
\vfill
\bbullet Groundbreaking set of papers starting in 1927
\vfill
\bbullet We will see one particular case, the most well known, but this is just the tip of the iceberg of their work
\end{frame}

\begin{frame}{Macdonald, Dietz and malaria}
\bbullet Read for instance \href{https://doi.org/10.1371/journal.ppat.1002588}{this paper}, which presents a history of the development of the so-called Ross-Macdonald model
\vfill
\bbullet Klaus Dietz also worked a lot on malaria
\end{frame}
    
    
\begin{frame}{Some activity later, but not much until 1990s}
\bbullet In recent years, explosion
\vfill
\bbullet Since the beginning of COVID-19: just nuts..
\end{frame}

\begin{frame}{Some landmarks in mathematical epidemiology (IMBO)}
\bbullet Macdonald. The epidemiology and control of malaria. 1957
\vfill
\bbullet Baroyan, Rvachev et al. Deterministic epidemic models for a territory with a transport network. Kibernetika, 1967
\vfill
\bbullet Hethcote \& Yorke. Gonorrhea Transmission Dynamics and Control. LNBM 56, 1984
\vfill
\bbullet Anderson \& May. Infectious diseases of humans: dynamics and control. 1991
\vfill
\bbullet Capasso. Mathematical Structures of Epidemic Systems. LNBM 97, 1993
\vfill
\bbullet Hethcote. The mathematics of infectious diseases. SIAM Review, 2000
\vfill
\bbullet van den Driessche \& Watmough. Reproduction numbers and sub-threshold endemic equilibria for compartmental models of disease transmission. MBS, 2002      
\end{frame}


%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
\subsection{Computational epidemiology}

\begin{frame}{A more recent trend}
\bbullet Some rare numerical work $\leq$ 1980s, mostly simulation of math models
\begin{itemize}
    \item Baroyan, Rvachev et al. \href{https://doi.org/10.2307/1426167}{Computer modelling of influenza epidemics for the whole country (USSR)}. \emph{Advances in Applied Probability} (1971) 
    \item Rvachev \& Longini. \href{https://doi.org/10.1016/0025-5564(85)90064-1}{A mathematical model for the global spread of influenza}. \emph{Mathematical Biosciences} (1986) 
    \item Flahault, Letrait et al. \href{https://doi.org/10.1002/sim.4780071107}{Modelling the 1985 influenza epidemic in France}. \emph{Statistics in Medicine} (1988)
\end{itemize}
\vfill
\bbullet More and more frequent now, to the point that some modelling studies are purely simulation-based
\end{frame}

\begin{frame}{Agent-based models (ABM)}
\bbullet Early in the life of these models, they were called IBM (individual-based models)
\vfill
\bbullet Over the years, a "philosophical" distinction has emerged:
\begin{itemize}
\item IBM are mathematical models that consider individuals as the units; e.g., DTMC, CTMC, branching processes, etc.
\item ABM are computational models whose study is, for the most part, only possible numerically
\end{itemize}
\end{frame}

\begin{frame}{Network models}
\bbullet Network models endow vertices with simple systems and couple them through graphs
\vfill
\bbullet Can be ABM, but some networks can also be studied analytically
\end{frame}

%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
\subsection{Use of data in mathematical epidemiology}

\begin{frame}{Has happened all along, undergoing a transformation}
\bbullet Epidemiology has long relied on data
\vfill
\bbullet Many developments in statistics originate there
\vfill
\bbullet Data has traditionally been better for chronic diseases than for infectious ones
\vfill
\bbullet Near-real-time surveillance of infectious diseases ongoing since the 1980s (e.g., Réseau Sentinelles)
\vfill
\bbullet SARS-CoV-1 saw the beginning of a move towards real-time emerging infectious disease data
\vfill
\bbullet With SARS-CoV-2, the system has really progressed a lot, both in terms of ``citizen science'' and governmental initiatives
\end{frame}



%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
\section{The Kermack-McKendrick SIR model without demography}

\begin{frame}{Paper series worth reading}
Model here is a particular case in
\begin{itemize}
  \item Kermack \& McKendrick. \href{https://doi.org/10.1098/rspa.1927.0118}{A contribution to the mathematical theory of epidemics} (1927)
\end{itemize}
\vfill
That paper was followed by a series of ``Contributions to the mathematical theory of epidemics.''
\begin{itemize}
  \item \href{https://doi.org/10.1098/rspa.1932.0171}{II. The problem of endemicity} (1932)
  \item \href{https://doi.org/10.1098/rspa.1933.0106}{III. Further studies of the problem of endemicity} (1933)
  \item \href{https://doi.org/10.1017/S0022172400034902}{IV. Analysis of experimental epidemics of the virus disease mouse ectromelia} (1937)
  \item \href{https://doi.org/10.1017/S0022172400011918}{V. Analysis of experimental epidemics of mouse-typhoid; a bacterial disease conferring incomplete immunity} (1939)
\end{itemize}
\end{frame}

\begin{frame}{What is the \emph{size} of an epidemic?}
\bbullet 
If we are interested in the possibility that an epidemic occurs
\begin{itemize}
  \item Does an epidemic peak always take place?
  \item If it does take place, what is its size?
\end{itemize}
\vfill
\bbullet If an epidemic traverses a population, is everyone affected/infected?
\end{frame}


%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
\subsection{The model}
\begin{frame}{The Kermack-McKendrick SIR model without demography}
\bbullet The period of time under consideration is sufficiently short that demography can be neglected (we also say the model has \emph{no vital dynamics})
\vfill
\bbullet Individuals are either \emph{susceptible} to the disease or \emph{infected} by (and \emph{infectious} with) the disease
\vfill
\bbullet After recovering or dying from the disease, individuals are \emph{removed} from the infectious compartment ($R$)
\vfill
\bbullet Incidence is of \defword{mass action} type and takes the form $\beta SI$
\end{frame}


\begin{frame}{The state variables}
We formulate the model as a system of \defword{differential equations}
\vfill
Differential equations: unknowns are \emph{functions} (instead of scalars, like in algebraic equations)
\vfill
At time $t\geq 0$ (we typically assume time starts at $t=0$, but could also consider $t\geq t_0>0$), the \defword{state variables}, in the current model, are the numbers of individuals who are
\begin{itemize}
\item susceptible to the disease: $S(t)$
\item infected and infectious with the disease: $I(t)$
\item removed from the infectious comparment: $R(t)$
\end{itemize}
\vfill
Often, we drop the dependence on $t$ if it is not explicitly required and write $S,I,R$
\end{frame}



\begin{frame}{Important -- Incidence functions}
Incidence is the rate at which new cases arise, the incidence function then describes how contacts lead to new infections
\vfill
If there are $S$ susceptible individuals and $I$ infectious individuals in the population, we use a function of the form
\[
f(S,I)
\]
The function can also explicitly depend on the total population $N$, i.e., $f(S,I,N)$
\vfill
We return to incidence functions in \href{no.se}{Lecture 06}
\vfill
For now, just know the most common incidence functions are
\begin{itemize}
\item \defword{mass action incidence} $f(S,I,N)=\beta SI$
\item \defword{standard} (or \defword{proportional}) \defword{incidence} $f(S,I,N)=\beta SI/N$
\end{itemize}
\end{frame}



\begin{frame}{The Kermack-McKendrick model}
This model is typically called the \defword{Kermack-McKendrick} (KMK) \defword{SIR model} 
  \begin{align*}
    \frac{d}{dt}S(t) &= -\beta S(t)I(t) \\
    \frac{d}{dt}I(t) &= \beta S(t)I(t)-\gamma I(t) \\
    \frac{d}{dt}R(t) &= \gamma I(t) 
    \end{align*}  
\vfill
\begin{center}
  \begin{tikzpicture}[scale=1.25, transform shape]
    \node [circle, fill=green!50, text=black] (S) {$S(t)$};
    \node [circle, right=1.5cm of S, fill=red!90, text=black] (I) {$I(t)$};
    \node [circle, right=1.5cm of I, fill=blue!90, text=black] (R) {$R(t)$};
    %% Flows
    \path [line, very thick] (S) to node [midway, above] (TextNode) {$\beta S(t)I(t)$} (I);
    \path [line, very thick] (I) to node [midway, above] (TextNode) {$\gamma I(t)$} (R);
  \end{tikzpicture}    
\end{center}
\end{frame}



\begin{frame}{The Kermack-McKendrick model}
As indicated, we often drop dependence on $t$ of the state variables; we also write $X':=dX(t)/dt$. So the KMK model is usually written
\vfill
\begin{subequations}\label{sys:KMK}
  \begin{align}
    S\pprime &= -\beta SI \label{sys:KMK_dS} \\
    I\pprime &= \beta SI-\gamma I \label{sys:KMK_dI} \\
    R\pprime &= \gamma I \label{sys:KMK_dR}
    \end{align}  
\end{subequations}
\vfill
\begin{center}
  \begin{tikzpicture}[scale=1.5, transform shape]
    \node [circle, fill=green!50, text=black] (S) {$S$};
    \node [circle, right=1cm of S, fill=red!90, text=black] (I) {$I$};
    \node [circle, right=1cm of I, fill=blue!90, text=black] (R) {$R$};
    %% Flows
    \path [line, very thick] (S) to node [midway, above] (TextNode) {$\beta SI$} (I);
    \path [line, very thick] (I) to node [midway, above] (TextNode) {$\gamma I$} (R);
  \end{tikzpicture}    
\end{center}
\end{frame}

%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
\subsection{Mathematical analysis}

\begin{frame}{Reduction of the model}
  3 compartments, but when considered in detail, we notice that \emph{removed} do not have a direct influence on the dynamics of $S$ or $I$, in the sense that $R$ does not appear in \eqref{sys:KMK_dS} or \eqref{sys:KMK_dI}
  \vfill
  Furthermore, the total population (including deceased who are also in $R$) $N=S+I+R$ satisfies
  \[
  N\pprime=(S+I+R)'=0
  \]
  Thus, $N$ is constant and 
  \begin{equation}\label{eq:constant_population}
    S(t)+I(t)+R(t)=N_0,\quad t\geq 0.
  \end{equation}
  so the dynamics of $R$ can be deduced from $R=N-(S+I)$.
  So we can consider
  \begin{subequations}\label{sys:KMK_2d}
    \begin{align}
      S\pprime &= -\beta SI \label{sys:KMK_2d_dS}\\
      I\pprime &= \beta SI-\gamma I  \label{sys:KMK_2d_dI}
      \end{align}
    \end{subequations}
\end{frame}

\begin{frame}{Equilibria}
  Let us consider the equilibria of
  \begin{subequations}
    \begin{align}
      S\pprime &= -\beta SI 
      \tag{\ref{sys:KMK_2d_dS}} \\
      I\pprime &= (\beta S-\gamma)I  
      \tag{\ref{sys:KMK_2d_dI}}
    \end{align}
  \end{subequations}
\vfill
  From \eqref{sys:KMK_2d_dI}
  \begin{itemize}
    \item either $S^\star=\gamma/\beta$ 
    \item or $I^\star=0$
  \end{itemize}
  \vfill
  Substitute into \eqref{sys:KMK_2d_dS}
  \begin{itemize}
    \item in the first case, $(S^\star,I^\star)=(\gamma/\beta,0)$ 
    \item in the second case, any $S^\star\geq 0$ is an EP
  \end{itemize}
  \vfill
  The second case is an \emph{issue}: the usual linearisation does not work when there is a \emph{continuum} of equilibria as the EP are not \emph{isolated}
\end{frame}

\begin{frame}{The DFE in KMK is ``weird''}
\begin{proposition}\label{prop:EP_KMK}
The Kermack-McKendrick model SIR model \eqref{sys:KMK} has the continuum of equilibria
\begin{equation}
\label{eq:DFE_KMK}
    E_0^\text{KMK}:=\left\{
    (S^\star,I^\star,R^\star)=(S_\infty,0,N_0-S_\infty),\quad S_\infty\in[0,N_0]
    \right\}
\end{equation}
\end{proposition}
\end{frame}

\begin{frame}{Proof}
Let us consider \eqref{sys:KMK} and start with $I=I^\star=0$.
Substitute this value into \eqref{sys:KMK_dS} at equilibrium, giving $0 = -\gamma S^\star I^\star(=0)$, meaning that any value of $S^\star$ satisfies this relation. From the conservation of the total population \eqref{eq:constant_population}, the equilibrium $E_0^\text{KMK}$ takes the form given by \eqref{eq:DFE_KMK}
\vfill
Now consider $S=S^\star=\gamma/\beta$. Substituting this value into \eqref{sys:KMK_dS} at equilibrium gives $0 = -\gamma I^\star$, from which it follows that $I^\star=0$, and, using the conservation of total population \eqref{eq:constant_population},
\begin{equation}\label{eq:DFE_KMK_tmp}
    (S^\star,I^\star,R^\star)=\left(
    \frac{\gamma}{\beta},0,N_0-\frac{\gamma}{\beta}
    \right)
\end{equation}
is an equilibrium of \eqref{sys:KMK}. 
The equilibrium \eqref{eq:DFE_KMK_tmp} is biologically relevant only when $N_0-\gamma/\beta\geq 0$.
Note that \eqref{eq:DFE_KMK} includes \eqref{eq:DFE_KMK_tmp} when the latter is biologically relevant
\end{frame}

\begin{frame}
Adapting slightly the definitions in \cite{HirschSmale1974}, consider the ordinary differential equation
\begin{equation}\label{eq:ODE}
    x' = f(x)
\end{equation}
where $x(t)\in W$ and $f:W\to E$ is a function such that solutions to \eqref{eq:ODE} exist uniquely, e.g., a $C^1$ function, from an open set $W$ of the vector space $E$ into $E$
\vfill
Denote $x(t,x_0)$ the solution to \eqref{eq:ODE} through the initial value $x(t_0)=x_0$
\end{frame}

\begin{frame}
A point $x^\star\in W$ is an \defword{equilibrium} if $f(x^\star)=0$
\vfill
\begin{definition}[Locally stable equilibrium]\label{def:LS_EP}
An equilibrium point $x^\star$ of \eqref{eq:ODE} is \defword{locally stable} (LS) if for every neighbourhood $\mathcal{N}(x^\star)$ of $x^\star$ in $W$, there is a neighbourhood $\mathcal{N}_1\subseteq\mathcal{N}(x^\star)$ of $x^\star$ such that every solution $x(t,x_0)$ with $x_0\in\mathcal{N}_1$ is defined and in $\mathcal{N}(x^\star)$ for all $t>t_0$
\end{definition}
\vfill
\begin{definition}[Locally asymptotically stable equilibrium]
If $\mathcal{N}_1$ can be chosen so that in addition to the properties in Definition~\ref{def:LS_EP}, $\lim_{t\to\infty}x(t,x_0)=x^\star$ for all $x_0\in\mathcal{N}_1$, then $x^\star$ is \defword{locally asymptotically stable} (LAS)
\end{definition}
\end{frame}

\begin{frame}
DFE \eqref{eq:DFE_KMK} of \eqref{sys:KMK} are not \defword{isolated}: any (open) neighbourhood of an equilibrium contains infinitely many other equilibria
\vfill
    \begin{tikzpicture}
    \coordinate (SN) at (4,0);
    \coordinate (RN) at (0,4);
    \coordinate (xs) at (1.5,2.5);
    % The region
    \fill[gray!10] (0,4) -| (4,4) -| (4,0) -| (0,0) -- cycle;
    \draw[gray!40, thick]  (0,0) -- (4,0) -- (4,4) -- (0,4) -- cycle;
    % axis, on the top
    \draw[->] (0,0) -- (5.25,0) node[below left] {$S$};
    \draw[->] (0,0) -- (0,5) node[below left] {$R$};
    % The line of EP
    \draw[thin] (SN) -- (RN) node[pos=0.3,right] {$S+R=N_0$};
    \draw[line width=2] (1,3) -- (2,2);
    \shade[ball color = gray!40, opacity = 0.4] (xs) circle (0.72);
    % Intersections on S and R axes
    \draw (SN) circle (0.1cm) node[below] {$S=N_0$};
    \shade[ball color = blue, opacity = 1] (SN) circle (0.1cm);
    \draw (RN) circle (0.1cm) node[left] {$R=N_0$};
    \shade[ball color = blue, opacity = 1] (RN) circle (0.1cm);
    % The equilibrium
    \draw (xs) circle (0.1cm) node[above right] {$x^\star$};
    \shade[ball color = red, opacity = 1] (xs) circle (0.1cm);
    \end{tikzpicture} 
    \vfill
Neighbourhood $\N(x^\star)$ of $x^\star\in E_0^\text{KMK}$ lying on the $S-R$ plane (the neighbourhood extends above and below the $S-R$ plane in the $I$ direction, not shown here). 
The thin line is $E_0^\text{KMK}$, the thick line is $E_0^\text{KMK}\cap\N(x^\star)$
\end{frame}

\begin{frame}
\begin{proposition}
Consider a disease-free equilibrium $x^\star\in E_0^\text{KMK}$ of \eqref{sys:KMK}. Then $x^\star$ is LS but not LAS  
\end{proposition}
\vfill
This means in particular that considering the Jacobian of \eqref{sys:KMK} at the DFE \textbf{makes no sense}!
\end{frame}

\begin{frame}{Proof}
Let $x_1^\star\in E_0^\text{KMK}$ be an equilibrium of \eqref{sys:KMK}.
Consider $\S_\mathcal{N}(x_1^\star)\subset E_0^\text{KMK}$, open subset of $E_0^\text{KMK}$ containing $x_1^\star$.
Now take some $x_2^\star\in\S_\mathcal{N}(x_1^\star)$. Since $x_2^\star\in\S_\mathcal{N}(x_1^\star)\subset E_0^\text{KMK}$, $x_2^\star$ is an equilibrium of \eqref{sys:KMK} and thus $x(t,x_2^\star)=x_2^\star\in\S_\mathcal{N}(x_1^\star)$ for all $t\geq t_0$.
As a consequence, $x_1^\star$ is locally stable
\vfill
$\Rightarrow$ any open neighbourhood $\mathcal{N}(x_1^\star)$ contains $\S_\mathcal{N}=\mathcal{N}(x_1^\star)\cap E_0^\text{KMK}$
\vfill
Consider, then, some $x_2^\star\in\S_\mathcal{N}$.
Since $x_2^\star\in\S_\mathcal{N}$, $x_2^\star$ is an equilibrium and as a consequence, $\lim_{t\to\infty}x(t,x_2^\star)=x_2^\star$.
Therefore, any open neighbourhood of $x_1^\star$ contains points $x_0$ not such that $\lim_{t\to\infty}x(t,x_0)=x_1^\star$ $\implies$ $x_1^\star$ is LS but not LAS
\end{frame}

\begin{frame}{The next generation matrix method in this context}
Consider the method in \cite{VdDWatmough2002}
\vfill
To construct $\R_0$, they require \emph{local stability}
\vfill
Theorem 2 in \cite{VdDWatmough2002} pertaining to LAS, on the other hand, has one assumption (assumption A5) that the DFE be \emph{locally asymptotically stable}, with the assumption that all eigenvalues of the linearisation near a disease-free equilibrium have negative real parts
\vfill
Clearly, this cannot be true with \eqref{sys:KMK}
\end{frame}


\begin{frame}{Another approach -- Study $dI/dS$}
  \begin{align}
  S\pprime &= -\beta SI \tag{\ref{sys:KMK_2d_dS}}\\
  I\pprime &= \beta SI-\gamma I  \tag{\ref{sys:KMK_2d_dI}}
  \end{align}
  \vfill
  What is the dynamics of $dI/dS$? 
  \begin{equation}
    \label{eq:KMK_dI_over_dS}
    \frac{dI}{dS}
    =\frac{dI}{dt}\frac{dt}{dS}
    =\frac{I'}{S'}
    =\frac{\beta SI-\gamma I}{-\beta SI}
    =\frac{\gamma}{\beta S}-1
  \end{equation}
 provided $S\neq 0$
  \vfill
  \textbf{Note --} Recall that $S$ and $I$ are $S(t)$ and $I(t)$.. \eqref{eq:KMK_dI_over_dS} thus describes the relation between $S$ and $I$ over solutions to the original ODE \eqref{sys:KMK_2d}
\end{frame}


\begin{frame}{}
  Integrate $\eqref{eq:KMK_dI_over_dS}$ and obtain trajectories in state space
  $$
  I(S)=\frac\gamma\beta \ln S-S+C
  $$
  with $C\in\IR$
  \vfill
  IC $I(S_0)=I_0$ $\Rightarrow$ $C=S_0+I_0-\dfrac \gamma\beta \ln S_0$ and the solution to \eqref{sys:KMK} is, as a function of $S$
  \begin{align*}
  I(S)&=S_0+I_0-S+\frac\gamma\beta \ln \frac S{S_0} \\
  R(S)&=N-S-I(S)=R_0-\frac\gamma\beta \ln \frac S{S_0}
  \end{align*}
  (since $N_0=S_0+I_0+R_0$)
\end{frame}


<<KMK_SI_plane,eval=TRUE,echo=FALSE,fig=TRUE,width=8,height=6,include=FALSE>>=
# Plot the trajectories of the KMK SIR system in the SI-plane
# In this plot, the total population N is normalised to 1
gamma = 1/5
beta = 0.5
# Store the values of S and I in lists
S = list()
I = list()
i = 1
# Solutions starting on the S axis
for (S0 in seq(0.6, 1, 0.1)) {
  I0 = 0
  S[[i]] = seq(0.001, S0, 0.001)
  I[[i]] = S0+I0-S[[i]]+gamma/beta*log(S[[i]]/S0)
  i = i+1
}
# Solutions starting on the S+I=1 line
for (S0 in seq(1, 0.05, -0.1)) {
  I0 = 1-S0
  S[[i]] = seq(0.001, S0, 0.001)
  I[[i]] = S0+I0-S[[i]]+gamma/beta*log(S[[i]]/S0)
  i = i+1
}
# S+I=1 line
S[[i]] = seq(0, 1, 0.001)
I[[i]] = 1-S[[i]]
# Plot (and save) the result
#png("../FIGS/KMK_planar_trajectories.png", width = 1000, height = 600)
if (plot_blackBG) {
  par(bg = 'black', fg = 'white') # set background to black, foreground white
  colour = "white"
} else {
  colour = "black"
}
for (i in 1:length(S)) {
  if (i == 1) {
    plot(S[[i]], I[[i]],
         type = "l", lwd = 3,
         col = ifelse((I[[i]][length(I[[i]])] < max(I[[i]])), "red", colour),
         xlim = c(0,1), ylim = c(0,1),
         xaxs = "i", yaxs = "i",
         xlab = "S", ylab = "I",
         col.axis = colour, cex.axis = 2,
         col.lab = colour, cex.lab = 2,
         bty = "n")
    points(S[[i]][length(S[[i]])], I[[i]][length(I[[i]])],
          pch = 19, cex = 3, 
          col = ifelse((I[[i]][length(I[[i]])] < max(I[[i]])), "red", colour))
  } else if (i<length(S)) {
    lines(S[[i]], I[[i]], 
          col = ifelse((I[[i]][length(I[[i]])] < max(I[[i]])), "red", colour),
          lwd = 3)
    points(S[[i]][length(S[[i]])], I[[i]][length(I[[i]])],
           pch = 19, cex = 3, 
           col = ifelse((I[[i]][length(I[[i]])] < max(I[[i]])), "red", colour))
  } else {
    lines(S[[i]], I[[i]])
  }
}
@

\begin{frame}
Trajectories of \eqref{sys:KMK_2d} in $(S,I)$-space, normalised, with IC $(S_0,1-S_0)$ and $\beta/\gamma=2.5$
\vfill
\begin{center}
\includegraphics[width=\textwidth]{FIGS/lecture-01-KMK_SI_plane}
\end{center}
\end{frame}



\begin{frame}{}
  Let us study
  $$
  I(S)=S_0+I_0-S+\frac\gamma\beta \ln \frac S{S_0} 
  $$
  We have
  $$
  \frac{d}{dS}I(S) = \frac{\gamma}{\beta S}-1
  $$
  So, in the previous curves, the max of $I(S)$ happens when $S=\gamma/\beta$ ($S=0.4$ in the example)
  \vfill
  At that point,
  $$
  I(S) = I_0+\left(
    1-\frac{1}{\R_0} - \frac{\ln(\R_0)}{\R_0}
  \right)S_0
  $$
\end{frame}


\begin{frame}{}
  \begin{theorem}[Epidemic or no epidemic?]
    Let $(S(t),I(t))$ be a solution to \eqref{sys:KMK_2d} and $\R_0$ defined by
    \begin{equation}\label{eq:R0_KMK}
    \R_0=\frac{\beta}{\gamma}S_0
    \end{equation}
    \vfill
    \begin{itemize}
      \item If $\R_0\leq 1$, then $I(t)\searrow 0$ when $t\to\infty$ 
      \item If $\R_0>1$, then $I(t)$ first reaches a maximum 
      \begin{equation}\label{eq:max_I}
        I_0+\left(
      1-\frac{1}{\R_0} - \frac{\ln(\R_0)}{\R_0}
      \right)S_0
      \end{equation}
      then goes to 0 as $t\to\infty$  
    \end{itemize}    
  \end{theorem}
\end{frame}

<<eval=TRUE,echo=FALSE>>=
library(deSolve)
rhs_SIR_KMK <- function(t, x, p) {
  with(as.list(c(x, p)), {
    dS = - beta * S * I
    dI = beta * S * I - gamma * I
    dR = gamma * I
    return(list(c(dS, dI, dR)))
  })
}
# Initial condition for S (to compute R_0)
S0 = 1000
gamma = 1/14
# Set beta so that R_0 = 1.5
beta = 1.5 * gamma / S0 
params = list(gamma = gamma, beta = beta)
IC = c(S = S0, I = 1, R = 0)
times = seq(0, 365, 1)
sol_KMK <- ode(IC, times, rhs_SIR_KMK, params)  
@

\begin{frame}[fragile]{}
\begin{lstlisting}
rhs_SIR_KMK <- function(t, x, p) {
  with(as.list(c(x, p)), {
    dS = - beta * S * I
    dI = beta * S * I - gamma * I
    dR = gamma * I
    return(list(c(dS, dI, dR)))
  })
}
# Initial condition for S (to compute R_0)
S0 = 1000
gamma = 1/14
# Set beta so that R_0 = 1.5
beta = 1.5 * gamma / S0 
params = list(gamma = gamma, beta = beta)
IC = c(S = S0, I = 1, R = 0)
times = seq(0, 365, 1)
sol_KMK <- ode(IC, times, rhs_SIR_KMK, params)  
\end{lstlisting}
\end{frame}

<<KMK_R0eq1dot5,eval=TRUE,echo=FALSE,fig=TRUE,width=8,height=5,include=FALSE>>=
library(latex2exp)
plot(sol_KMK[, "time"], sol_KMK[, "I"], 
     type = "l", lwd = 2,
     main = TeX("Kermack-McKendrick SIR, $R_0=1.5$"),
     xlab = "Time (days)", ylab = "Prevalence")
@

\begin{frame}[fragile]{}
\begin{lstlisting}
plot(sol_KMK[, "time"], sol_KMK[, "I"], type = "l",
main = TeX("Kermack-McKendrick SIR, $R_0=1.5$"),
xlab = "Time (days)", ylab = "Prevalence")
\end{lstlisting}
\begin{center}
\includegraphics[width=\textwidth]{FIGS/lecture-01-KMK_R0eq1dot5}
\end{center}
\end{frame}


\begin{frame}{The basic reproduction number $\R_0$}
\bbullet Indicator often used in epidemiology. Verbally
\begin{quote}
  average number of secondary cases of infection produced when a single infectious individual is introduced in a wholly susceptible population
\end{quote}
\vfill
\bbullet If $\R_0<1$, then each infectious individual infects on average less than 1 person and the epidemic is quite likely to go extinct 
\vfill
\bbullet If $R_0>1$, then each infectious individual infects on average more than 1 person and an epidemic is quite likely to occur
\end{frame}

\begin{frame}{A few sample values of $\R_0$}
  $\R_0$ can be estimated from data
  \vfill
  \begin{center}
  \begin{tabular}{llcc}
  \hline 
  Infection & Location & Period & $\R_0$ \\
  \hline
  Measles & Cirencester, England & 1947-50 & 13-14 \\
  & England and Wales & 1950-68 & 16-18 \\
  & Kansas, USA & 1918-21 & 5-6 \\
  & Ontario, Canada & 1912-3 & 11-12 \\
  & Willesden, England & 1912-3 & 11-12 \\
  & Ghana & 1960-8 & 14-15 \\
  & East Nigeria & 1960-8 & 16-17 \\
  \end{tabular}
  \end{center}
\end{frame}
    

%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%
\subsection{The final size of an epidemic}

\begin{frame}{Final size of an epidemic}
  For a nonnegative valued integrable function $w(t)$, denote
  $$
  w_0=w(0),\qquad  w_\infty = \lim_{t\to\infty}w(t),\qquad\hat w = \int_0^\infty w(t)\ dt
  $$
  \vfill
  In the subsystem
  \begin{align}
  S' &= -\beta SI \tag{\ref{sys:KMK_2d_dS}} \\
  I' &= \beta SI-\gamma I \tag{\ref{sys:KMK_2d_dI}} 
  \end{align}
  compute the sum of \eqref{sys:KMK_2d_dS} and \eqref{sys:KMK_2d_dI}, making sure to show time dependence $$
  \frac{d}{dt}(S(t)+I(t))=-\gamma I(t)
  $$
\end{frame}


\begin{frame}{}
  Integrate from 0 to $\infty$:
  $$
  \int_0^\infty\frac{d}{dt}(S(t)+I(t))\ dt=-\int_0^\infty\gamma I(t)dt 
  $$
  The left hand side gives
  $$
  \int_0^\infty\frac{d}{dt}(S(t)+I(t))\ dt
  = S_\infty+I_\infty-S_0-I_0 = S_\infty-S_0-I_0
  $$
  since $I_\infty=0$
  \vfill
  The right hand side takes the form
  $$
  -\int_0^\infty\gamma I(t)dt = -\gamma\int_0^\infty I(t)dt = -\gamma \hat I
  $$
  We thus have
  \begin{equation}
  \label{eq:KMK_final_size_step1}
  S_\infty-S_0-I_0 = -\gamma\hat I
  \end{equation}
\end{frame}



\begin{frame}{}
  Now consider \eqref{sys:KMK_2d_dS}:
  $$
  S' = -\beta SI
  $$
  Divide both sides by $S$:
  $$
  \frac{S'(t)}{S(t)} = -\beta I(t)
  $$
  Integrate from 0 to $\infty$:
  \begin{equation}
  \label{eq:KMK_final_size_step2}
  \ln S_\infty-\ln S_0 = -\beta \hat I
  \end{equation}
  Express \eqref{eq:KMK_final_size_step1} and \eqref{eq:KMK_final_size_step2} in terms of $-\hat I$ and equate
  $$
  \frac{\ln S_\infty-\ln S_0}{\beta}
  =
  \frac{S_\infty-S_0-I_0}{\gamma}
  $$
  Thus we have
  \begin{equation}
  \label{eq:final_size}
  (\ln S_0-\ln S_\infty)S_0 = (S_0-S_\infty)\R_0+I_0\R_0
  \end{equation}
\end{frame}



\begin{frame}{}
\begin{theorem}[Final size relation]
  Let $(S(t),I(t))$ be a solution to \eqref{sys:KMK_2d} and $\R_0$ defined by \eqref{eq:R0_KMK}
  \vskip0.5cm
  The number $S(t)$ of susceptible individuals is a nonincreasing function and its limit $S_\infty$ is the only solution in $(0,S_0)$ of the transcendental equation
  \begin{equation}\tag{\ref{eq:final_size}}
  (\ln S_0-\ln S_\infty)S_0 = (S_0-S_\infty)\R_0+I_0\R_0
  \end{equation}
\end{theorem}
\end{frame}



\begin{frame}{The (transcendantal) final size equation}
  Rewrite the final size equation
  \begin{equation}
    \tag{\ref{eq:final_size}}
  (\ln S_0-\ln S_\infty)S_0 = (S_0-S_\infty)\R_0+I_0\R_0
  \end{equation}
  as
  \begin{equation}
  \label{eq:final_size_2}
  T(S_\infty) =(\ln S_0-\ln S_\infty)S_0
  - (S_0-S_\infty)\R_0 -I_0\R_0
\end{equation}
\vfill
Thus, we seek the zeros of the function $T(S_\infty)$
\end{frame}



\begin{frame}{}
  We seek $S_\infty$ in $(0,S_0]$ s.t. $T(S_\infty)=0$, with
  \begin{equation}\tag{\ref{eq:final_size_2}}
    T(S_\infty) =(\ln S_0-\ln S_\infty)S_0
    - (S_0-S_\infty)\R_0 -I_0\R_0      
  \end{equation}
  \vfill
  Note to begin that 
  $$
  \lim_{S_\infty\to 0}T(S_\infty)=\lim_{S_\infty\to 0}-S_0\ln(S_\infty)=\infty
  $$
  \vfill
  Differentiating $T$ with respect to $S_\infty$, we get 
  $$
  T'(S_\infty)=\R_0-S_0/S_\infty
  $$ 
  \vfill
  When $S_\infty\to 0$, $\R_0-S_0/S_\infty<0$, so $T$ decreases to $S_\infty=S_0/\R_0$
  \vfill
  So if $\R_0\leq 1$, the function $T$ is decreasing on $(0,S_0)$, while it has a minimum if $\R_0>1$
\end{frame}



\begin{frame}{Case $\R_0\leq 1$}
  \begin{equation}\tag{\ref{eq:final_size_2}}
    T(S_\infty) =(\ln S_0-\ln S_\infty)S_0
    - (S_0-S_\infty)\R_0 -I_0\R_0      
  \end{equation}
  \vfill
  \bbullet We have seen that $T$ decreases on $(0,S_0]$
  \vfill
  \bbullet Also, $T(S_0)=-I_0\R_0<0$ ($I_0=0$ is trivial and not considered)
  \vfill
  \bbullet $T$ is continuous
  \vfill
  $\implies$ there exists a unique $S_\infty\in (0,S_0]$ s.t. $T(S_\infty)=0$
\end{frame}


\begin{frame}{Case $\R_0> 1$}
  \begin{equation}\tag{\ref{eq:final_size_2}}
    T(S_\infty) =(\ln S_0-\ln S_\infty)S_0
    - (S_0-S_\infty)\R_0 -I_0\R_0      
  \end{equation}
  \vfill
  \bbullet We have seen that $T$ decreases on $(0,S_0/\R_0]$
  \vfill
  \bbullet For $S_\infty\in[S_0/\R_0]$, $T'>0$
  \vfill
  \bbullet As before, $T(S_\infty)=-I_0\R_0$
  \vfill
  \bbullet $T$ is continuous
  \vfill
  $\implies$ there exists a unique $S_\infty\in (0,S_0]$ s.t. $T(S_\infty)=0$. More precisely, in this case, $S_\infty\in(0,S_0/\R_0)$
\end{frame}

<<eval=TRUE,echo=FALSE>>=
final_size_eq = function(S_inf, S0 = 999, I0 = 1, R_0 = 2.5) {
  OUT = S0*(log(S0)-log(S_inf)) - (S0+I0-S_inf)*R_0
  return(OUT)
}
final_size = function(L) {
  with(as.list(L), {
  S_inf = uniroot(f = function(x) final_size_eq(S_inf = x, 
                                                S0 = S0, I0 = I0, 
                                                R_0 = R_0),
                  interval = c(0.05, S0))
  return(S_inf$root)
  })
}
@


\begin{frame}[fragile]{}
We solve numerically. We need a function
\begin{lstlisting}  
final_size_eq = function(S_inf, S0 = 999, I0 = 1, R_0 = 2.5) {
  OUT = S0*(log(S0)-log(S_inf)) - (S0+I0-S_inf)*R_0
  return(OUT)
}
\end{lstlisting}
and solve easily using \code{uniroot}, here with the values by default that we have set for the function
\begin{lstlisting}
uniroot(f = final_size_eq, interval = c(0.05, 999))
$root
[1] 106.8819
$f.root
[1] -2.649285e-07
$iter
[1] 10
$init.it
[1] NA
$estim.prec
[1] 6.103516e-05
\end{lstlisting}
\end{frame}


\begin{frame}[fragile]{}
To use something else than the default values, e.g.,
\vfill
\begin{lstlisting}  
N0 = 1000
I0 = 1
S0 = N0-I0
R_0 = 2.4
uniroot(
  f = function(x) 
    final_size_eq(S_inf = x, 
                  S0 = S0, I0 = I0, 
                  R_0 = R_0),
  interval = c(0.05, S0))
\end{lstlisting}
\end{frame}

\begin{frame}[fragile]{A function to use this..}
\begin{lstlisting}
final_size = function(L) {
  with(as.list(L), {
  S_inf = uniroot(f = function(x) final_size_eq(S_inf = x, 
                                                S0 = S0, I0 = I0, 
                                                R_0 = R_0),
                  interval = c(0.05, S0))
  return(S_inf$root)
  })
}
\end{lstlisting}
\end{frame}

\begin{frame}[fragile]{A figure with all the information}
\begin{lstlisting}
S = seq(0.1, S0, by = 0.1)
fs = final_size_eq(S, S0 = S0, I0 = I0, R_0 = R_0)
S_inf = uniroot(f = function(x) final_size_eq(S_inf = x, 
                                              S0 = S0, I0 = I0, 
                                              R_0 = R_0),
                interval = c(0.05, S0))
plot(S, fs, type = "l", ylab = "Value of equation (10)")
abline(h = 0)
points(x = S_inf$root, y = 0, pch = 19)
text(x = S_inf$root, y = 0, labels = "S_inf", adj = c(-0.25,-1))    
\end{lstlisting}
\end{frame}

<<KMK_final_size_0p8,eval=TRUE,echo=FALSE,fig=TRUE,width=8,height=5,include=FALSE>>=
N0 = 1000
I0 = 1
S0 = N0-I0
R_0 = 0.8
S = seq(0.1, S0, by = 0.1)
fs = final_size_eq(S, S0 = S0, I0 = I0, R_0 = R_0)
S_inf = uniroot(f = function(x) final_size_eq(S_inf = x, 
                                              S0 = S0, I0 = I0, 
                                              R_0 = R_0),
                interval = c(0.05, S0))
plot(S, fs, type = "l", ylab = "Value of equation (10)")
abline(h = 0)
points(x = S_inf$root, y = 0, pch = 19)
text(x = S_inf$root, y = 0, labels = "S_inf", adj = c(-0.25,-1))    
@


\begin{frame}{$\R_0=0.8$}
\begin{center}
  \includegraphics[width=\textwidth]{FIGS/lecture-01-KMK_final_size_0p8}
\end{center}
\end{frame}


<<KMK_final_size_2p5,eval=TRUE,echo=FALSE,fig=TRUE,width=8,height=5,include=FALSE>>=
N0 = 1000
I0 = 1
S0 = N0-I0
R_0 = 2.5
S = seq(0.1, S0, by = 0.1)
fs = final_size_eq(S, S0 = S0, I0 = I0, R_0 = R_0)
S_inf = uniroot(f = function(x) final_size_eq(S_inf = x, 
                                              S0 = S0, I0 = I0, 
                                              R_0 = R_0),
                interval = c(0.05, S0))
plot(S, fs, type = "l", ylab = "Value of equation (10)")
abline(h = 0)
points(x = S_inf$root, y = 0, pch = 19)
text(x = S_inf$root, y = 0, labels = "S_inf", adj = c(-0.25,-1))    
@


\begin{frame}{$\R_0=2.4$}
  \begin{center}
    \includegraphics[width=\textwidth]{FIGS/lecture-01-KMK_final_size_2p5}
  \end{center}
\end{frame}

<<KMK_attack_rate,eval=TRUE,echo=FALSE,fig=TRUE,width=8,height=5,include=FALSE>>=
library(lattice)
library(viridis)
library(latex2exp)
values = expand.grid(
  R_0 = seq(0.01, 3, by = 0.01),
  I0 = seq(1, 100, 1)
)
values$S0 = N0-values$I0
L = split(values, 1:nrow(values))
values$S_inf = sapply(X = L, FUN = final_size)
values$final_size = values$S0-values$S_inf+values$I0
values$attack_rate = (values$final_size / N0)*100

p = levelplot(attack_rate ~ R_0*I0, data = values, 
              xlab = TeX("$R_0$"), ylab = "I(0)",
              col.regions = viridis(100))
print(p)
@

\begin{frame}[fragile]{A little nicer}
\begin{lstlisting}
values = expand.grid(
  R_0 = seq(0.01, 3, by = 0.01),
  I0 = seq(1, 100, 1)
)
values$S0 = N0-values$I0
L = split(values, 1:nrow(values))
values$S_inf = sapply(X = L, FUN = final_size)
values$final_size = values$S0-values$S_inf+values$I0
values$attack_rate = (values$final_size / N0)*100

p = levelplot(attack_rate ~ R_0*I0, data = values, 
              xlab = TeX("$R_0$"), ylab = "I(0)",
              col.regions = viridis(100))
print(p)
\end{lstlisting}
(requires \code{lattice}, \code{viridis} and \code{latex2exp} librairies)
\end{frame}


\begin{frame}{Attack rate (in \%)}
  \begin{center}
    \includegraphics[width=\textwidth]{FIGS/lecture-01-KMK_attack_rate}
  \end{center}
\end{frame}


%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%
\subsection{Herd immunity}

\begin{frame}{The simplest vaccination model}
To implement vaccination in KMK, assume that vaccination reduces the number of susceptibles
\vfill
Let total population be $N$ with $S_0$ initially susceptible
\vfill
Vaccinate a fraction $p\in[0,1]$ of susceptible individuals
\vfill
Original IC (for simplicity, $R(0)=0$)
\begin{equation}\label{eq:IC_KMK_novacc}
IC: (S(0),I(0),R(0)) = (S_0,I_0,0)
\end{equation}
Post-vaccination IC 
\begin{equation}\label{eq:IC_KMK_vacc}
IC: (S(0),I(0),R(0)) = ((1-p)S_0,I_0,pS_0)
\end{equation}
\end{frame}


\begin{frame}{Vaccination reproduction number}
  Without vaccination
  \begin{equation}\tag{\ref{eq:R0_KMK}}
    \R_0=\frac{\beta}{\gamma}S_0
  \end{equation}
  \vfill
  With vaccination, denoting $\R_{\text{v}}$ the reproduction number,
  \begin{equation}
    \R_{\text{v}} = \frac{\beta}{\gamma}(1-p)S_0
  \end{equation}
  \vfill
  Since $p\in[0,1]$, $\R_{\text{v}}\leq\R_0$
\end{frame}


\begin{frame}{Herd immunity}
  Therefore
  \begin{itemize}
    \item $\R_{\text{v}}<\R_0$ if $p>0$ 
    \item To control the disease, $\R_{\text{v}}$ must take a value less than 1
  \end{itemize}
  \vfill
To make $\R_{\text{v}}$ less than 1
  \begin{equation}\label{eq:herd_immunity}
    \R_{\text{v}}<1 \iff p> 1-\frac{1}{\R_0}
  \end{equation}
  \vfill
  By vaccinating a fraction $p>1-1/\R_0$ of the susceptible population, we thus are in a situation where an epidemic peak is precluded (or, at the very least, the final size is reduced)
  \vfill
  This is \defword{herd immunity}
\end{frame}







%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
\section{The endemic SIRS model with demography}

%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
\subsection{The model(s)}
\begin{frame}{Two potential variations on the Kermack-McKendrick model}
\bbullet Add \emph{vital dynamics}, i.e., consider demographic processes
\vfill
\bbullet Individuals do not die from the disease; after recovering, individuals are \emph{immune} from infection for some time
\vfill
\bbullet We can of course combine both!
\end{frame}

\begin{frame}{Potential variations}
\def\skip{*1.5}
\def\yskip{*-2.5}
\begin{center}
  \begin{tikzpicture}[scale=1.25, transform shape]
    %% Regular nodes
    \node [circle, fill=green!50, text=black] at (0\skip,0) (S1) {$S$};
    \node [circle, fill=red!90, text=black] at (1\skip,0) (I1) {$I$};
    \node [circle, fill=blue!90, text=black] at (2\skip,0) (R1) {$R$};
    %% Fake nodes for arrows
    \node [left=1cm of S1] (birth1) {};
    \node [below=0.5cm of S1] (dS1) {};
    \node [below=0.5cm of I1] (dI1) {};
    \node [below=0.5cm of R1] (dR1) {};
    %% Flows
    \path [line, very thick] (birth1) to node [midway, above] (TextNode) {$b(N)$} (S1);
    \path [line, very thick] (S1) to node [midway, right] (TextNode) {$dS$} (dS1);
    \path [line, very thick] (I1) to node [midway, right] (TextNode) {$dI$} (dI1);
    \path [line, very thick] (R1) to node [midway, right] (TextNode) {$dR$} (dR1);
    \path [line, very thick] (S1) to node [midway, above] (TextNode) {$\beta SI$} (I1);
    \path [line, very thick] (I1) to node [midway, above] (TextNode) {$\gamma I$} (R1);
    \node [circle, fill=green!50, text=black] at (0,1\yskip) (S2) {$S$};
    \node [circle, fill=red!90, text=black] at (1\skip,1\yskip) (I2) {$I$};
    \node [circle, fill=blue!90, text=black] at (2\skip,1\yskip) (R2) {$R$};
    %% Flows
    \path [line, very thick] (S2) to node [midway, above] (TextNode) {$\beta SI$} (I2);
    \path [line, very thick] (I2) to node [midway, above] (TextNode) {$\gamma I$} (R2);
    \draw [>=latex,->, thick, rounded corners] (R2) -- (2\skip,0.75\yskip) -- (0,0.75\yskip) node[sloped, midway, above] {$\nu R$} -- (S2);
    %% Regular nodes
    \node [circle, fill=green!50, text=black] at (0\skip,2\yskip) (S3) {$S$};
    \node [circle, fill=red!90, text=black] at (1\skip,2\yskip) (I3) {$I$};
    \node [circle, fill=blue!90, text=black] at (2\skip,2\yskip) (R3) {$R$};
    %% Fake nodes for arrows
    \node [left=1cm of S3] (birth3) {};
    \node [below=0.5cm of S3] (dS3) {};
    \node [below=0.5cm of I3] (dI3) {};
    \node [below=0.5cm of R3] (dR3) {};
    %% Flows
    \path [line, very thick] (birth3) to node [midway, above] (TextNode) {$b(N)$} (S3);
    \path [line, very thick] (S3) to node [midway, right] (TextNode) {$dS$} (dS3);
    \path [line, very thick] (I3) to node [midway, right] (TextNode) {$dI$} (dI3);
    \path [line, very thick] (R3) to node [midway, right] (TextNode) {$dR$} (dR3);
    \path [line, very thick] (S3) to node [midway, above] (TextNode) {$\beta SI$} (I3);
    \path [line, very thick] (I3) to node [midway, above] (TextNode) {$\gamma I$} (R3);
    \draw [>=latex,->, thick, rounded corners] (R3) -- (2\skip,1.75\yskip) -- (0,1.75\yskip) node[sloped, midway, above] {$\nu R$} -- (S3);
  \end{tikzpicture}    
\end{center}
\end{frame}


\begin{frame}{The model}
\begin{minipage}{0.25\textwidth}
  \def\skip{*-1.5}
  \begin{tikzpicture}[scale=1, transform shape]
    %% Regular nodes
    \node [circle, fill=green!50, text=black] at (0,0) (S) {$S$};
    \node [circle, fill=red!90, text=black] at (0,1\skip) (I) {$I$};
    \node [circle, fill=blue!90, text=black] at (0,2\skip) (R) {$R$};
    %% Fake nodes for arrows
    \node [above=1cm of S] (birth) {};
    \node [left=0.5cm of S] (dS) {};
    \node [left=0.5cm of I] (dI) {};
    \node [left=0.5cm of R] (dR) {};
    %% Flows
    \path [line, very thick] (birth) to node [midway, left] (TextNode) {$b(N)$} (S);
    \path [line, very thick] (S) to node [midway, above] (TextNode) {$dS$} (dS);
    \path [line, very thick] (I) to node [midway, above] (TextNode) {$dI$} (dI);
    \path [line, very thick] (R) to node [midway, above] (TextNode) {$dR$} (dR);
    \path [line, very thick] (S) to node [midway, right] (TextNode) {$\beta SI$} (I);
    \path [line, very thick] (I) to node [midway, right] (TextNode) {$\gamma I$} (R);
    \draw [>=latex,->, thick, rounded corners] (R) -- (0.75,2\skip) -- (0.75,0) node[midway, right] {$\nu R$} -- (S);
  \end{tikzpicture}    
\end{minipage}
\begin{minipage}{0.7\textwidth}
  \begin{subequations} \label{sys:SIRS_base}
  \begin{align}
    S\pprime &= b(N)+\nu R-dS-\beta SI \label{sys:SIRS_base_dS} \\
    I\pprime &= \beta SI-(d+\gamma) I \label{sys:SIRS_base_dI} \\
    R\pprime &= \gamma I-(d+\nu)R \label{sys:SIRS_base_dR}
  \end{align}    
  \end{subequations}
  \vskip1cm
  Consider the initial value problem consisting in \eqref{sys:SIRS_base} to which we adjoin initial conditions $S(0)=S_0\geq 0$, $I(0)=I_0\geq 0$ and $R(0)=R_0\geq 0$
  \vskip1cm
  Typically, we assume $N_0=S_0+I_0+R_0>0$ to avoid a trivial case
  \end{minipage}
\end{frame}

\begin{frame}{Birth and death are \emph{relative}}
  Remark that the notions of \emph{birth} and \emph{death} are relative to the population under consideration
  \vfill
  E.g., consider a model for human immunodeficiency virus (HIV) in an at-risk population of intravenous drug users. Then
  \begin{itemize}
    \item birth is the moment the at-risk behaviour starts 
    \item death is the moment the at-risk behaviour stops,  whether from ``real death'' or because the individual stops using drugs
  \end{itemize}
\end{frame}

\begin{frame}{Choosing a form for demography}
Before we proceed with the analysis proper, we must discuss the nature of the assumptions on demography
\vfill
To do this, we consider the behaviour of the total population 
\[
N(t)=S(t)+I(t)+R(t)
\]
\end{frame}

\begin{frame}{Behaviour of the total population}
Summing the equations in \eqref{sys:SIRS_base}
\begin{equation}\label{eq:total_pop_general}
N\pprime=b(N)-dN
\end{equation}
\vfill
There are three common ways to define $b(N)$ in \eqref{eq:total_pop_general}
\begin{enumerate}
\item $b(N)=b$
\item $b(N)=bN$
\item $b(N)=bN-cN^2$
\end{enumerate}
\vfill
Case 3 leads to logistic dynamics of the total population and is not discussed here
\end{frame}


\begin{frame}{Case of a birth rate constant \emph{per capita}}
If $b(N)=bN$, then birth in \eqref{eq:total_pop_general} satisfies $N'/N=b$; we say that birth is \defword{constant \emph{per capita}}
\vfill
In this case, \eqref{eq:total_pop_general} takes the form
\[
N\pprime=bN-dN=(b-d)N
\]
with initial condition $N(0)=N_0$
\vfill
The solution to this scalar autonomous ODE is easy
\[
N(t)=N_0e^{(b-d)t},\quad t\geq 0
\]
Thus there are 3 possibilities:
\begin{itemize}
  \item if $b>d$, $N(t)\to\infty$, the total population explodes 
  \item if $b=d$, $N(t)\equiv N_0$, the total population remains constant 
  \item if $b<d$, $N(t)\to 0$, the total population collapses
\end{itemize}
\end{frame}

\begin{frame}{From now on, assume $b(N)=b$}
\bbullet We want a reasonable case, we could therefore suppose that $b(N)=d$, which would lead to a constant total population
\vfill
\bbullet However, this is a little reductive, so we choose instead $b(N)=b$, which, we will see, works as well even though it can initially be thought of as not being very realistic
\end{frame}


\begin{frame}{The model (for good this time)}
\begin{minipage}{0.25\textwidth}
  \def\skip{*-1.5}
  \begin{tikzpicture}[scale=1, transform shape]
    %% Regular nodes
    \node [circle, fill=green!50, text=black] at (0,0) (S) {$S$};
    \node [circle, fill=red!90, text=black] at (0,1\skip) (I) {$I$};
    \node [circle, fill=blue!90, text=black] at (0,2\skip) (R) {$R$};
    %% Fake nodes for arrows
    \node [above=1cm of S] (birth) {};
    \node [left=0.5cm of S] (dS) {};
    \node [left=0.5cm of I] (dI) {};
    \node [left=0.5cm of R] (dR) {};
    %% Flows
    \path [line, very thick] (birth) to node [midway, left] (TextNode) {$b$} (S);
    \path [line, very thick] (S) to node [midway, above] (TextNode) {$dS$} (dS);
    \path [line, very thick] (I) to node [midway, above] (TextNode) {$dI$} (dI);
    \path [line, very thick] (R) to node [midway, above] (TextNode) {$dR$} (dR);
    \path [line, very thick] (S) to node [midway, right] (TextNode) {$\beta SI$} (I);
    \path [line, very thick] (I) to node [midway, right] (TextNode) {$\gamma I$} (R);
    \draw [>=latex,->, thick, rounded corners] (R) -- (0.75,2\skip) -- (0.75,0) node[midway, right] {$\nu R$} -- (S);
  \end{tikzpicture}    
\end{minipage}
\begin{minipage}{0.7\textwidth}
  \begin{subequations} \label{sys:SIRS}
  \begin{align}
    S\pprime &= b+\nu R-dS-\beta SI \label{sys:SIRS_dS} \\
    I\pprime &= \beta SI-(d+\gamma) I \label{sys:SIRS_dI} \\
    R\pprime &= \gamma I-(d+\nu)R \label{sys:SIRS_dR}
  \end{align}    
  \end{subequations}
  \vskip1cm
  Consider the initial value problem consisting in \eqref{sys:SIRS} to which we adjoin initial conditions $S(0)=S_0\geq 0$, $I(0)=I_0\geq 0$ and $R(0)=R_0\geq 0$
  \vskip1cm
  Typically, we assume $N_0=S_0+I_0+R_0>0$ to avoid a trivial case
  \end{minipage}
\end{frame}


%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%
\subsection{Mathematical analysis}


\begin{frame}{Is the system well-posed?} 
For an ODE epidemiological model
\vfill
\bbullet Do solutions to \eqref{sys:SIRS} exist and are they unique?
\vfill
\bbullet Is the positive cone invariant under the flow of \eqref{sys:SIRS}?
\vfill
\bbullet Are solutions to \eqref{sys:SIRS} bounded?
Some models have unbounded solutions but they are rare and will need to be considered specifically
\end{frame}

\begin{frame}{Solutions exist and are unique}
\bbullet The vector field is always $C^1$, implying that solutions exist and are unique
\vfill
If we had instead considered an incidence of the form $f(S,I,N)=\beta SI/N$ and, say, demography with $b(N)=bN$, then some discussion might have been needed if $b<d$
\end{frame}


\begin{frame}{Invariance of $\IR_+^3$ under the flow (1)}
Let us start by assuming that $I(0)=I_0=0$. Then \eqref{sys:SIRS_dI} remains $I\pprime=0$, meaning that the $SR$-plane (i.e., the set $\{I=0\}$) is positively invariant under the flow of \eqref{sys:SIRS}
\vfill
On that plane, \eqref{sys:SIRS} reduce to
\begin{subequations}\label{sys:SIRS_on_Ieq0}
\begin{align}
S\pprime &= b+\nu R-dS \\
R\pprime &= -(d+\nu)R
\end{align}    
\end{subequations}
\vfill
$\implies$ a solution with $I_0>0$ cannot enter the plane $\{I=0\}$. Indeed, suppose that $I_0>0$ but $\exists t_\star>0$ such that $I(t_\star)=0$. Then at $(S(t_\star),I(t_\star)=0,R(t_\star))$, there are two solutions to \eqref{sys:SIRS}: the one we just generated as well as the one governed by \eqref{sys:SIRS_on_Ieq0}
\vfill
This contradicts uniqueness of solutions to \eqref{sys:SIRS}
\end{frame}

\begin{frame}{Invariance of $\IR_+^3$ under the flow (2)} 
We saw that $I(t)>0$ if $I(0)>0$
\vfill
Suppose now that $S=0$. Equation \eqref{sys:SIRS_dS} is then
$$
S\pprime = b+\nu R>0
$$
\vfill
So if $S(0)=S_0>0$, then $S(t)>0$ for all $t$. If, on the other hand, $S_0=0$, then $S(t)>0$ for $t>0$ small; from what we just saw, this is then also true for all $t>0$
\vfill
We say the vector field points \emph{inward}
\vfill
$\implies$ $S$ cannot become zero
\vfill
Do the same for $R$
\end{frame}

\begin{frame}{To summarise, for invariance}
For simplicity, denote $\IR^\star=\IR\setminus\{0\}$
\vfill
\bbullet If $(S(0),I(0),R(0))\in\IR_+\times \IR_+^\star\times\IR_+$, then $\forall t>0$,
\[
(S(t),I(t),R(t))\in(\IR_+^\star)^3
\]
\vfill
\bbullet If $(S(0),I(0),R(0))\in\IR_+\times\{0\}\times\IR_+$, then $\forall t\geq 0$, 
\[
(S(t),I(t),R(t))\in\IR_+^\star\times\{0\}\times\IR_+
\]
\vfill
The model is therefore satisfactory in that it does not allow solutions to become negative
\end{frame}

\begin{frame}{Remark -- Know your audience} 
This reasoning has its place in an MSc of PhD manuscript: you need to demonstrate that you know what to do and how to do it
\vfill
In a research paper, this is not really necessary and actually often superfluous; the statement \emph{it is easy to show that solutions exist uniquely and that the positive orthant is invariant under the flow of the system} is typically sufficient
\vfill
(However, be sure to cover your bases: don't show the proof in the paper but have it in your notes.. \emph{it is easy to show} can be a dangerous statement if it is not easy...)
\end{frame}


\begin{frame}{The total population is asymptotically constant}
Since $b(N)=b$, the total population equation \eqref{eq:total_pop_general} takes the form
\[
N\pprime = b-dN
\]
This equation has a unique equilbrium $N^\star=b/d$ and it is very easy to check that this equilibrium is GAS: this is a scalar autonomous equation, so solutions are monotone; they increase to $N^\star$ if $N_0<N^\star$ and decrease to $N^\star$ if $N_0>N^\star$
\vfill
So we can work at the limit $N^\star$ where $R=N^\star-(S+I)$ and thus drop the equation for $R$
\end{frame}


\begin{frame}{Boundedness}
It follows from what we just saw that the positive cone $\IR_+^3$ is (positively) invariant under the flow of \eqref{sys:SIRS}
\vfill
Since $N(t)\to N^\star$, we deduce that solutions of \eqref{sys:SIRS} are bounded
\end{frame}


\begin{frame}{Seeking equilibria}
We seek $S=S^\star, I=I^\star, R=R^\star$ such that
\begin{subequations} \label{sys:SIRS_EP}
\begin{align}
0 &= b+\nu R-dS-\beta SI \label{sys:SIRS_EP_dS} \\
0 &= \beta SI-(d+\gamma) I \label{sys:SIRS_EP_dI} \\
0 &= \gamma I-(d+\nu)R \label{sys:SIRS_EP_dR}
\end{align}    
\end{subequations}
\vfill
From \eqref{sys:SIRS_EP_dI}, either $I^\star=0$ or $\beta S-(d+\gamma)=0$, i.e., $S^\star=(d+\gamma)/\beta$
\vfill
When $I^\star=0$, substituting $I^\star=0$ into \eqref{sys:SIRS_EP_dR} implies that $R^\star=0$ and, in turn, substituting $I^\star=R^\star=0$ into \eqref{sys:SIRS_EP_dR} gives $S^\star=b/d$. This gives the disease-free equilibrium (DFE)
\begin{equation}\label{eq:SIRS_DFE}
\bE_0:=(S^\star,I^\star,R^\star)=
\left(\frac bd, 0, 0\right)
\end{equation}
\vfill
We return to $S^\star=(d+\gamma)/\beta$ in a while
\end{frame}



\begin{frame}{Classic method for computing $\R_0$}
$\R_0$ is the surface in parameter space where the DFE loses its LAS
\vfill
To find $\R_0$, we therefore study the LAS of the DFE
\vfill
In an arbitrary $(S,I,R)$, the Jacobian matrix of \eqref{sys:SIRS} takes the form
\begin{equation}
\label{eq:SIRS_Jacobian}
J_{(S,I,R)} =
\begin{pmatrix}
-d-\beta I & -\beta S & \nu \\
\beta I & \beta S-(d+\gamma) & 0 \\
0 & \gamma & -(d+\nu)
\end{pmatrix}
\end{equation}
\end{frame}

\begin{frame}
The LAS of the DFE depends on the sign of the real parts of the eigenvalues of \eqref{eq:SIRS_Jacobian} at that equilibrium point, so we evaluate
\begin{equation}
\label{eq:SIRS_Jacobian_DFE}
J_{\bE_0} =
\begin{pmatrix}
-d & -\beta S^\star & \nu \\
0 & \beta S^\star-(d+\gamma) & 0 \\
0 & \gamma & -(d+\nu)
\end{pmatrix}
\end{equation}
\vfill
Block upper triangular matrix $\implies$ eigenvalues are $-d<0$, $-(d+\nu)<0$ and $\beta S^\star-(d+\gamma)$ 
\vfill
$\implies$ LAS of the DFE determined by sign of $\beta S^\star-(d+\gamma)$
\end{frame}


\begin{frame}{Sign of $\beta S^\star-(d+\gamma)$}
Recall that at the DFE \eqref{eq:SIRS_DFE}, $S^\star=b/d$, so
\[
\text{sign}(\beta S^\star-(d+\gamma))
=\text{sign}\left(
\beta\frac{b}{d} -(d+\gamma)
\right)
\]
So the DFE is LAS if
\[
\beta\frac bd < d+\gamma
\iff \frac\beta{d+\gamma}\ \frac bd <1
\]
Denote
\begin{equation}\label{eq:SIRS_R0}
\R_0 = \frac\beta{d+\gamma}\ \frac bd
\end{equation}
\vfill
(We sometimes emphasise that $b/d=N^\star$, the total population, and thus write $\R_0=\beta N^\star/(d+\gamma)$)
\end{frame}


\begin{frame}{Seeking equilibria (2)}
Now consider the second EP where $S^\star=(d+\gamma)/\beta=N^\star/\R_0$
\vfill
Write \eqref{sys:SIRS_EP_dR} as $R^\star=\gamma I^\star/(d+\nu)$
\vfill
Since $S^\star+I^\star+R^\star=N^\star$, this means that
\[
N^\star-S^\star-I^\star = \gamma I^\star/(d+\nu)
\]
so substituting $S^\star = N^\star/\R_0$,
\[
\left(1+\frac{\gamma}{d+\nu}\right)I^\star = \left(1-\frac{1}{\R_0}\right)N^\star
\]
So finally
\[
I^\star = \left(1-\frac{1}{\R_0}\right)\
\frac{d+\nu}{d+\nu+\gamma}\ N^\star
\]
\end{frame}


\begin{frame}{The EEP}
The \defword{endemic equilibrium} (EEP) of \eqref{sys:SIRS} is
\begin{multline}\label{eq:SIRS_EEP}
\bE_\star:=(S^\star,I^\star,R^\star) = \\
\left(
\frac{1}{\R_0}\ N^\star,
\left(1-\frac{1}{\R_0}\right)\
\frac{d+\nu}{d+\nu+\gamma}\ N^\star,
N^\star-(S^\star+I^\star)
\right)
\end{multline}
\vfill
Remark that $\bE_\star$ is \defword{not biologically relevant} when $\R_0\leq 1$
\end{frame}


\begin{frame}
\begin{theorem}\label{th:SIRS_LAS_DFE}
Let the basic reproduction number be
\begin{equation}\tag{\ref{eq:SIRS_R0}}
\R_0 = \frac\beta{d+\gamma}\ N^\star
\end{equation}
and consider the EP of \eqref{sys:SIRS}: the DFE
\begin{equation}\tag{\ref{eq:SIRS_DFE}}
\bE_0=
\left(\frac bd, 0, 0\right)
\end{equation}
and the EEP
\begin{equation}\tag{\ref{eq:SIRS_EEP}}
\bE_\star=
\left(
\frac{1}{\R_0}\ N^\star,
\left(1-\frac{1}{\R_0}\right)\
\frac{d+\nu}{d+\nu+\gamma}\ N^\star,
N^\star-(S^\star+I^\star)
\right)
\end{equation}
\vskip0.5cm
\begin{itemize}
\item If $\R_0<1$, then $\bE_0$ is LAS and $\bE_\star$ is not biologically relevant
\item If $\R_0>1$, then $\bE_0$ is unstable and $\bE_\star$ is biologically relevant
\end{itemize}
\end{theorem}
\end{frame}

\begin{frame}
As you can probably guess, if $\R_0>1$, then $\bE_\star$ is not only biologically relevant but actually also LAS
\vfill
Recall the Jacobian
\begin{align}
\tag{\ref{eq:SIRS_Jacobian}}
J_{(S,I,R)} &=
\begin{pmatrix}
-d-\beta I & -\beta S & \nu \\
\beta I & \beta S-(d+\gamma) & 0 \\
0 & \gamma & -(d+\nu)
\end{pmatrix} \\
&= \begin{pmatrix}
-\beta I & -\beta S & \nu \\
\beta I & \beta S-\gamma & 0 \\
0 & \gamma & -\nu
\end{pmatrix}
-d\II  \nonumber
\end{align}
\vfill
From this, we get that $-d$ is an eigenvalue of $J$
\begin{itemize}
\item there is a theorem that tells us that if $\lambda\in\sigma(M)$, then $\lambda+k\in\sigma(M+k\II)$ \qquad($\sigma(M)$ is the spectrum of $M$, the set of eigenvalues of $M$)
\item the first matrix on the second line has all column sums zero so has a zero eigenvalue
\end{itemize}
\end{frame}

\begin{frame}
We could continue and after some blood, sweat and tears, get that $J_{\bE_\star}$ has its eigenvalues with negative real parts when $\bE_\star$ is biologically relevant, i.e., when $\R_0>1$
\vfill
With even more blood, sweat and tears, we can actually show that the result is \emph{global}
\vfill We express that on the next slide
\end{frame}

\begin{frame}
\begin{theorem}\label{th:SIRS_GAS_behaviour}
Let the basic reproduction number be defined by \eqref{eq:SIRS_R0} and consider the DFE \eqref{eq:SIRS_DFE} and the EEP \eqref{eq:SIRS_EEP}
\vskip1cm
\begin{itemize}
\item If $\R_0<1$, then $\bE_0$ is globally asymptotically stable (GAS) and $\bE_\star$ is not biologically relevant
\item If $\R_0>1$, then $\bE_0$ is unstable and $\bE_\star$ is GAS
\end{itemize}
\end{theorem}
\vfill
In other words
\begin{itemize}
\item when $\R_0<1$, then all solutions go to the DFE, the disease goes \defword{extinct}
\item when $\R_0>1$, then all solutions go to the EEP, the disease becomes \defword{endemic}
\end{itemize}
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%
\subsection{Some numerics}


\begin{frame}[fragile]
\begin{lstlisting}
library(deSolve)
rhs_SIRS <- function(t, x, p) {
  with(as.list(c(x, p)), {
    dS = b + nu * R - d * S - beta * S * I
    dI = beta * S * I - (d + gamma) * I
    dR = gamma * I - (d + nu) * R
    return(list(c(dS, dI, dR)))
  })
}
# Initial conditions
N0 = 1000
I0 = 1
R0 = 0
IC = c(S = N0-(I0+R0), I = I0, R = R0)
# "Known" parametres
d = 1/(80*365.25)
b = N0 * d
gamma = 1/14
nu = 1/365.25
\end{lstlisting}
\end{frame}

\begin{frame}[fragile]
\begin{lstlisting}
# Set beta s.t. R_0 = 1.5
R_0 = 1.5
beta = R_0 * (d + gamma) / (N0-I0-R0)
params = list(b = b, d = d, gamma = gamma, beta = beta, nu = nu)
times = seq(0, 365, 1)
# Call the numerical integrator
sol_SIRS <- ode(y = IC, times = times, func = rhs_SIRS, 
                parms = params, method = "ode45")
# Plot the result
plot(sol_SIRS[,"time"], sol_SIRS[,"I"], 
     type = "l", lwd = 2,
     xlab = "Time (days)", ylab = "Prevalence")
\end{lstlisting}
\end{frame}

<<SIRS_one_sim_prevalence,eval=TRUE,echo=FALSE,fig=TRUE,width=8,height=5,include=FALSE>>=
library(deSolve)
rhs_SIRS <- function(t, x, p) {
  with(as.list(c(x, p)), {
    dS = b + nu * R - d * S - beta * S * I
    dI = beta * S * I - (d + gamma) * I
    dR = gamma * I - (d + nu) * R
    return(list(c(dS, dI, dR)))
  })
}
# Initial conditions
N0 = 1000
I0 = 1
R0 = 0
IC = c(S = N0-(I0+R0), I = I0, R = R0)
# "Known" parametres
d = 1/(80*365.25)
b = N0 * d
gamma = 1/14
nu = 1/365.25
# Set beta s.t. R_0 = 1.5
R_0 = 1.5
beta = R_0 * (d + gamma) / (N0-I0-R0)
params = list(b = b, d = d, gamma = gamma, beta = beta, nu = nu)
times = seq(0, 500, 1)
# Call the numerical integrator
sol_SIRS <- ode(y = IC, times = times, func = rhs_SIRS, 
                parms = params, method = "ode45")
# Plot the result
plot(sol_SIRS[,"time"], sol_SIRS[,"I"], 
     type = "l", lwd = 2,
     xlab = "Time (days)", ylab = "Prevalence")
crop_figure("FIGS/lecture-01-SIRS_one_sim_prevalence")
@

\begin{frame}{}
  \begin{center}
    \includegraphics[width=\textwidth]{FIGS/lecture-01-SIRS_one_sim_prevalence}
  \end{center}
\end{frame}

\begin{frame}{I just did ...}

What I advise not to do: illustrate a mathematical result without adding anything to the result itself
\vfill
Let us make things a bit better. See the \href{https://raw.githubusercontent.com/julien-arino/3MC-2023-12-Arba-Minch/main/CODE/ODE_SIS_multiple_solutions.R}{code}
\end{frame}

<<SIRS_3_sims_prevalence,eval=TRUE,echo=FALSE,fig=TRUE,width=8,height=5,include=FALSE>>=
# Compute the EPs
valeur_PE = function(params) {
  with(as.list(c(params)), {
    OUT = list()
    if (R_0<1) {
      OUT$S_EP = Pop
      OUT$I_EP = 0
      OUT$col = "dodgerblue4"
    } else {
      OUT$S_EP = 1/R_0*Pop
      OUT$I_EP = (1-1/R_0)*(d+nu)/(d+nu+gamma)*Pop
      OUT$col = "darkorange4"
    }
    return(OUT)
  })
}
# RHS function set in previous chunk

# Put the parameters in a list
# "Known" parametres
params = list()
params$Pop = N0
params$d = 1/(80 * 365.25)
params$b = params$Pop * params$d
params$gamma = 1/14
params$nu = 1/365.25
params$t_f = 1200
params$I_0 = I0
# Note that we did not set R_0 or beta. This is done in a loop

# IC. "Static" part (N0, I0, R0) of IC are set in previous chunk
IC = c(S = N0-(I0+R0), I = I0, R = R0)

# Times at which the solution will be returned.
tspan = seq(from = 0, to = params$t_f, by = 0.1)

# Now simulate the ODE. Loop on several values of R_0
R_0 = c(0.8, 1.5, 2.5)
# Save results in a list together with EP values
sol_ODE = list()
EP = list()
# Now loop on R_0
for (r_0 in R_0) {
  # Name for list entry
  entry_name = sprintf("$R_0$=%1.1f",r_0)
  # Keep the current value of R_0 to compute EPs
  params$R_0 = r_0
  # R0=(beta/(d+gamma)) => beta=R0*(d+gamma)
  params$beta = r_0 * (params$d+params$gamma) / (N0-I0-R0)
  # Call numerical integrator
  sol_ODE[[entry_name]] = ode(y = IC,
                              func = rhs_SIRS,
                              times = tspan,
                              parms = params)
  EP[[entry_name]] = valeur_PE(params)
  EP[[entry_name]]$lty = which(r_0 == R_0)
}

# Get maximum value of I across all simulations for plot. Note the use of lapply.
max_I = max(unlist(lapply(sol_ODE, function(x) max(x[,"I"]))))

# Plot
y_axis = plot_hr_yaxis(sol_ODE[[1]][,"time"], sol_ODE[[1]][,"I"],
                       y_range = c(0, max_I),
                       type = "l", lwd = 5, col = EP[[1]]$col, lty = EP[[1]]$lty,
                       xlab = "Time (days)", ylab = "Prevalence")
points(x = params$t_f, y = EP[[1]]$I_EP*y_axis$factor, 
       col = EP[[1]]$col, pch = 19, cex = 2)
for (i in 2:length(sol_ODE)) {
  lines(sol_ODE[[i]][,"time"], sol_ODE[[i]][,"I"]*y_axis$factor,
        type = "l", lwd = 5, col = EP[[i]]$col, lty = EP[[i]]$lty)
  points(x = params$t_f, y = EP[[i]]$I_EP*y_axis$factor, 
         col = EP[[i]]$col, pch = 19, cex = 2)
}
legend("topright", legend = TeX(names(EP)), cex = 0.8,
       col = unlist(lapply(EP, function(x) x$col)),
       lty = unlist(lapply(EP, function(x) x$lty)),
       lwd = c(3,3,3))
@

\begin{frame}{}
  \begin{center}
    \includegraphics[width=\textwidth]{FIGS/lecture-01-SIRS_3_sims_prevalence}
  \end{center}
\end{frame}

\begin{frame}
We could continue, but with a model this simple, there is little  more to do: the 3 parameters of the system are combined within $\R_0$ and the latter summarises the dynamics well
\vfill
We are going to show something important: the bifurcation diagram
\vfill
We saw that when $\R_0<1$, $I\to 0$, whereas when $\R_0>1$, $I\to (1-1/\R_0)N$. Let us represent this (\href{https://raw.githubusercontent.com/julien-arino/3MC-2023-12-Arba-Minch/main/CODE/SIS_PEI_vs_R0.R}{code})
\end{frame}

<<SIRS_bifurcation_R0,eval=TRUE,echo=FALSE,fig=TRUE,width=8,height=5,include=FALSE>>=
# Values of the EPs
value_EPs = function(R_0, N) {
  EP_I = ifelse(R_0 < 1, 0, (1-1/R_0)*N)
  return(EP_I)
}

R_0 = seq(0.5, 5, by = 0.01)
EP_I = value_EPs(R_0, N = 1000)
# We also show the DFE when R_0>1, so prepare this
R_0_geq_1 = R_0[which(R_0>=1)]
DFE = rep(0, length(R_0_geq_1))

plot(R_0, EP_I,
     type = "l", lwd = 3,
     xlab = TeX("$R_0$"),
     las = 1,
     ylab = "Prevalence at equilibrium")
lines(R_0_geq_1, DFE,
      type = "l", lwd = 3,
      lty = 2)
legend("topleft", legend = c("LAS EP", "Unstable EP"),
       lty = c(1, 2), lwd = c(2,2),
       bty = "n")
@

\begin{frame}
  \begin{center}
    \includegraphics[width=\textwidth]{FIGS/lecture-01-SIRS_bifurcation_R0}
  \end{center}
\end{frame}



%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%
\subsection{An SIRS model with vaccination}

\begin{frame}{An SIRS model with vaccination}
Take SIRS model \eqref{sys:SIRS} and assume the following
\vfill
\begin{itemize}
\item Vaccination takes newborn individuals and moves them directly into the removed compartment, without them becoming infected/infectious
\vfill
\item A fraction $p$ is vaccinated at birth
\end{itemize}
\end{frame}

\begin{frame}{The model}
\begin{minipage}{0.25\textwidth}
  \def\skip{*-1.5}
  \begin{tikzpicture}[scale=1, transform shape]
    %% Regular nodes
    \node [circle, fill=green!50, text=black] at (0,0) (S) {$S$};
    \node [circle, fill=red!90, text=black] at (0,1\skip) (I) {$I$};
    \node [circle, fill=blue!90, text=black] at (0,2\skip) (R) {$R$};
    %% Fake nodes for arrows
    \node [above=1cm of S] (birthS) {};
    \node [below=1cm of R] (birthR) {};
    \node [left=0.5cm of S] (dS) {};
    \node [left=0.5cm of I] (dI) {};
    \node [left=0.5cm of R] (dR) {};
    %% Flows
    \path [line, very thick, red] (birthS) to node [midway, right] (TextNode) {$(1-p)b$} (S);
    \path [line, very thick, red] (birthR) to node [midway, right] (TextNode) {$pb$} (R);
    \path [line, very thick] (S) to node [midway, above] (TextNode) {$dS$} (dS);
    \path [line, very thick] (I) to node [midway, above] (TextNode) {$dI$} (dI);
    \path [line, very thick] (R) to node [midway, above] (TextNode) {$dR$} (dR);
    \path [line, very thick] (S) to node [midway, right] (TextNode) {$\beta SI$} (I);
    \path [line, very thick] (I) to node [midway, right] (TextNode) {$\gamma I$} (R);
    \draw [>=latex,->, thick, rounded corners] (R) -- (0.8,2\skip) -- (0.8,0) node[midway, right] {$\nu R$} -- (S);
    \end{tikzpicture}    
\end{minipage}
\begin{minipage}{0.7\textwidth}
  \begin{subequations} \label{sys:SIR_vacc}
  \begin{align}
    S\pprime &= (1-p)b+\nu R-dS-\beta SI \label{sys:SIR_vacc_dS} \\
    I\pprime &= \beta SI-(d+\gamma) I \label{sys:SIR_vacc_dI} \\
    R\pprime &= bp+\gamma I-(d+\nu)R \label{sys:SIR_vacc_dR}
  \end{align}    
  \end{subequations}
  \vskip1cm
  Consider the initial value problem consisting in \eqref{sys:SIR_vacc} to which we adjoin initial conditions $S(0)=S_0\geq 0$, $I(0)=I_0\geq 0$ and $R(0)=R_0\geq 0$
  \vskip1cm
  Typically, we assume $N_0=S_0+I_0+R_0>0$ to avoid a trivial case
  \end{minipage}
\end{frame}

\begin{frame}{This modification doesn't change much}
Equation \eqref{eq:total_pop_general} for the total population is unchanged
\vfill
The Jacobian \eqref{eq:SIRS_Jacobian} at arbitrary point is also unchanged
\vfill 
The DFE is affected, though; as a consequence, so is the reproduction number
\end{frame}

\begin{frame}{The DFE for the SIRS vaccination model}
Considering \eqref{sys:SIR_vacc} at equilibrium and substituting $I^\star=0$ into this system gives
\begin{align*}
0 &= (1-p)b+\nu R^\star-dS^\star \\
0 &= bp-(d+\nu)R^\star
\end{align*}
which we rewrite as the linear system
\[
\begin{pmatrix}
d & -\nu \\ 0 & d+\nu
\end{pmatrix}
\begin{pmatrix}
S^\star \\ R^\star
\end{pmatrix}
=
\begin{pmatrix}
(1-p)b \\ bp
\end{pmatrix}
\]
Thus
\begin{align*}
\begin{pmatrix}
S^\star \\ R^\star
\end{pmatrix}
&= \frac{1}{d(d+\nu)}
\begin{pmatrix}
d+\nu & \nu \\ 0 & d
\end{pmatrix}
\begin{pmatrix}
(1-p)b \\ pb
\end{pmatrix} \\
&= \frac{1}{d(d+\nu)}
\begin{pmatrix}
(d+\nu)(1-p)b+pb\nu \\ pbd
\end{pmatrix}
\end{align*}
\end{frame}

\begin{frame}
As a consequence, the DFE takes the form
\begin{equation}\label{eq:SIRS_vacc_DFE}
\bE_0^v := (S^\star,I^\star,R^\star) =
\left(
\left(1-p+\frac{p\nu}{d+\nu}\right)N^\star,0,
\frac{pd}{d+\nu}N^\star
\right)
\end{equation}
\vfill
Substituting \eqref{eq:SIRS_vacc_DFE} into the eigenvalue that determines stability of the DFE, $\beta S^\star-(d+\gamma)$, we get
\begin{align*}
\beta S^\star-(d+\gamma)<0 &\iff
\frac\beta{d+\gamma} S^\star <1 \\
&\iff 
\frac\beta{d+\gamma}
\left(1-p+\frac{p\nu}{d+\nu}\right)N^\star<1
\end{align*}
So we define
\begin{equation}\label{eq:SIRS_vacc_R0}
\R_0^v =
\frac\beta{d+\gamma}
\left(1-p+\frac{p\nu}{d+\nu}\right)N^\star
\end{equation}
\end{frame}


\begin{frame}{Herd immunity}
  Therefore 
  \begin{itemize}
  \item $\R_0^{\textrm{v}}<\R_0$ if $p>0$
  \item To control the disease, $\R_{\text{v}}$ must take a value less than 1, i.e.,
  \begin{equation}
    \R_{\text{v}}<1 \iff p> 1-\frac{1}{\R_0}
  \end{equation}
  \end{itemize}
  \vfill
  By vaccinating a fraction $p>1-1/\R_0$ of newborns, we thus are in a situation where the disease is eventually eradicated
  \vfill
  This is \defword{herd immunity} (\emph{bis repetita})
\end{frame}


%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Last remarks}

\begin{frame}{To simplify or not to simplify?}
\bbullet In the KMK epidemic model \eqref{sys:KMK} and the SIRS endemic model \eqref{sys:SIRS}, since the total population is constant or asymptotically constant, it is possible to omit one of the state variables since $N^\star=S+I+R$
\vfill
\bbullet We often use $R=N^\star-S-I$
\vfill
\bbullet This can greatly simplify some computations
\vfill
\bbullet Whether to do it or not is a matter of preference
\end{frame}

\begin{frame}{To normalise or not to normalise?}
\bbullet In the KMK epidemic model \eqref{sys:KMK} and the SIRS endemic model \eqref{sys:SIRS}, since the total population is constant or asymptotically constant, it is possible to normalise to $N=1$
\vfill
\bbullet This can greatly simplify some computations
\vfill
\bbullet However, I am not a big fan: it is important to always have the ``sizes'' of objects in mind
\vfill
\bbullet If you do normalise, at least for a paper destined to mathematical biology, always do a ``return to biology'', i.e., interpret your results in a biological light, which often implies to return to original values
\end{frame}

\begin{frame}{Where we are}
\bbullet An \emph{epidemic} SIR model (the KMK SIR) in which the presence or absence of an epidemic wave is characterised by the value of $\R_0$
\vfill
\bbullet The KMK SIR has explicit solutions (in some sense). \textbf{This is an exception!}
\vfill
\bbullet An \emph{endemic} SIRS model in which the threshold $\R_0=1$ is such that, when $\R_0<1$, the disease goes extinct, whereas when $\R_0>1$, the disease becomes established in the population
\end{frame}


\begin{frame}{Bibliography}
\bibliographystyle{apalike}
\bibliography{/home/jarino/github/bib-files/math,/home/jarino/github/bib-files/math_epi}
\end{frame}

\end{document}